
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read

        
@model(
    columns={'_data_modified_utc': 'date', '_metadata_modified_utc': 'datetime2', '_source': 'varchar(max)', 'FRANGO_GILTIG_FOM': 'varchar(max)', 'FRANGO_GILTIG_TOM': 'varchar(max)', 'FRANGO_ID': 'varchar(max)', 'FRANGO_ID_TEXT': 'varchar(max)', 'FRANGO_PASSIV': 'varchar(max)', 'FRANGO_TEXT': 'varchar(max)', 'FRARAD_GILTIG_FOM': 'varchar(max)', 'FRARAD_GILTIG_TOM': 'varchar(max)', 'FRARAD_ID': 'varchar(max)', 'FRARAD_ID_TEXT': 'varchar(max)', 'FRARAD_PASSIV': 'varchar(max)', 'FRARAD_TEXT': 'varchar(max)', 'FRASUM_GILTIG_FOM': 'varchar(max)', 'FRASUM_GILTIG_TOM': 'varchar(max)', 'FRASUM_ID': 'varchar(max)', 'FRASUM_ID_TEXT': 'varchar(max)', 'FRASUM_PASSIV': 'varchar(max)', 'FRASUM_TEXT': 'varchar(max)', 'FRIRA2_GILTIG_FOM': 'varchar(max)', 'FRIRA2_GILTIG_TOM': 'varchar(max)', 'FRIRA2_ID': 'varchar(max)', 'FRIRA2_ID_TEXT': 'varchar(max)', 'FRIRA2_PASSIV': 'varchar(max)', 'FRIRA2_TEXT': 'varchar(max)', 'FRIRAD_GILTIG_FOM': 'varchar(max)', 'FRIRAD_GILTIG_TOM': 'varchar(max)', 'FRIRAD_ID': 'varchar(max)', 'FRIRAD_ID_TEXT': 'varchar(max)', 'FRIRAD_PASSIV': 'varchar(max)', 'FRIRAD_TEXT': 'varchar(max)', 'FRISUM_GILTIG_FOM': 'varchar(max)', 'FRISUM_GILTIG_TOM': 'varchar(max)', 'FRISUM_ID': 'varchar(max)', 'FRISUM_ID_TEXT': 'varchar(max)', 'FRISUM_PASSIV': 'varchar(max)', 'FRISUM_TEXT': 'varchar(max)', 'KONTO_GILTIG_FOM': 'varchar(max)', 'KONTO_GILTIG_TOM': 'varchar(max)', 'KONTO_ID': 'varchar(max)', 'KONTO_ID_TEXT': 'varchar(max)', 'KONTO_PASSIV': 'varchar(max)', 'KONTO_TEXT': 'varchar(max)', 'KRES_GILTIG_FOM': 'varchar(max)', 'KRES_GILTIG_TOM': 'varchar(max)', 'KRES_ID': 'varchar(max)', 'KRES_ID_TEXT': 'varchar(max)', 'KRES_PASSIV': 'varchar(max)', 'KRES_TEXT': 'varchar(max)', 'KRGRP_GILTIG_FOM': 'varchar(max)', 'KRGRP_GILTIG_TOM': 'varchar(max)', 'KRGRP_ID': 'varchar(max)', 'KRGRP_ID_TEXT': 'varchar(max)', 'KRGRP_PASSIV': 'varchar(max)', 'KRGRP_TEXT': 'varchar(max)', 'KTO2_GILTIG_FOM': 'varchar(max)', 'KTO2_GILTIG_TOM': 'varchar(max)', 'KTO2_ID': 'varchar(max)', 'KTO2_ID_TEXT': 'varchar(max)', 'KTO2_PASSIV': 'varchar(max)', 'KTO2_TEXT': 'varchar(max)', 'SJKGRP_GILTIG_FOM': 'varchar(max)', 'SJKGRP_GILTIG_TOM': 'varchar(max)', 'SJKGRP_ID': 'varchar(max)', 'SJKGRP_ID_TEXT': 'varchar(max)', 'SJKGRP_PASSIV': 'varchar(max)', 'SJKGRP_TEXT': 'varchar(max)', 'SJKRAD_GILTIG_FOM': 'varchar(max)', 'SJKRAD_GILTIG_TOM': 'varchar(max)', 'SJKRAD_ID': 'varchar(max)', 'SJKRAD_ID_TEXT': 'varchar(max)', 'SJKRAD_PASSIV': 'varchar(max)', 'SJKRAD_TEXT': 'varchar(max)', 'UKONTO_GILTIG_FOM': 'varchar(max)', 'UKONTO_GILTIG_TOM': 'varchar(max)', 'UKONTO_ID': 'varchar(max)', 'UKONTO_ID_TEXT': 'varchar(max)', 'UKONTO_PASSIV': 'varchar(max)', 'UKONTO_TEXT': 'varchar(max)'},
    kind=dict(
        name=ModelKindName.FULL
    ),
    cron="@daily"
)

        
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = f"""
	SELECT * FROM (SELECT 
 		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _data_modified_utc,
		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _metadata_modified_utc,
		'ksp_rd_sll_se_Utdata_udp_100' as _source,
		CONVERT(varchar(max), FRANGO_GILTIG_FOM, 126) AS FRANGO_GILTIG_FOM,
		CONVERT(varchar(max), FRANGO_GILTIG_TOM, 126) AS FRANGO_GILTIG_TOM,
		CAST(FRANGO_ID AS VARCHAR(MAX)) AS FRANGO_ID,
		CAST(FRANGO_ID_TEXT AS VARCHAR(MAX)) AS FRANGO_ID_TEXT,
		CAST(FRANGO_PASSIV AS VARCHAR(MAX)) AS FRANGO_PASSIV,
		CAST(FRANGO_TEXT AS VARCHAR(MAX)) AS FRANGO_TEXT,
		CONVERT(varchar(max), FRARAD_GILTIG_FOM, 126) AS FRARAD_GILTIG_FOM,
		CONVERT(varchar(max), FRARAD_GILTIG_TOM, 126) AS FRARAD_GILTIG_TOM,
		CAST(FRARAD_ID AS VARCHAR(MAX)) AS FRARAD_ID,
		CAST(FRARAD_ID_TEXT AS VARCHAR(MAX)) AS FRARAD_ID_TEXT,
		CAST(FRARAD_PASSIV AS VARCHAR(MAX)) AS FRARAD_PASSIV,
		CAST(FRARAD_TEXT AS VARCHAR(MAX)) AS FRARAD_TEXT,
		CONVERT(varchar(max), FRASUM_GILTIG_FOM, 126) AS FRASUM_GILTIG_FOM,
		CONVERT(varchar(max), FRASUM_GILTIG_TOM, 126) AS FRASUM_GILTIG_TOM,
		CAST(FRASUM_ID AS VARCHAR(MAX)) AS FRASUM_ID,
		CAST(FRASUM_ID_TEXT AS VARCHAR(MAX)) AS FRASUM_ID_TEXT,
		CAST(FRASUM_PASSIV AS VARCHAR(MAX)) AS FRASUM_PASSIV,
		CAST(FRASUM_TEXT AS VARCHAR(MAX)) AS FRASUM_TEXT,
		CONVERT(varchar(max), FRIRA2_GILTIG_FOM, 126) AS FRIRA2_GILTIG_FOM,
		CONVERT(varchar(max), FRIRA2_GILTIG_TOM, 126) AS FRIRA2_GILTIG_TOM,
		CAST(FRIRA2_ID AS VARCHAR(MAX)) AS FRIRA2_ID,
		CAST(FRIRA2_ID_TEXT AS VARCHAR(MAX)) AS FRIRA2_ID_TEXT,
		CAST(FRIRA2_PASSIV AS VARCHAR(MAX)) AS FRIRA2_PASSIV,
		CAST(FRIRA2_TEXT AS VARCHAR(MAX)) AS FRIRA2_TEXT,
		CONVERT(varchar(max), FRIRAD_GILTIG_FOM, 126) AS FRIRAD_GILTIG_FOM,
		CONVERT(varchar(max), FRIRAD_GILTIG_TOM, 126) AS FRIRAD_GILTIG_TOM,
		CAST(FRIRAD_ID AS VARCHAR(MAX)) AS FRIRAD_ID,
		CAST(FRIRAD_ID_TEXT AS VARCHAR(MAX)) AS FRIRAD_ID_TEXT,
		CAST(FRIRAD_PASSIV AS VARCHAR(MAX)) AS FRIRAD_PASSIV,
		CAST(FRIRAD_TEXT AS VARCHAR(MAX)) AS FRIRAD_TEXT,
		CONVERT(varchar(max), FRISUM_GILTIG_FOM, 126) AS FRISUM_GILTIG_FOM,
		CONVERT(varchar(max), FRISUM_GILTIG_TOM, 126) AS FRISUM_GILTIG_TOM,
		CAST(FRISUM_ID AS VARCHAR(MAX)) AS FRISUM_ID,
		CAST(FRISUM_ID_TEXT AS VARCHAR(MAX)) AS FRISUM_ID_TEXT,
		CAST(FRISUM_PASSIV AS VARCHAR(MAX)) AS FRISUM_PASSIV,
		CAST(FRISUM_TEXT AS VARCHAR(MAX)) AS FRISUM_TEXT,
		CONVERT(varchar(max), KONTO_GILTIG_FOM, 126) AS KONTO_GILTIG_FOM,
		CONVERT(varchar(max), KONTO_GILTIG_TOM, 126) AS KONTO_GILTIG_TOM,
		CAST(KONTO_ID AS VARCHAR(MAX)) AS KONTO_ID,
		CAST(KONTO_ID_TEXT AS VARCHAR(MAX)) AS KONTO_ID_TEXT,
		CAST(KONTO_PASSIV AS VARCHAR(MAX)) AS KONTO_PASSIV,
		CAST(KONTO_TEXT AS VARCHAR(MAX)) AS KONTO_TEXT,
		CONVERT(varchar(max), KRES_GILTIG_FOM, 126) AS KRES_GILTIG_FOM,
		CONVERT(varchar(max), KRES_GILTIG_TOM, 126) AS KRES_GILTIG_TOM,
		CAST(KRES_ID AS VARCHAR(MAX)) AS KRES_ID,
		CAST(KRES_ID_TEXT AS VARCHAR(MAX)) AS KRES_ID_TEXT,
		CAST(KRES_PASSIV AS VARCHAR(MAX)) AS KRES_PASSIV,
		CAST(KRES_TEXT AS VARCHAR(MAX)) AS KRES_TEXT,
		CONVERT(varchar(max), KRGRP_GILTIG_FOM, 126) AS KRGRP_GILTIG_FOM,
		CONVERT(varchar(max), KRGRP_GILTIG_TOM, 126) AS KRGRP_GILTIG_TOM,
		CAST(KRGRP_ID AS VARCHAR(MAX)) AS KRGRP_ID,
		CAST(KRGRP_ID_TEXT AS VARCHAR(MAX)) AS KRGRP_ID_TEXT,
		CAST(KRGRP_PASSIV AS VARCHAR(MAX)) AS KRGRP_PASSIV,
		CAST(KRGRP_TEXT AS VARCHAR(MAX)) AS KRGRP_TEXT,
		CONVERT(varchar(max), KTO2_GILTIG_FOM, 126) AS KTO2_GILTIG_FOM,
		CONVERT(varchar(max), KTO2_GILTIG_TOM, 126) AS KTO2_GILTIG_TOM,
		CAST(KTO2_ID AS VARCHAR(MAX)) AS KTO2_ID,
		CAST(KTO2_ID_TEXT AS VARCHAR(MAX)) AS KTO2_ID_TEXT,
		CAST(KTO2_PASSIV AS VARCHAR(MAX)) AS KTO2_PASSIV,
		CAST(KTO2_TEXT AS VARCHAR(MAX)) AS KTO2_TEXT,
		CONVERT(varchar(max), SJKGRP_GILTIG_FOM, 126) AS SJKGRP_GILTIG_FOM,
		CONVERT(varchar(max), SJKGRP_GILTIG_TOM, 126) AS SJKGRP_GILTIG_TOM,
		CAST(SJKGRP_ID AS VARCHAR(MAX)) AS SJKGRP_ID,
		CAST(SJKGRP_ID_TEXT AS VARCHAR(MAX)) AS SJKGRP_ID_TEXT,
		CAST(SJKGRP_PASSIV AS VARCHAR(MAX)) AS SJKGRP_PASSIV,
		CAST(SJKGRP_TEXT AS VARCHAR(MAX)) AS SJKGRP_TEXT,
		CONVERT(varchar(max), SJKRAD_GILTIG_FOM, 126) AS SJKRAD_GILTIG_FOM,
		CONVERT(varchar(max), SJKRAD_GILTIG_TOM, 126) AS SJKRAD_GILTIG_TOM,
		CAST(SJKRAD_ID AS VARCHAR(MAX)) AS SJKRAD_ID,
		CAST(SJKRAD_ID_TEXT AS VARCHAR(MAX)) AS SJKRAD_ID_TEXT,
		CAST(SJKRAD_PASSIV AS VARCHAR(MAX)) AS SJKRAD_PASSIV,
		CAST(SJKRAD_TEXT AS VARCHAR(MAX)) AS SJKRAD_TEXT,
		CONVERT(varchar(max), UKONTO_GILTIG_FOM, 126) AS UKONTO_GILTIG_FOM,
		CONVERT(varchar(max), UKONTO_GILTIG_TOM, 126) AS UKONTO_GILTIG_TOM,
		CAST(UKONTO_ID AS VARCHAR(MAX)) AS UKONTO_ID,
		CAST(UKONTO_ID_TEXT AS VARCHAR(MAX)) AS UKONTO_ID_TEXT,
		CAST(UKONTO_PASSIV AS VARCHAR(MAX)) AS UKONTO_PASSIV,
		CAST(UKONTO_TEXT AS VARCHAR(MAX)) AS UKONTO_TEXT 
	FROM Utdata.udp_100.EK_DIM_OBJ_KONTO ) y

	"""
    return read(query=query, server_url="ksp.rd.sll.se")
    