
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read

        
@model(
    columns={'_data_modified_utc': 'date', '_metadata_modified_utc': 'datetime2', '_source': 'varchar(max)', 'FAKINT_GILTIG_FOM': 'varchar(max)', 'FAKINT_GILTIG_TOM': 'varchar(max)', 'FAKINT_ID': 'varchar(max)', 'FAKINT_ID_TEXT': 'varchar(max)', 'FAKINT_PASSIV': 'varchar(max)', 'FAKINT_TEXT': 'varchar(max)', 'PANM_GILTIG_FOM': 'varchar(max)', 'PANM_GILTIG_TOM': 'varchar(max)', 'PANM_ID': 'varchar(max)', 'PANM_ID_TEXT': 'varchar(max)', 'PANM_PASSIV': 'varchar(max)', 'PANM_TEXT': 'varchar(max)', 'PDIARI_GILTIG_FOM': 'varchar(max)', 'PDIARI_GILTIG_TOM': 'varchar(max)', 'PDIARI_ID': 'varchar(max)', 'PDIARI_ID_TEXT': 'varchar(max)', 'PDIARI_PASSIV': 'varchar(max)', 'PDIARI_TEXT': 'varchar(max)', 'PHSAID_GILTIG_FOM': 'varchar(max)', 'PHSAID_GILTIG_TOM': 'varchar(max)', 'PHSAID_ID': 'varchar(max)', 'PHSAID_ID_TEXT': 'varchar(max)', 'PHSAID_PASSIV': 'varchar(max)', 'PHSAID_TEXT': 'varchar(max)', 'PKLINI_GILTIG_FOM': 'varchar(max)', 'PKLINI_GILTIG_TOM': 'varchar(max)', 'PKLINI_ID': 'varchar(max)', 'PKLINI_ID_TEXT': 'varchar(max)', 'PKLINI_PASSIV': 'varchar(max)', 'PKLINI_TEXT': 'varchar(max)', 'PLED_GILTIG_FOM': 'varchar(max)', 'PLED_GILTIG_TOM': 'varchar(max)', 'PLED_ID': 'varchar(max)', 'PLED_ID_TEXT': 'varchar(max)', 'PLED_PASSIV': 'varchar(max)', 'PLED_TEXT': 'varchar(max)', 'POH_GILTIG_FOM': 'varchar(max)', 'POH_GILTIG_TOM': 'varchar(max)', 'POH_ID': 'varchar(max)', 'POH_ID_TEXT': 'varchar(max)', 'POH_PASSIV': 'varchar(max)', 'POH_TEXT': 'varchar(max)', 'PORGNR_GILTIG_FOM': 'varchar(max)', 'PORGNR_GILTIG_TOM': 'varchar(max)', 'PORGNR_ID': 'varchar(max)', 'PORGNR_ID_TEXT': 'varchar(max)', 'PORGNR_PASSIV': 'varchar(max)', 'PORGNR_TEXT': 'varchar(max)', 'PROHUV_GILTIG_FOM': 'varchar(max)', 'PROHUV_GILTIG_TOM': 'varchar(max)', 'PROHUV_ID': 'varchar(max)', 'PROHUV_ID_TEXT': 'varchar(max)', 'PROHUV_PASSIV': 'varchar(max)', 'PROHUV_TEXT': 'varchar(max)', 'PROJ_GILTIG_FOM': 'varchar(max)', 'PROJ_GILTIG_TOM': 'varchar(max)', 'PROJ_ID': 'varchar(max)', 'PROJ_ID_TEXT': 'varchar(max)', 'PROJ_PASSIV': 'varchar(max)', 'PROJ_TEXT': 'varchar(max)', 'PROSTA_GILTIG_FOM': 'varchar(max)', 'PROSTA_GILTIG_TOM': 'varchar(max)', 'PROSTA_ID': 'varchar(max)', 'PROSTA_ID_TEXT': 'varchar(max)', 'PROSTA_PASSIV': 'varchar(max)', 'PROSTA_TEXT': 'varchar(max)', 'PTYP_GILTIG_FOM': 'varchar(max)', 'PTYP_GILTIG_TOM': 'varchar(max)', 'PTYP_ID': 'varchar(max)', 'PTYP_ID_TEXT': 'varchar(max)', 'PTYP_PASSIV': 'varchar(max)', 'PTYP_TEXT': 'varchar(max)', 'PÅTBET_GILTIG_FOM': 'varchar(max)', 'PÅTBET_GILTIG_TOM': 'varchar(max)', 'PÅTBET_ID': 'varchar(max)', 'PÅTBET_ID_TEXT': 'varchar(max)', 'PÅTBET_PASSIV': 'varchar(max)', 'PÅTBET_TEXT': 'varchar(max)', 'PÅTRAP_GILTIG_FOM': 'varchar(max)', 'PÅTRAP_GILTIG_TOM': 'varchar(max)', 'PÅTRAP_ID': 'varchar(max)', 'PÅTRAP_ID_TEXT': 'varchar(max)', 'PÅTRAP_PASSIV': 'varchar(max)', 'PÅTRAP_TEXT': 'varchar(max)', 'XPLED_GILTIG_FOM': 'varchar(max)', 'XPLED_GILTIG_TOM': 'varchar(max)', 'XPLED_ID': 'varchar(max)', 'XPLED_ID_TEXT': 'varchar(max)', 'XPLED_PASSIV': 'varchar(max)', 'XPLED_TEXT': 'varchar(max)'},
    kind=dict(
        name=ModelKindName.FULL
    ),
    cron="@daily"
)

        
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = f"""
	SELECT * FROM (SELECT 
 		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _data_modified_utc,
		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _metadata_modified_utc,
		'ksp_rd_sll_se_Utdata_udp_100' as _source,
		CONVERT(varchar(max), FAKINT_GILTIG_FOM, 126) AS FAKINT_GILTIG_FOM,
		CONVERT(varchar(max), FAKINT_GILTIG_TOM, 126) AS FAKINT_GILTIG_TOM,
		CAST(FAKINT_ID AS VARCHAR(MAX)) AS FAKINT_ID,
		CAST(FAKINT_ID_TEXT AS VARCHAR(MAX)) AS FAKINT_ID_TEXT,
		CAST(FAKINT_PASSIV AS VARCHAR(MAX)) AS FAKINT_PASSIV,
		CAST(FAKINT_TEXT AS VARCHAR(MAX)) AS FAKINT_TEXT,
		CONVERT(varchar(max), PANM_GILTIG_FOM, 126) AS PANM_GILTIG_FOM,
		CONVERT(varchar(max), PANM_GILTIG_TOM, 126) AS PANM_GILTIG_TOM,
		CAST(PANM_ID AS VARCHAR(MAX)) AS PANM_ID,
		CAST(PANM_ID_TEXT AS VARCHAR(MAX)) AS PANM_ID_TEXT,
		CAST(PANM_PASSIV AS VARCHAR(MAX)) AS PANM_PASSIV,
		CAST(PANM_TEXT AS VARCHAR(MAX)) AS PANM_TEXT,
		CONVERT(varchar(max), PDIARI_GILTIG_FOM, 126) AS PDIARI_GILTIG_FOM,
		CONVERT(varchar(max), PDIARI_GILTIG_TOM, 126) AS PDIARI_GILTIG_TOM,
		CAST(PDIARI_ID AS VARCHAR(MAX)) AS PDIARI_ID,
		CAST(PDIARI_ID_TEXT AS VARCHAR(MAX)) AS PDIARI_ID_TEXT,
		CAST(PDIARI_PASSIV AS VARCHAR(MAX)) AS PDIARI_PASSIV,
		CAST(PDIARI_TEXT AS VARCHAR(MAX)) AS PDIARI_TEXT,
		CONVERT(varchar(max), PHSAID_GILTIG_FOM, 126) AS PHSAID_GILTIG_FOM,
		CONVERT(varchar(max), PHSAID_GILTIG_TOM, 126) AS PHSAID_GILTIG_TOM,
		CAST(PHSAID_ID AS VARCHAR(MAX)) AS PHSAID_ID,
		CAST(PHSAID_ID_TEXT AS VARCHAR(MAX)) AS PHSAID_ID_TEXT,
		CAST(PHSAID_PASSIV AS VARCHAR(MAX)) AS PHSAID_PASSIV,
		CAST(PHSAID_TEXT AS VARCHAR(MAX)) AS PHSAID_TEXT,
		CONVERT(varchar(max), PKLINI_GILTIG_FOM, 126) AS PKLINI_GILTIG_FOM,
		CONVERT(varchar(max), PKLINI_GILTIG_TOM, 126) AS PKLINI_GILTIG_TOM,
		CAST(PKLINI_ID AS VARCHAR(MAX)) AS PKLINI_ID,
		CAST(PKLINI_ID_TEXT AS VARCHAR(MAX)) AS PKLINI_ID_TEXT,
		CAST(PKLINI_PASSIV AS VARCHAR(MAX)) AS PKLINI_PASSIV,
		CAST(PKLINI_TEXT AS VARCHAR(MAX)) AS PKLINI_TEXT,
		CONVERT(varchar(max), PLED_GILTIG_FOM, 126) AS PLED_GILTIG_FOM,
		CONVERT(varchar(max), PLED_GILTIG_TOM, 126) AS PLED_GILTIG_TOM,
		CAST(PLED_ID AS VARCHAR(MAX)) AS PLED_ID,
		CAST(PLED_ID_TEXT AS VARCHAR(MAX)) AS PLED_ID_TEXT,
		CAST(PLED_PASSIV AS VARCHAR(MAX)) AS PLED_PASSIV,
		CAST(PLED_TEXT AS VARCHAR(MAX)) AS PLED_TEXT,
		CONVERT(varchar(max), POH_GILTIG_FOM, 126) AS POH_GILTIG_FOM,
		CONVERT(varchar(max), POH_GILTIG_TOM, 126) AS POH_GILTIG_TOM,
		CAST(POH_ID AS VARCHAR(MAX)) AS POH_ID,
		CAST(POH_ID_TEXT AS VARCHAR(MAX)) AS POH_ID_TEXT,
		CAST(POH_PASSIV AS VARCHAR(MAX)) AS POH_PASSIV,
		CAST(POH_TEXT AS VARCHAR(MAX)) AS POH_TEXT,
		CONVERT(varchar(max), PORGNR_GILTIG_FOM, 126) AS PORGNR_GILTIG_FOM,
		CONVERT(varchar(max), PORGNR_GILTIG_TOM, 126) AS PORGNR_GILTIG_TOM,
		CAST(PORGNR_ID AS VARCHAR(MAX)) AS PORGNR_ID,
		CAST(PORGNR_ID_TEXT AS VARCHAR(MAX)) AS PORGNR_ID_TEXT,
		CAST(PORGNR_PASSIV AS VARCHAR(MAX)) AS PORGNR_PASSIV,
		CAST(PORGNR_TEXT AS VARCHAR(MAX)) AS PORGNR_TEXT,
		CONVERT(varchar(max), PROHUV_GILTIG_FOM, 126) AS PROHUV_GILTIG_FOM,
		CONVERT(varchar(max), PROHUV_GILTIG_TOM, 126) AS PROHUV_GILTIG_TOM,
		CAST(PROHUV_ID AS VARCHAR(MAX)) AS PROHUV_ID,
		CAST(PROHUV_ID_TEXT AS VARCHAR(MAX)) AS PROHUV_ID_TEXT,
		CAST(PROHUV_PASSIV AS VARCHAR(MAX)) AS PROHUV_PASSIV,
		CAST(PROHUV_TEXT AS VARCHAR(MAX)) AS PROHUV_TEXT,
		CONVERT(varchar(max), PROJ_GILTIG_FOM, 126) AS PROJ_GILTIG_FOM,
		CONVERT(varchar(max), PROJ_GILTIG_TOM, 126) AS PROJ_GILTIG_TOM,
		CAST(PROJ_ID AS VARCHAR(MAX)) AS PROJ_ID,
		CAST(PROJ_ID_TEXT AS VARCHAR(MAX)) AS PROJ_ID_TEXT,
		CAST(PROJ_PASSIV AS VARCHAR(MAX)) AS PROJ_PASSIV,
		CAST(PROJ_TEXT AS VARCHAR(MAX)) AS PROJ_TEXT,
		CONVERT(varchar(max), PROSTA_GILTIG_FOM, 126) AS PROSTA_GILTIG_FOM,
		CONVERT(varchar(max), PROSTA_GILTIG_TOM, 126) AS PROSTA_GILTIG_TOM,
		CAST(PROSTA_ID AS VARCHAR(MAX)) AS PROSTA_ID,
		CAST(PROSTA_ID_TEXT AS VARCHAR(MAX)) AS PROSTA_ID_TEXT,
		CAST(PROSTA_PASSIV AS VARCHAR(MAX)) AS PROSTA_PASSIV,
		CAST(PROSTA_TEXT AS VARCHAR(MAX)) AS PROSTA_TEXT,
		CONVERT(varchar(max), PTYP_GILTIG_FOM, 126) AS PTYP_GILTIG_FOM,
		CONVERT(varchar(max), PTYP_GILTIG_TOM, 126) AS PTYP_GILTIG_TOM,
		CAST(PTYP_ID AS VARCHAR(MAX)) AS PTYP_ID,
		CAST(PTYP_ID_TEXT AS VARCHAR(MAX)) AS PTYP_ID_TEXT,
		CAST(PTYP_PASSIV AS VARCHAR(MAX)) AS PTYP_PASSIV,
		CAST(PTYP_TEXT AS VARCHAR(MAX)) AS PTYP_TEXT,
		CONVERT(varchar(max), PÅTBET_GILTIG_FOM, 126) AS PÅTBET_GILTIG_FOM,
		CONVERT(varchar(max), PÅTBET_GILTIG_TOM, 126) AS PÅTBET_GILTIG_TOM,
		CAST(PÅTBET_ID AS VARCHAR(MAX)) AS PÅTBET_ID,
		CAST(PÅTBET_ID_TEXT AS VARCHAR(MAX)) AS PÅTBET_ID_TEXT,
		CAST(PÅTBET_PASSIV AS VARCHAR(MAX)) AS PÅTBET_PASSIV,
		CAST(PÅTBET_TEXT AS VARCHAR(MAX)) AS PÅTBET_TEXT,
		CONVERT(varchar(max), PÅTRAP_GILTIG_FOM, 126) AS PÅTRAP_GILTIG_FOM,
		CONVERT(varchar(max), PÅTRAP_GILTIG_TOM, 126) AS PÅTRAP_GILTIG_TOM,
		CAST(PÅTRAP_ID AS VARCHAR(MAX)) AS PÅTRAP_ID,
		CAST(PÅTRAP_ID_TEXT AS VARCHAR(MAX)) AS PÅTRAP_ID_TEXT,
		CAST(PÅTRAP_PASSIV AS VARCHAR(MAX)) AS PÅTRAP_PASSIV,
		CAST(PÅTRAP_TEXT AS VARCHAR(MAX)) AS PÅTRAP_TEXT,
		CONVERT(varchar(max), XPLED_GILTIG_FOM, 126) AS XPLED_GILTIG_FOM,
		CONVERT(varchar(max), XPLED_GILTIG_TOM, 126) AS XPLED_GILTIG_TOM,
		CAST(XPLED_ID AS VARCHAR(MAX)) AS XPLED_ID,
		CAST(XPLED_ID_TEXT AS VARCHAR(MAX)) AS XPLED_ID_TEXT,
		CAST(XPLED_PASSIV AS VARCHAR(MAX)) AS XPLED_PASSIV,
		CAST(XPLED_TEXT AS VARCHAR(MAX)) AS XPLED_TEXT 
	FROM Utdata.udp_100.EK_DIM_OBJ_PROJ ) y

	"""
    return read(query=query, server_url="ksp.rd.sll.se")
    