gateways:
  mssql_lakehouse:
    connection:
      type: mssql
      host: localhost
      user: sa
      password: Password1!
      port: 31433
      database: lakehouse

default_gateway: mssql_lakehouse

model_defaults:
  dialect: tsql
  start: 2024-01-01

model_naming:
  infer_names: true
