MODEL (
  column_descriptions (
    accnsh_accumulate_sales_history_log = 'Accumulate sales history log',
    accumulate_production_history_log = 'Accumulate production history log',
    accumulate_purchase_history_log = 'Accumulate purchase history log',
    acsalh_accumulate_sales_history_log = 'Accumulate sales history log',
    sales_cost_addition = 'Sales cost addition',
    administration_cost_addition = 'Administration cost addition',
    agent_identification_code = 'Agent Identification Code',
    assorted_order_discount_group_identification = 'Assorted Order Discount Group Identification',
    procurement_product_selection_slash_range_restriction = 'Procurement Product Selection/Range Restriction',
    asset_type_identification_code = 'Asset Type Identification Code',
    acquisition_control = 'Acquisition control',
    base_unit_identification_code = 'Base unit identification code',
    billed_retal_of_product = 'Billed Retal of Product',
    breakdown_type = 'Breakdown type',
    budget_unit_identification_code = 'Budget unit identification code',
    information_last_changed_date = 'Information last changed date',
    information_last_changed_by_user = 'Information last changed by user',
    clclot = 'No description found in source docs.',
    consignment_stock = 'Consignment Stock',
    include_replacement_reference_for_consigned_item = 'Include Replacement Reference for Consigned Item',
    consuming_unit_identifcation_code = 'Consuming unit identifcation code',
    country_of_origin = 'Country of origin',
    company_identification_code = 'Company identification code',
    cost_price_model_how_to_find_correct_cost = 'Cost price model: how to find correct cost',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information created by user',
    critical_in_delivery_calculation = 'Critical in Delivery Calculation',
    cost_center_identification_code = 'Cost Center Identification Code',
    customs_tariff_number_identification_code = 'Customs Tariff Number Identification Code',
    generate_component_transfer_requests = 'Generate Component Transfer Requests',
    component_transfer_levels = 'Component Transfer Levels',
    detail_unit_identification_code = 'Detail Unit Identification Code',
    datasheet_identification_code = 'Datasheet identification code',
    ear_hyphen_code_identification_code = 'EAR-Code Identification Code',
    environment_class_or_classification = 'Environment Class or Classification',
    exclude_item_on_external_documents = 'Exclude Item on External Documents',
    exclude_item_on_invoice_dcuments = 'Exclude Item on Invoice Dcuments',
    exclude_item_on_transport_documents = 'Exclude Item on Transport Documents',
    external_item_type = 'External item type',
    forecast_profile_identification_code = 'Forecast Profile Identification Code',
    factory_identification_code = 'Factory identification code',
    fixed_lead_hyphen_time_independent_of_lotsize = 'Fixed Lead-Time: Independent of LotSize',
    generate_gs1_item_barcode = 'Generate GS1 Item Barcode',
    hide_from_search = 'Hide from Search',
    item_category_identification_code = 'Item category identification code',
    individ_group_identification_code = 'Individ group identification code',
    _information_model = ' Information Model',
    active__slash__passive_status_code = 'Active / Passive status code',
    life_cycle_status_code = 'Life cycle status code',
    item_type_identification_code = 'Item type identification code',
    logistic_group_identification_code = 'Logistic group identification code',
    defualt_theoretical_production_hyphen_lot_or__hyphen_batch_size = 'Defualt Theoretical Production-Lot or -Batch Size',
    loss__slash__wreck_type = 'Loss / wreck type',
    override_rule_for_exceeded_maximum_consuming_quantity = 'Override rule for exceeded maximum consuming quantity',
    maximum_consuming_quantity = 'Maximum consuming quantity',
    override_rule_for_exceeded_maximum_purchase_quantity = 'Override rule for exceeded maximum purchase quantity',
    maximum_purchase_quantity = 'Maximum purchase quantity',
    override_rule_for_exceeded_maximum_sales_quantity = 'Override rule for exceeded maximum sales quantity',
    maximum_sales_quantity = 'Maximum sales quantity',
    material_usage_in_bill_of_material = 'Material Usage in Bill of Material',
    multi_element_discount_group = 'Multi Element Discount Group',
    minimum_consuming_quantity = 'Minimum consuming quantity',
    main_item_group_identification_code = 'Main item group identification code',
    main_item_group_name__slash__description = 'Main item group name / description',
    minimum_purchase_quantity = 'Minimum purchase quantity',
    minimum_sales_quantity = 'Minimum sales quantity',
    master_in_bulletin_board_system = 'Master in Bulletin Board System',
    generate_requisition_one_hyphen_to_hyphen_one = 'Generate Requisition One-to-One',
    product_calculation_group_identification_codeq = 'Product Calculation Group Identification Codeq',
    how_to_control_the_initiation_of_a_production = 'How to control the initiation of a production',
    product_family_identification_code = 'Product Family Identification Code',
    product_group_identification_code = 'Product group identification code',
    product_information_model_identification_code = 'Product information model identification code',
    planning_group_identification_code = 'Planning group identification code',
    product_model_identification_code = 'Product Model Identification Code',
    product_manager_identification_code = 'Product manager identification code',
    production_planner_identification_code = 'Production planner identification code',
    previous_production_order_link_control = 'Previous Production Order Link Control',
    purchase_budget_account_number = 'Purchase budget account number',
    purchaser_identification_code = 'Purchaser identification code',
    procurement_control = 'Procurement Control',
    purchase_unit_identification_code = 'Purchase unit identification code',
    item_entry_profile_code = 'Item Entry Profile Code',
    product_range_identification_code = 'Product Range Identification Code',
    quality_assurance_control_model_identification = 'Quality assurance control model identification',
    quality_manager = 'Quality Manager',
    formula_for_reporting_quantities_on_odd_measures = 'Formula for Reporting Quantities on odd measures',
    recyclable_share__slash__part = 'Recyclable Share / Part',
    reinitiate_value_when_changed_on_item = 'Reinitiate Value when Changed on Item',
    required_contribution_margin = 'Required contribution margin',
    required_contribution_rate = 'required contribution rate',
    relation_ratio_from_budget_unit_to_base_unit = 'Relation Ratio from Budget Unit to Base Unit',
    relation_ratio_from_consuming_unit_to_base_unit = 'Relation Ratio from Consuming Unit to Base Unit',
    relation_ratio_from_detail_unit_to_base_unit = 'Relation Ratio from Detail Unit to Base Unit',
    relation_ratio_from_purchase_unit_to_base_unit = 'Relation Ratio from Purchase Unit to Base Unit',
    relation_ratio_from_sales_unit_to_base_unit = 'Relation Ratio from Sales Unit to Base Unit',
    relation_type_from_budget_unit_to_base_unit = 'Relation Type from Budget Unit to Base Unit',
    relation_type_from_consuming_unit_to_base_unit = 'Relation Type from Consuming Unit to Base Unit',
    relation_type_from_detail_unit_to_base_unit = 'Relation Type from Detail Unit to Base Unit',
    relation_type_from_purchase_unit_to_base_unit = 'Relation Type from Purchase Unit to Base Unit',
    relation_type_from_sales_unit_to_base_unit = 'Relation Type from Sales Unit to Base Unit',
    sales_addition = 'Sales addition',
    sales_resupply = 'Sales resupply',
    sales_unit_identification_code = 'Sales unit identification code',
    seller__slash__salesperson_identification_code = 'Seller / Salesperson identification code',
    scpunt = 'No description found in source docs.',
    special_treatment = 'Special treatment',
    sales_prce_model_for_standard_slash_recommended_price = 'Sales Prce Model for Standard/Recommended Price',
    indicates_how_to_control_sale_of_sp_hyphen_products = 'Indicates how to control sale of SP-products',
    shortname = 'Shortname',
    shortnumber = 'Shortnumber',
    stock_resupply = 'Stock resupply',
    stock_holding_control = 'Stock holding control',
    standard_production_deviation_handling = 'Standard Production Deviation Handling',
    standard_production_deviation_type = 'Standard Production Deviation Type',
    standard_report_deviation = 'Standard Report Deviation',
    standard_report_quantity = 'Standard Report Quantity',
    sub_level_is_required = 'Sub Level is Required',
    supplier_identification_code = 'Supplier identification code',
    tax_base_in_relation_to_tax_value = 'Tax Base in Relation to Tax Value',
    tax_value_code = 'Tax value (code)',
    tax_group_identification_code = 'Tax Group Identification Code',
    additional_text__slash__description = 'Additional Text / Description',
    update__slash__synchronize_country_of_origin = 'Update / Synchronize Country of Origin',
    update_cost_price_from_suppliers_item_catalogue = 'Update Cost Price from Suppliers Item Catalogue',
    update_standard_purchase_price_from_suppliers_item_catalogue = 'Update Standard Purchase Price from Suppliers Item Catalogue',
    activate_use_of_barcode_mode = 'Activate Use of Barcode Mode',
    variant_group_identification_code = 'Variant group identification code',
    value_added_taxcode_for_consume = 'Value added taxcode for consume',
    value_added_taxcode_for_production = 'Value added taxcode for production',
    value_added_taxcode_for_purchase = 'Value added taxcode for purchase',
    value_added_taxccode_for_sales = 'Value added taxccode for sales',
    warehouse_identification_code = 'Warehouse identification code',
    work_order_resupply_control = 'Work Order Resupply Control'
  )
);

SELECT
  acpdch AS Accumulate_production_history_log,
  acprch AS Accumulate_purchase_history_log,
  ausctr AS Acquisition_control,
  usebcm AS Activate_Use_of_Barcode_Mode,
  itmact AS Active__slash__Passive_status_code,
  txtdsc AS Additional_Text__slash__Description,
  admadd AS Administration_cost_addition,
  agncod AS Agent_Identification_Code,
  astcod AS Asset_Type_Identification_Code,
  aodgid AS Assorted_Order_Discount_Group_Identification,
  basunt AS Base_unit_identification_code,
  bilrtl AS Billed_Retal_of_Product,
  brkdwn AS Breakdown_type,
  budunt AS Budget_unit_identification_code,
  compny AS Company_identification_code,
  ctrlvl AS Component_Transfer_Levels,
  cnsgnd AS Consignment_Stock,
  cnsunt AS Consuming_unit_identifcation_code,
  csccod AS Cost_Center_Identification_Code,
  cprmod AS Cost_price_model_how_to_find_correct_cost,
  cntori AS Country_of_origin,
  criitm AS Critical_in_Delivery_Calculation,
  cstcod AS Customs_Tariff_Number_Identification_Code,
  dtscod AS Datasheet_identification_code,
  lotsiz AS Defualt_Theoretical_Production_hyphen_Lot_or__hyphen_Batch_Size,
  dtlunt AS Detail_Unit_Identification_Code,
  earcod AS EAR_hyphen_Code_Identification_Code,
  envcls AS Environment_Class_or_Classification,
  excexd AS Exclude_Item_on_External_Documents,
  excivd AS Exclude_Item_on_Invoice_Dcuments,
  exctrd AS Exclude_Item_on_Transport_Documents,
  exttyp AS External_item_type,
  fctcod AS Factory_identification_code,
  fixtim AS Fixed_Lead_hyphen_Time_Independent_of_LotSize,
  fcpcod AS Forecast_Profile_Identification_Code,
  qtyfml AS Formula_for_Reporting_Quantities_on_odd_measures,
  ctrgen AS Generate_Component_Transfer_Requests,
  gs1ibc AS Generate_GS1_Item_Barcode,
  otomrq AS Generate_Requisition_One_hyphen_to_hyphen_One,
  hidsrc AS Hide_from_Search,
  pdcctr AS How_to_control_the_initiation_of_a_production,
  cnsref AS Include_Replacement_Reference_for_Consigned_Item,
  spsale AS Indicates_how_to_control_sale_of_SP_hyphen_products,
  idgcod AS Individ_group_identification_code,
  credat AS Information_Created_Date,
  creusr AS Information_created_by_user,
  chgusr AS Information_last_changed_by_user,
  chgdat AS Information_last_changed_date,
  prfcod AS Item_Entry_Profile_Code,
  ictcod AS Item_category_identification_code,
  itycod AS Item_type_identification_code,
  itmlcs AS Life_cycle_status_code,
  logcod AS Logistic_group_identification_code,
  lwvtyp AS Loss__slash__wreck_type,
  migcod AS Main_item_group_identification_code,
  mignam AS Main_item_group_name__slash__description,
  mstbbs AS Master_in_Bulletin_Board_System,
  matuse AS Material_Usage_in_Bill_of_Material,
  macqty AS Maximum_consuming_quantity,
  mapqty AS Maximum_purchase_quantity,
  masqty AS Maximum_sales_quantity,
  micqty AS Minimum_consuming_quantity,
  mipqty AS Minimum_purchase_quantity,
  misqty AS Minimum_sales_quantity,
  medgrp AS Multi_Element_Discount_Group,
  macofh AS Override_rule_for_exceeded_maximum_consuming_quantity,
  mapofh AS Override_rule_for_exceeded_maximum_purchase_quantity,
  masofh AS Override_rule_for_exceeded_maximum_sales_quantity,
  plgcod AS Planning_group_identification_code,
  pprctr AS Previous_Production_Order_Link_Control,
  prcctr AS Procurement_Control,
  aprctr AS Procurement_Product_Selection_slash_Range_Restriction,
  pcgcod AS Product_Calculation_Group_Identification_Codeq,
  pfmcod AS Product_Family_Identification_Code,
  pmdcod AS Product_Model_Identification_Code,
  prncod AS Product_Range_Identification_Code,
  pgrcod AS Product_group_identification_code,
  pinmod AS Product_information_model_identification_code,
  pmgcod AS Product_manager_identification_code,
  pplcod AS Production_planner_identification_code,
  prbuac AS Purchase_budget_account_number,
  prcunt AS Purchase_unit_identification_code,
  prccod AS Purchaser_identification_code,
  qlmcod AS Quality_Manager,
  qamcod AS Quality_assurance_control_model_identification,
  recycl AS Recyclable_Share__slash__Part,
  reinit AS Reinitiate_Value_when_Changed_on_Item,
  rrbbud AS Relation_Ratio_from_Budget_Unit_to_Base_Unit,
  rrbcns AS Relation_Ratio_from_Consuming_Unit_to_Base_Unit,
  rrbdtl AS Relation_Ratio_from_Detail_Unit_to_Base_Unit,
  rrbprc AS Relation_Ratio_from_Purchase_Unit_to_Base_Unit,
  rrbsal AS Relation_Ratio_from_Sales_Unit_to_Base_Unit,
  rtbbud AS Relation_Type_from_Budget_Unit_to_Base_Unit,
  rtbcns AS Relation_Type_from_Consuming_Unit_to_Base_Unit,
  rtbdtl AS Relation_Type_from_Detail_Unit_to_Base_Unit,
  rtbprd AS Relation_Type_from_Purchase_Unit_to_Base_Unit,
  rtbsal AS Relation_Type_from_Sales_Unit_to_Base_Unit,
  reqcbm AS Required_contribution_margin,
  sprmod AS Sales_Prce_Model_for_Standard_slash_Recommended_Price,
  saladd AS Sales_addition,
  admad AS Sales_cost_addition,
  salrsp AS Sales_resupply,
  salunt AS Sales_unit_identification_code,
  sapcod AS Seller__slash__Salesperson_identification_code,
  srtnam AS Shortname,
  srtnum AS Shortnumber,
  spctrt AS Special_treatment,
  strpdh AS Standard_Production_Deviation_Handling,
  strpdt AS Standard_Production_Deviation_Type,
  strpdv AS Standard_Report_Deviation,
  strpqt AS Standard_Report_Quantity,
  sthctr AS Stock_holding_control,
  stcrsp AS Stock_resupply,
  sublvl AS Sub_Level_is_Required,
  supcod AS Supplier_identification_code,
  taxbas AS Tax_Base_in_Relation_to_Tax_Value,
  txgcod AS Tax_Group_Identification_Code,
  taxcod AS Tax_value_code,
  updscp AS Update_Cost_Price_from_Suppliers_Item_Catalogue,
  updspp AS Update_Standard_Purchase_Price_from_Suppliers_Item_Catalogue,
  updori AS Update__slash__Synchronize_Country_of_Origin,
  vatsal AS Value_added_taxccode_for_sales,
  vatcns AS Value_added_taxcode_for_consume,
  vatpdc AS Value_added_taxcode_for_production,
  vatprc AS Value_added_taxcode_for_purchase,
  vargrp AS Variant_group_identification_code,
  whscod AS Warehouse_identification_code,
  worrsp AS Work_Order_Resupply_Control,
  infmod AS _Information_Model,
  accnsh AS accnsh_Accumulate_sales_history_log,
  acsalh AS acsalh_Accumulate_sales_history_log,
  reqcbr AS required_contribution_rate
FROM clockwork.rainbow_mig