MODEL (
  column_descriptions (
    agreement_or_contract_number = 'Agreement or Contract Number',
    approved_date = 'Approved Date',
    approval_status_code = 'Approval Status Code',
    approved_by_user = 'Approved by User',
    reference_to_record_in_balance_update_logdot = 'Reference to record in balance update log.',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    completed_date = 'Completed Date',
    completion_status_code = 'Completion Status Code',
    completed_by_user = 'Completed by User',
    currency_convertion_factor_1_slash_100 = 'Currency Convertion Factor (1/100)',
    company_identification_code = 'Company Identification Code',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information Created by User',
    cart_identification_code = 'Cart Identification code',
    currency_identification_code = 'Currency Identification Code',
    reference_to_transaction_record_in_dynamic_financial_informatio = 'Reference to transaction record in dynamic financial information.',
    delegated_date = 'Delegated Date',
    delegate_to_identity_code = 'Delegate to Identity Code',
    delegate_to_identity_type = 'Delegate to Identity Type',
    delegation_status_code = 'Delegation Status Code',
    date_for_last_delivery = 'Date for Last Delivery',
    delivered_slash_received_by_user = 'Delivered/Received by User',
    despatcher_code_according_to_type = 'Despatcher Code according to Type',
    despatch_date = 'Despatch Date',
    despatcher_name = 'Despatcher Name',
    despatcher_type = 'Despatcher Type',
    distribution_period_code_for_accrual = 'Distribution Period Code for Accrual',
    type__slash__method_of_entry = 'Type / Method of Entry',
    exchange_rate = 'Exchange Rate',
    external_item_identification_code = 'External Item Identification Code',
    external_item_name__slash__description = 'External Item Name / Description',
    external_catalogue_sequence_number = 'External Catalogue Sequence Number',
    contract_sequence_number = 'Contract Sequence Number',
    forwarded_invoice_at_date = 'Forwarded Invoice at Date',
    forward_invoice_to_status = 'Forward Invoice to Status',
    invoice_forwarded_by_user = 'Invoice Forwarded by User',
    hide_price_on_dokuments = 'Hide Price on Dokuments',
    handling_sequence = 'Handling Sequence',
    item_classification_catalogue = 'Item Classification Catalogue',
    item_classification_reference_code_in_catalogue = 'Item Classification Reference Code in Catalogue',
    individ_identification_number = 'Individ Identification Number',
    information_status = 'Information Status',
    line_item_code_according_to_type = 'Line Item Code According to Type',
    line_item_name__slash__description = 'Line Item Name / Description',
    line_item_type = 'Line Item Type',
    visualized_mapped_location = 'Visualized Mapped Location',
    requisition_alternatives_exists_in_table_mrqalt = 'Requisition Alternatives exists in table MRQALT',
    requisition_number = 'Requisition Number',
    reference_to_master_record_in_mrqmst = 'Reference to Master record in MRQMST',
    order_form_identification_code = 'Order Form Identification Code',
    order_break_value_1 = 'Order Break: value 1',
    latest_ordering_date = 'Latest ordering date',
    re_hyphen_evaluate_open_request_at_date = 'Re-Evaluate Open Request at Date',
    default_sales_order_type = 'Default Sales Order Type',
    price__slash__cost_per_unit = 'Price / Cost per unit',
    requisition_assortment_classification_system_code = 'Requisition Assortment Classification System Code',
    requisition_classification_reference_in_catalogue = 'Requisition Classification Reference in Catalogue',
    ration_control_status = 'Ration Control Status',
    receiver_code_according_to_type = 'Receiver Code According to Type',
    receiving_date = 'Receiving Date',
    receiver_name = 'Receiver Name',
    receiver_type = 'Receiver Type',
    requisition_entered_by_user = 'Requisition Entered by User',
    requisition_entered_at_date = 'Requisition Entered at Date',
    requested_quantity = 'Requested Quantity',
    relation_ratio_from_transaction_unit_to_base_unit = 'Relation Ratio from Transaction Unit to Base Unit',
    relation_type_from_transaction_unit_to_base_unit = 'Relation Type from Transaction Unit to Base Unit',
    requisition_status_code = 'Requisition Status Code',
    unit_identification_code = 'Unit Identification Code',
    request_for_information_status = 'Request for Information Status',
    consigned_replacement_reference = 'Consigned Replacement Reference',
    resupply_type = 'Resupply Type',
    return_date_for_loan = 'Return Date for Loan',
    requisition_line_sequence_number = 'Requisition Line Sequence Number',
    splitted_or_changed_line_from_original_master = 'Splitted or Changed Line From Original Master',
    source_type_for_barcode_order = 'Source Type for Barcode Order',
    delivery_address_reference_sequence_number = 'Delivery Address Reference Sequence Number',
    request_for_quotation_number = 'Request for Quotation Number',
    request_for_quotation_sequence_number = 'Request for Quotation Sequence Number',
    external_text__slash__comment = 'External Text / Comment',
    internal_comment__slash__text = 'Internal Comment / Text',
    total_line_value_in_foreign_currency = 'Total Line Value in Foreign Currency',
    total_line_value_in_local_currency = 'Total Line Value in Local Currency',
    value_added_tax_code = 'Value Added Tax Code',
    verification_status = 'Verification Status',
    variant_string = 'Variant String',
    not_in_use = 'Not in Use'
  )
);

SELECT
  agrnum AS Agreement_or_Contract_Number,
  appsts AS Approval_Status_Code,
  appdat AS Approved_Date,
  appusr AS Approved_by_User,
  crtcod AS Cart_Identification_code,
  compny AS Company_Identification_Code,
  cmpdat AS Completed_Date,
  cmpusr AS Completed_by_User,
  cmpsts AS Completion_Status_Code,
  rplref AS Consigned_Replacement_Reference,
  faiseq AS Contract_Sequence_Number,
  cnvexc AS Currency_Convertion_Factor_1_slash_100,
  curcod AS Currency_Identification_Code,
  dlvdat AS Date_for_Last_Delivery,
  otscod AS Default_Sales_Order_Type,
  dlgidc AS Delegate_to_Identity_Code,
  dlgidt AS Delegate_to_Identity_Type,
  dlgdat AS Delegated_Date,
  dlgsts AS Delegation_Status_Code,
  dlvusr AS Delivered_slash_Received_by_User,
  tadref AS Delivery_Address_Reference_Sequence_Number,
  dspdat AS Despatch_Date,
  dspcod AS Despatcher_Code_according_to_Type,
  dspnam AS Despatcher_Name,
  dsptyp AS Despatcher_Type,
  dstper AS Distribution_Period_Code_for_Accrual,
  excrat AS Exchange_Rate,
  extseq AS External_Catalogue_Sequence_Number,
  extitm AS External_Item_Identification_Code,
  extnam AS External_Item_Name__slash__Description,
  txtext AS External_Text__slash__Comment,
  fivsts AS Forward_Invoice_to_Status,
  fivdat AS Forwarded_Invoice_at_Date,
  hndseq AS Handling_Sequence,
  hidprc AS Hide_Price_on_Dokuments,
  idncod AS Individ_Identification_Number,
  credat AS Information_Created_Date,
  creusr AS Information_Created_by_User,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  infsts AS Information_Status,
  txtint AS Internal_Comment__slash__Text,
  fivusr AS Invoice_Forwarded_by_User,
  icscat AS Item_Classification_Catalogue,
  icsref AS Item_Classification_Reference_Code_in_Catalogue,
  orddat AS Latest_ordering_date,
  lincod AS Line_Item_Code_According_to_Type,
  linnam AS Line_Item_Name__slash__Description,
  lintyp AS Line_Item_Type,
  wwfseq AS Not_in_Use,
  ordbk1 AS Order_Break_value_1,
  ofmcod AS Order_Form_Identification_Code,
  prccst AS Price__slash__Cost_per_unit,
  ratsts AS Ration_Control_Status,
  oreval AS Re_hyphen_Evaluate_Open_Request_at_Date,
  rcvcod AS Receiver_Code_According_to_Type,
  rcvnam AS Receiver_Name,
  rcvtyp AS Receiver_Type,
  rcvdat AS Receiving_Date,
  mstseq AS Reference_to_Master_record_in_MRQMST,
  balseq AS Reference_to_record_in_balance_update_logdot,
  dfiseq AS Reference_to_transaction_record_in_dynamic_financial_informatio,
  reqrra AS Relation_Ratio_from_Transaction_Unit_to_Base_Unit,
  reqrty AS Relation_Type_from_Transaction_Unit_to_Base_Unit,
  rfqsts AS Request_for_Information_Status,
  tndnum AS Request_for_Quotation_Number,
  tndseq AS Request_for_Quotation_Sequence_Number,
  reqqty AS Requested_Quantity,
  mrqalt AS Requisition_Alternatives_exists_in_table_MRQALT,
  rascat AS Requisition_Assortment_Classification_System_Code,
  rasref AS Requisition_Classification_Reference_in_Catalogue,
  reqdat AS Requisition_Entered_at_Date,
  recusr AS Requisition_Entered_by_User,
  seqnum AS Requisition_Line_Sequence_Number,
  mrqnum AS Requisition_Number,
  reqsts AS Requisition_Status_Code,
  rsptyp AS Resupply_Type,
  rtndat AS Return_Date_for_Loan,
  srctyp AS Source_Type_for_Barcode_Order,
  splmst AS Splitted_or_Changed_Line_From_Original_Master,
  valcur AS Total_Line_Value_in_Foreign_Currency,
  valloc AS Total_Line_Value_in_Local_Currency,
  enttyp AS Type__slash__Method_of_Entry,
  requnt AS Unit_Identification_Code,
  vatcod AS Value_Added_Tax_Code,
  vrscod AS Variant_String,
  vrfsts AS Verification_Status,
  maploc AS Visualized_Mapped_Location
FROM clockwork.rainbow_mrqlin