MODEL (
  column_descriptions (
    account_table_identification_code = 'Account table identification code',
    indicates_if_address_control_is_to_be_executed_or_not = 'Indicates if address control is to be executed or not',
    defines_if_and_how_handling_hyphen_cost_is_to_be_applied = 'Defines if and how handling-cost is to be applied',
    business_approval_classification = 'Business approval classification',
    approved_for_business_from_date = 'Approved for Business from Date',
    approved_for_business_until_date = 'Approved for Business until Date',
    defines_if_and_how_warehouse_hyphen_cost_is_to_be_applied = 'Defines if and how warehouse-cost is to be applied',
    automatic_link_to_internal_distribution_from_arrival = 'Automatic link to internal distribution from arrival',
    automatic_allocation_of_stock = 'Automatic Allocation of Stock',
    automatic_confirm_picking_list = 'Automatic Confirm Picking List',
    additional_warehouse_name = 'Additional Warehouse Name',
    bank_account_number = 'Bank account number',
    barcode_label_type = 'Barcode Label Type',
    temporay_delivery_stop_caused_by = 'Temporay delivery stop caused by',
    default_cost_deviation_control_percentage = 'Default Cost Deviation Control Percentage',
    information_last_changed_date = 'Information last changed date',
    information_last_changed_by_user = 'Information last changed by user',
    corporate_client_identification_code = 'Corporate Client Identification Code',
    consignment_reference_registration = 'Consignment Reference Registration',
    country_identification_code = 'Country identification code',
    company_identification_code = 'Company Identification Code',
    cpccby = 'No description found in source docs.',
    credit_balance_setup_code = 'Credit balance setup code',
    credit_balance_method = 'Credit Balance Method',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information created by user',
    coroprate_warehouse_open_for_transactions = 'Coroprate Warehouse open for Transactions',
    cost_center_identification_code = 'Cost center identification code',
    current_service_level_for_delivery_last_changed_by_user = 'Current service level for delivery last changed by user',
    current_service_level_value_delivery = 'Current service level value: delivery',
    current_stock_turnover_value_last_changed_by_user = 'Current stock turnover value last changed by user',
    current_stock_turnover_value = 'Current stock turnover value',
    warehouse_contact_person = 'Warehouse contact person',
    currency_identification_code = 'Currency identification code',
    currency_type = 'Currency type',
    display_production_proposals_in_day_by_day = 'Display Production Proposals in Day by Day',
    display_purchase_proposals_in_day_by_day = 'Display Purchase Proposals in Day by Day',
    document_set_identification_code = 'Document Set Identification Code',
    account_set_is_used_for_both_sides_in_a_stock_transfer = 'Account set is used for both sides in a stock transfer',
    default_sales_price_method = 'Default sales price method',
    delivery_address_line_1 = 'Delivery Address: Line 1',
    delivery_address_line_2 = 'Delivery Address: Line 2',
    delivery_address_line_3 = 'Delivery Address: Line 3',
    delivery_address_line_4 = 'Delivery Address: Line 4',
    delivery_group_identification_code = 'Delivery group identification code',
    defines_which_warehouse_accumulated_demand_is_to_be_re_hyphen_r = 'Defines which warehouse accumulated demand is to be re-routed to.',
    department_identification_code = 'Department Identification Code',
    district_identification_code = 'District Identification Code',
    european_community_country_code = 'European Community Country Code',
    end_date_for_closed_for_service_interval = 'End Date for Closed for Service Interval',
    eori__hyphen__economic_operators_registration_and_identificatio = 'EORI - Economic Operators Registration and Identification Number',
    enable_mail_address_entry = 'Enable Mail Address Entry',
    enable_visiting_address_entry = 'Enable Visiting Address Entry',
    entity_identification_code = 'Entity Identification Code',
    leadtime_for_ex_hyphen_works_termsdot_part_of_standard_leadtime = 'Leadtime for Ex-Works Terms. Part of Standard Leadtime',
    telefax_number_to_warehouse_switchboard = 'Telefax number to warehouse switchboard',
    prefix_in_serial_number_for_sales_invoice = 'Prefix in Serial Number for Sales Invoice',
    prefix_in_serial_number_for_arrival = 'Prefix in Serial Number for Arrival',
    prefix_in_serial_number_for_sales_credit_invoice = 'Prefix in Serial Number for Sales Credit Invoice',
    fixed_discount_percentage = 'Fixed discount percentage',
    prefix_in_serial_number_for_disassembly = 'Prefix in serial number for disassembly',
    prefix_in_serial_number_for_shipment = 'Prefix in Serial Number for Shipment',
    prefix_in_serial_number_for_direct_withdraw = 'Prefix in Serial Number for Direct Withdraw',
    prefix_in_transaction_number_for_direct_receipt = 'Prefix in Transaction Number for Direct Receipt',
    prefix_in_serial_number_for_purchase_invoice = 'Prefix in Serial Number for Purchase Invoice',
    prefix_in_serial_number_for_internal_orders = 'Prefix in Serial Number for Internal Orders',
    prefix_in_serial_number_for_reservation_order = 'Prefix in Serial Number for Reservation Order',
    prefix_in_serial_hyphen_number_for_packing_list_entered_for_thi = 'Prefix in serial-number for packing list entered for this Warehouse',
    prefix_in_serial_number_for_picking_list = 'Prefix in Serial Number for Picking List',
    prefix_in_serial_number_for_place_list = 'Prefix in Serial Number for Place List',
    prefix_in_serial_number_for_purchase_order = 'Prefix in Serial Number for Purchase Order',
    prefix_in_serial_number_for_requisition = 'Prefix in Serial Number for Requisition',
    prefix_in_serial_number_for_receipt = 'Prefix in Serial Number for Receipt',
    prefix_in_serial_number_for_requirement = 'Prefix in Serial Number for Requirement',
    prefix_in_serial_number_for_replenishment = 'Prefix in serial number for replenishment',
    prefix_in_serial_number_for_sales_order = 'Prefix in Serial Number for Sales Order',
    prefix_in_serial_number_for_stocktake = 'Prefix in Serial Number for Stocktake',
    forwarder_agent_identification_code = 'Forwarder agent identification code',
    forwarder_identification_code = 'Forwarder identification code',
    temporary_delivery_stop_to_and_forth_this_warehouse = 'Temporary delivery stop to and forth this warehouse',
    gateway_identification_code = 'Gateway identification code',
    gateway_entry_line_code = 'Gateway Entry Line Code',
    gateway_entry_line_type = 'Gateway Entry Line Type',
    hide_warehouse_in_search_functions = 'Hide Warehouse in Search Functions',
    warehouse_handling_cost = 'Warehouse handling cost',
    internal_handling_leadtime = 'Internal Handling Leadtime',
    leadtime_in_hours_for_general_and_internal_handling_of_goods_in = 'Leadtime in hours for general and internal handling of goods in and out',
    horizon_historic_stock_transaction_log = 'Horizon: Historic Stock Transaction Log',
    closed_for_service_caused_by = 'Closed for Service Caused by',
    defines_if_a_warehouse_is_in_service_or_notdot = 'Defines if a Warehouse is in Service or Not.',
    internal_or_external_warehouse = 'Internal or External Warehouse',
    internal_location_or_delivery_address = 'Internal Location or Delivery Address',
    invoice_frequency__indicates_how_often_the_warehouse_will_be_in = 'Invoice frequency  indicates how often the warehouse will be invoiced.',
    inbound_transport_route = 'Inbound Transport Route',
    use_caused_by_code_at_stock_adjustment = 'Use Caused By Code at Stock Adjustment',
    stock_adjustment_controlled_by = 'Stock Adjustment Controlled by',
    stock_adjustment_message_handling = 'Stock Adjustment Message Handling',
    zero_cost_price_handling_at_stock_adjustment = 'Zero Cost Price Handling at Stock Adjustment',
    withdrawal_scanning_sequence_1 = 'Withdrawal Scanning Sequence 1',
    default_job_queue_for_service_management = 'Default Job Queue for Service Management',
    label_layout_configuration = 'Label Layout Configuration',
    label_print_command_file_configuration = 'Label Print Command File Configuration',
    gives_the_number_of_lines_per_page_in_a_stocktake_list = 'Gives the number of lines per page in a stocktake list',
    _default_line_type = ' Default Line Type',
    loading_location_identification_code = 'Loading location identification code',
    language_identification_code = 'Language Identification Code',
    set_default_location_at_stock_move = 'Set Default Location at Stock Move',
    mailing__slash__postal_address_line_1 = 'Mailing / Postal Address: Line 1',
    mailing__slash__postal_address_line_2 = 'Mailing / Postal Address: Line 2',
    mailing__slash__postal_address_line_3 = 'Mailing / Postal Address: Line 3',
    mailing__slash__postal_address_line_4 = 'Mailing / Postal Address: Line 4',
    null = 'NULL',
    default_markup_percentage = 'Default markup percentage',
    password_restrictions_in_manual_request_approval = 'Password restrictions in manual request approval',
    user_restrictions_in_manual_request_approval = 'User restrictions in manual request approval',
    item_restrictions_in_manual_request_entry = 'Item restrictions in manual request entry',
    supplier_restrictions_in_manual_request_entry = 'Supplier restrictions in manual request entry',
    master_in_bulletin_board = 'Master in Bulletin Board',
    master_in_location_mapping = 'Master in Location Mapping',
    master_in_remarks__slash__notes = 'Master in Remarks / Notes',
    outbound_transport_route = 'Outbound Transport Route',
    order_type_for_catering_slash_meal_order = 'Order Type for Catering/Meal Order',
    requisition_order_type_cabinet_order = 'Requisition Order Type: Cabinet Order',
    requisition_order_type = 'Requisition Order Type',
    requisition_order_type_cart_order = 'Requisition Order Type: Cart Order',
    open_requisition_order_type = 'Open Requisition Order Type',
    order_type_for_handling_return_on_requisition = 'Order Type for Handling Return on Requisition',
    default_sales_order_type_for_stock_transfer = 'Default Sales Order Type for Stock Transfer',
    reservation_order_type_identifcation_code = 'Reservation Order Type Identifcation Code',
    warehouse_linked_to_owner_code_according_to_type = 'Warehouse linked to owner code according to type',
    warehouse_linked_to_owner_type = 'Warehouse linked to owner type',
    auto_allocate_stock_prior_to_picking = 'Auto Allocate Stock Prior to Picking',
    horizon_for_generating_picking_list = 'Horizon for Generating Picking List',
    include_sales_order_for_picking = 'Include Sales Order for Picking',
    include_work_order_for_picking = 'Include Work Order for Picking',
    telephone_extension_number_to_warehouse_contact_person = 'Telephone extension number to warehouse contact person',
    telephone_number_to_warehouse_switchboard = 'Telephone number to warehouse switchboard',
    background_picture_hyphen_file_for_graphic_mapping_of_warehouse = 'Background picture-file for graphic mapping of warehouse',
    post_account_number = 'Post account number',
    purchaser_identification_code = 'Purchaser Identification Code',
    price_zone_deefining_a_term_used_in_a_region_differentiated_pri = 'Price zone: deefining a term used in a region differentiated price-matrix',
    not_in_use = 'Not in use',
    entry_profile_identfication_code = 'Entry Profile Identfication Code',
    order_priority = 'Order Priority',
    pick_requirement_planning_forwarding_agent = 'Pick Requirement Planning: Forwarding Agent',
    pick_requirement_planning_receiver_type = 'Pick Requirement Planning: Receiver Type',
    pick_requirement_planning_auto_release = 'Pick Requirement Planning: Auto Release',
    pick_requirement_planning_use_session = 'Pick Requirement Planning: Use Session',
    print_internal_stock_adjustment_document = 'Print Internal Stock Adjustment Document',
    print_internal_stock_move_document = 'Print Internal Stock Move Document',
    print_internal_stock_transfer_document = 'Print Internal Stock Transfer Document',
    print_internal_stock_merge_document = 'Print Internal Stock Merge Document',
    printer_set_identification_code = 'Printer set identification code',
    planned_stock_turnover_value = 'Planned stock turnover value',
    planned_service_level_value_delivery = 'Planned service level value: delivery',
    indicates_how_part_delivery_is_to_be_managed = 'Indicates how part delivery is to be managed',
    quality_manager_identification_code = 'Quality Manager Identification Code',
    region_identification_code = 'Region Identification Code',
    organization_or_registration_number = 'Organization or Registration Number',
    resupply_from_warehouse = 'Resupply from Warehouse',
    start_date_for_closed_for_service_interval = 'Start Date for Closed for Service Interval',
    stock_catalogue_options_identification_code = 'Stock Catalogue Options Identification Code',
    scpwhs = 'No description found in source docs.',
    sales_order_discount_matrix_identification_code = 'Sales order discount matrix identification code',
    sales_order_fixed_item_discount_identification_code = 'Sales order fixed item discount identification code',
    sales_order_item_discount_matrix_identification_code = 'Sales order item discount matrix identification code',
    sales_order_direct_allocate_stock = 'Sales Order: Direct Allocate Stock',
    sales_order_direct_picking_list_confirmation = 'Sales Order: Direct Picking List Confirmation',
    sales_order_direct_delivery = 'Sales Order: Direct Delivery',
    sales_order_direct_pakcing = 'Sales Order: Direct Pakcing',
    sales_order_direct_generation_of_picking_list = 'Sales Order: Direct Generation of Picking List',
    sales_price_list_code = 'Sales price list code',
    defines_if_and_on_what_a_pickinglist_is_supposed_to_be_splitdot = 'Defines if and on what a pickinglist is supposed to be split.',
    split_place_list = 'Split Place List',
    shortname = 'Shortname',
    shortnumber = 'Shortnumber',
    default_sort_sequence_for_picking_list = 'Default Sort Sequence for Picking List',
    sorting_of_picking_list_in_picking_terminal_1 = 'Sorting of Picking List in Picking Terminal 1',
    standard_leadtime_for_items_to_slash_forth = 'Standard leadtime for items to/forth',
    generate_stocktake_as_type = 'Generate StockTake as Type',
    default_internal_distribution_service_identification_code = 'Default Internal Distribution Service Identification Code',
    telex_number_to_warehouse_switchboard = 'Telex number to warehouse switchboard',
    terms_of_payment = 'Terms of payment',
    terms_defined_for_this_specific_owner = 'Terms defined for this specific owner',
    defines_if_demand_is_to_be_accumulated_for_this_warehouse = 'Defines if demand is to be accumulated for this Warehouse',
    activate_use_of_cost_deviation_control = 'Activate Use of Cost Deviation Control',
    include_stock_transfer_in_demand = 'Include Stock Transfer in Demand',
    defines_if_first_hyphen_in_first_hyphen_out_transactions_are_av = 'Defines if First-In First-Out transactions are available',
    defines_if_multiple_stock_locations_are_available = 'Defines if multiple stock locations are available',
    defines_if_periodic_stock_is_available = 'Defines if periodic stock is available',
    defines_if_historical_stock_transactions_are_available = 'Defines if historical stock transactions are available',
    current_stock_turnover_value_last_changed_date = 'Current stock turnover value last changed date',
    current_service_level_value_for_delivery_last_changed_date = 'Current service level value for delivery last changed date',
    value_added_tax_identification_code = 'Value added tax identification code',
    value_added_tax_registration_number = 'Value Added Tax Registration Number',
    voucher_group = 'Voucher Group',
    visiting_address_line_1 = 'Visiting Address: Line 1',
    visiting_address_line_2 = 'Visiting Address: Line 2',
    visiting_address_line_3 = 'Visiting Address: Line 3',
    visiting_address_line_4 = 'Visiting Address: Line 4',
    warehouse_category_identification_code = 'Warehouse Category Identification Code',
    warehouse_group_identification_code = 'Warehouse group identification code',
    active__slash__passive_status_code = 'Active / passive status code',
    warehouse_identification_code = 'Warehouse Identification Code',
    warehouse_interest_cost_in_percent_per_year = 'Warehouse interest cost: in percent per year',
    warehouse_form_stocked_or_non_hyphen_stocked_warehouse = 'Warehouse Form: Stocked or Non-Stocked Warehouse',
    lifecycle_status_code = 'Lifecycle status code',
    warehouse_name__slash__description = 'Warehouse Name / Description',
    warehouse_type_identifying_ownership_and_control_level = 'Warehouse type: identifying ownership and control level',
    default_warehouse_transaction_type_for_manual_arrival = 'Default warehouse transaction type for manual arrival',
    default_warehouse_transaction_type_for_manual_receipt = 'Default warehouse transaction type for manual receipt',
    warehouse_order_type_for_issue = 'Warehouse order type for issue',
    order_type_for_handling_of_manual_receipt = 'Order Type for Handling of Manual Receipt',
    warehouse_ordertype_for_withdraw = 'Warehouse ordertype for withdraw',
    warehouse_type_identification_code = 'Warehouse Type Identification Code',
    default_external_trade_catalogue = 'Default external trade catalogue'
  )
);

SELECT
  defacs AS Account_set_is_used_for_both_sides_in_a_stock_transfer,
  actcod AS Account_table_identification_code,
  usecdc AS Activate_Use_of_Cost_Deviation_Control,
  whsact AS Active__slash__passive_status_code,
  awhsnm AS Additional_Warehouse_Name,
  appfda AS Approved_for_Business_from_Date,
  appuda AS Approved_for_Business_until_Date,
  pckalc AS Auto_Allocate_Stock_Prior_to_Picking,
  autalc AS Automatic_Allocation_of_Stock,
  autpck AS Automatic_Confirm_Picking_List,
  auidar AS Automatic_link_to_internal_distribution_from_arrival,
  picfil AS Background_picture_hyphen_file_for_graphic_mapping_of_warehouse,
  bankac AS Bank_account_number,
  blltyp AS Barcode_Label_Type,
  appcls AS Business_approval_classification,
  inscby AS Closed_for_Service_Caused_by,
  compny AS Company_Identification_Code,
  cnsreg AS Consignment_Reference_Registration,
  crpwhs AS Coroprate_Warehouse_open_for_Transactions,
  clicod AS Corporate_Client_Identification_Code,
  csccod AS Cost_center_identification_code,
  cntcod AS Country_identification_code,
  crbplm AS Credit_Balance_Method,
  crbcod AS Credit_balance_setup_code,
  curcod AS Currency_identification_code,
  curtyp AS Currency_type,
  csldlu AS Current_service_level_for_delivery_last_changed_by_user,
  csldlv AS Current_service_level_value_delivery,
  valunt AS Current_service_level_value_for_delivery_last_changed_date,
  csttov AS Current_stock_turnover_value,
  csttou AS Current_stock_turnover_value_last_changed_by_user,
  valfrm AS Current_stock_turnover_value_last_changed_date,
  cdcval AS Default_Cost_Deviation_Control_Percentage,
  svccod AS Default_Internal_Distribution_Service_Identification_Code,
  jobque AS Default_Job_Queue_for_Service_Management,
  otsstt AS Default_Sales_Order_Type_for_Stock_Transfer,
  srtpck AS Default_Sort_Sequence_for_Picking_List,
  xtccod AS Default_external_trade_catalogue,
  markup AS Default_markup_percentage,
  defprc AS Default_sales_price_method,
  wttdma AS Default_warehouse_transaction_type_for_manual_arrival,
  wttdmr AS Default_warehouse_transaction_type_for_manual_receipt,
  usfifo AS Defines_if_First_hyphen_In_First_hyphen_Out_transactions_are_av,
  inssts AS Defines_if_a_Warehouse_is_in_Service_or_Notdot,
  aphdlc AS Defines_if_and_how_handling_hyphen_cost_is_to_be_applied,
  apwhsc AS Defines_if_and_how_warehouse_hyphen_cost_is_to_be_applied,
  splpck AS Defines_if_and_on_what_a_pickinglist_is_supposed_to_be_splitdot,
  usdmac AS Defines_if_demand_is_to_be_accumulated_for_this_Warehouse,
  ustrlo AS Defines_if_historical_stock_transactions_are_available,
  usmulo AS Defines_if_multiple_stock_locations_are_available,
  uspdst AS Defines_if_periodic_stock_is_available,
  dmdwhs AS Defines_which_warehouse_accumulated_demand_is_to_be_re_hyphen_r,
  dladr1 AS Delivery_Address_Line_1,
  dladr2 AS Delivery_Address_Line_2,
  dladr3 AS Delivery_Address_Line_3,
  dladr4 AS Delivery_Address_Line_4,
  dlgcod AS Delivery_group_identification_code,
  dptcod AS Department_Identification_Code,
  dbdpdc AS Display_Production_Proposals_in_Day_by_Day,
  dbdprc AS Display_Purchase_Proposals_in_Day_by_Day,
  dstcod AS District_Identification_Code,
  dcscod AS Document_Set_Identification_Code,
  ecregn AS EORI__hyphen__Economic_Operators_Registration_and_Identificatio,
  enblma AS Enable_Mail_Address_Entry,
  enblva AS Enable_Visiting_Address_Entry,
  eclins AS End_Date_for_Closed_for_Service_Interval,
  ettcod AS Entity_Identification_Code,
  prfcod AS Entry_Profile_Identfication_Code,
  ecland AS European_Community_Country_Code,
  fixdsc AS Fixed_discount_percentage,
  fwacod AS Forwarder_agent_identification_code,
  fwdcod AS Forwarder_identification_code,
  gwlcod AS Gateway_Entry_Line_Code,
  gwltyp AS Gateway_Entry_Line_Type,
  gtwcod AS Gateway_identification_code,
  stltyp AS Generate_StockTake_as_Type,
  linstp AS Gives_the_number_of_lines_per_page_in_a_stocktake_list,
  hidsrc AS Hide_Warehouse_in_Search_Functions,
  hsthrz AS Horizon_Historic_Stock_Transaction_Log,
  pckhrz AS Horizon_for_Generating_Picking_List,
  irtcod AS Inbound_Transport_Route,
  pcksor AS Include_Sales_Order_for_Picking,
  usfcst AS Include_Stock_Transfer_in_Demand,
  pckwor AS Include_Work_Order_for_Picking,
  ptdlvm AS Indicates_how_part_delivery_is_to_be_managed,
  adrctr AS Indicates_if_address_control_is_to_be_executed_or_not,
  credat AS Information_Created_Date,
  creusr AS Information_created_by_user,
  chgusr AS Information_last_changed_by_user,
  chgdat AS Information_last_changed_date,
  hndldt AS Internal_Handling_Leadtime,
  intloc AS Internal_Location_or_Delivery_Address,
  intext AS Internal_or_External_Warehouse,
  invfrq AS Invoice_frequency__indicates_how_often_the_warehouse_will_be_in,
  mrenit AS Item_restrictions_in_manual_request_entry,
  lczlbl AS Label_Layout_Configuration,
  lczpcf AS Label_Print_Command_File_Configuration,
  lngcod AS Language_Identification_Code,
  exwldt AS Leadtime_for_Ex_hyphen_Works_Termsdot_Part_of_Standard_Leadtime,
  hndtim AS Leadtime_in_hours_for_general_and_internal_handling_of_goods_in,
  whslcy AS Lifecycle_status_code,
  llccod AS Loading_location_identification_code,
  maadr1 AS Mailing__slash__Postal_Address_Line_1,
  maadr2 AS Mailing__slash__Postal_Address_Line_2,
  maadr3 AS Mailing__slash__Postal_Address_Line_3,
  maadr4 AS Mailing__slash__Postal_Address_Line_4,
  mstbbs AS Master_in_Bulletin_Board,
  mstlcm AS Master_in_Location_Mapping,
  mstmrk AS Master_in_Remarks__slash__Notes,
  manreq AS NULL,
  prdstc AS Not_in_use,
  otropn AS Open_Requisition_Order_Type,
  pricod AS Order_Priority,
  otccod AS Order_Type_for_Catering_slash_Meal_Order,
  otrrtn AS Order_Type_for_Handling_Return_on_Requisition,
  wttmrc AS Order_Type_for_Handling_of_Manual_Receipt,
  regnum AS Organization_or_Registration_Number,
  ortcod AS Outbound_Transport_Route,
  mrappw AS Password_restrictions_in_manual_request_approval,
  prprel AS Pick_Requirement_Planning_Auto_Release,
  prpfwa AS Pick_Requirement_Planning_Forwarding_Agent,
  prprcv AS Pick_Requirement_Planning_Receiver_Type,
  prpses AS Pick_Requirement_Planning_Use_Session,
  psvcld AS Planned_service_level_value_delivery,
  psttov AS Planned_stock_turnover_value,
  postac AS Post_account_number,
  fixarr AS Prefix_in_Serial_Number_for_Arrival,
  fixeoo AS Prefix_in_Serial_Number_for_Direct_Withdraw,
  fixior AS Prefix_in_Serial_Number_for_Internal_Orders,
  fixpil AS Prefix_in_Serial_Number_for_Picking_List,
  fixpll AS Prefix_in_Serial_Number_for_Place_List,
  fixiin AS Prefix_in_Serial_Number_for_Purchase_Invoice,
  fixprc AS Prefix_in_Serial_Number_for_Purchase_Order,
  fixrcp AS Prefix_in_Serial_Number_for_Receipt,
  fixreq AS Prefix_in_Serial_Number_for_Requirement,
  fixprq AS Prefix_in_Serial_Number_for_Requisition,
  fixotv AS Prefix_in_Serial_Number_for_Reservation_Order,
  fixcrd AS Prefix_in_Serial_Number_for_Sales_Credit_Invoice,
  ficinv AS Prefix_in_Serial_Number_for_Sales_Invoice,
  fixsor AS Prefix_in_Serial_Number_for_Sales_Order,
  fixdsp AS Prefix_in_Serial_Number_for_Shipment,
  fixstt AS Prefix_in_Serial_Number_for_Stocktake,
  fixeor AS Prefix_in_Transaction_Number_for_Direct_Receipt,
  fixpal AS Prefix_in_serial_hyphen_number_for_packing_list_entered_for_thi,
  fixdsm AS Prefix_in_serial_number_for_disassembly,
  fixrpl AS Prefix_in_serial_number_for_replenishment,
  prczon AS Price_zone_deefining_a_term_used_in_a_region_differentiated_pri,
  prtisa AS Print_Internal_Stock_Adjustment_Document,
  prtisx AS Print_Internal_Stock_Merge_Document,
  prtism AS Print_Internal_Stock_Move_Document,
  prtist AS Print_Internal_Stock_Transfer_Document,
  pstcod AS Printer_set_identification_code,
  prccod AS Purchaser_Identification_Code,
  qlmcod AS Quality_Manager_Identification_Code,
  regcod AS Region_Identification_Code,
  otrcod AS Requisition_Order_Type,
  otrcdb AS Requisition_Order_Type_Cabinet_Order,
  otrcrt AS Requisition_Order_Type_Cart_Order,
  otvcod AS Reservation_Order_Type_Identifcation_Code,
  rspwhs AS Resupply_from_Warehouse,
  sordas AS Sales_Order_Direct_Allocate_Stock,
  sorddl AS Sales_Order_Direct_Delivery,
  sordpl AS Sales_Order_Direct_Generation_of_Picking_List,
  sordpk AS Sales_Order_Direct_Pakcing,
  sordcp AS Sales_Order_Direct_Picking_List_Confirmation,
  sdxcod AS Sales_order_discount_matrix_identification_code,
  sifcod AS Sales_order_fixed_item_discount_identification_code,
  sixcod AS Sales_order_item_discount_matrix_identification_code,
  splcod AS Sales_price_list_code,
  locism AS Set_Default_Location_at_Stock_Move,
  srtnam AS Shortname,
  srtnum AS Shortnumber,
  srtpt1 AS Sorting_of_Picking_List_in_Picking_Terminal_1,
  splpll AS Split_Place_List,
  stdldt AS Standard_leadtime_for_items_to_slash_forth,
  sclins AS Start_Date_for_Closed_for_Service_Interval,
  isactr AS Stock_Adjustment_Controlled_by,
  isamsg AS Stock_Adjustment_Message_Handling,
  scocod AS Stock_Catalogue_Options_Identification_Code,
  mrensu AS Supplier_restrictions_in_manual_request_entry,
  faxswt AS Telefax_number_to_warehouse_switchboard,
  phnext AS Telephone_extension_number_to_warehouse_contact_person,
  phnswt AS Telephone_number_to_warehouse_switchboard,
  tlxswt AS Telex_number_to_warehouse_switchboard,
  fwstop AS Temporary_delivery_stop_to_and_forth_this_warehouse,
  ccdlvs AS Temporay_delivery_stop_caused_by,
  tpyown AS Terms_defined_for_this_specific_owner,
  tpycod AS Terms_of_payment,
  isacby AS Use_Caused_By_Code_at_Stock_Adjustment,
  mrapus AS User_restrictions_in_manual_request_approval,
  vatnum AS Value_Added_Tax_Registration_Number,
  vatcod AS Value_added_tax_identification_code,
  viadr1 AS Visiting_Address_Line_1,
  viadr2 AS Visiting_Address_Line_2,
  viadr3 AS Visiting_Address_Line_3,
  viadr4 AS Visiting_Address_Line_4,
  vcrgrp AS Voucher_Group,
  wctcod AS Warehouse_Category_Identification_Code,
  whsfrm AS Warehouse_Form_Stocked_or_Non_hyphen_Stocked_Warehouse,
  whscod AS Warehouse_Identification_Code,
  whsnam AS Warehouse_Name__slash__Description,
  wtycod AS Warehouse_Type_Identification_Code,
  ctcprs AS Warehouse_contact_person,
  wgrcod AS Warehouse_group_identification_code,
  hndcst AS Warehouse_handling_cost,
  whscst AS Warehouse_interest_cost_in_percent_per_year,
  owncod AS Warehouse_linked_to_owner_code_according_to_type,
  owntyp AS Warehouse_linked_to_owner_type,
  wttiss AS Warehouse_order_type_for_issue,
  wttwdw AS Warehouse_ordertype_for_withdraw,
  whstyp AS Warehouse_type_identifying_ownership_and_control_level,
  isssc1 AS Withdrawal_Scanning_Sequence_1,
  isazch AS Zero_Cost_Price_Handling_at_Stock_Adjustment,
  lintyp AS _Default_Line_Type
FROM clockwork_sllclockdb01_dc_sll_se.rainbow_whs