
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read

        
@model(
    columns={'_data_modified_utc': 'date', '_metadata_modified_utc': 'datetime2', '_source': 'varchar(max)', 'A1_GILTIG_FOM': 'varchar(max)', 'A1_GILTIG_TOM': 'varchar(max)', 'A1_ID': 'varchar(max)', 'A1_ID_TEXT': 'varchar(max)', 'A1_PASSIV': 'varchar(max)', 'A1_TEXT': 'varchar(max)', 'A2_GILTIG_FOM': 'varchar(max)', 'A2_GILTIG_TOM': 'varchar(max)', 'A2_ID': 'varchar(max)', 'A2_ID_TEXT': 'varchar(max)', 'A2_PASSIV': 'varchar(max)', 'A2_TEXT': 'varchar(max)', 'A3_GILTIG_FOM': 'varchar(max)', 'A3_GILTIG_TOM': 'varchar(max)', 'A3_ID': 'varchar(max)', 'A3_ID_TEXT': 'varchar(max)', 'A3_PASSIV': 'varchar(max)', 'A3_TEXT': 'varchar(max)', 'C1_GILTIG_FOM': 'varchar(max)', 'C1_GILTIG_TOM': 'varchar(max)', 'C1_ID': 'varchar(max)', 'C1_ID_TEXT': 'varchar(max)', 'C1_PASSIV': 'varchar(max)', 'C1_TEXT': 'varchar(max)', 'C2_GILTIG_FOM': 'varchar(max)', 'C2_GILTIG_TOM': 'varchar(max)', 'C2_ID': 'varchar(max)', 'C2_ID_TEXT': 'varchar(max)', 'C2_PASSIV': 'varchar(max)', 'C2_TEXT': 'varchar(max)', 'C3_GILTIG_FOM': 'varchar(max)', 'C3_GILTIG_TOM': 'varchar(max)', 'C3_ID': 'varchar(max)', 'C3_ID_TEXT': 'varchar(max)', 'C3_PASSIV': 'varchar(max)', 'C3_TEXT': 'varchar(max)', 'D3_GILTIG_FOM': 'varchar(max)', 'D3_GILTIG_TOM': 'varchar(max)', 'D3_ID': 'varchar(max)', 'D3_ID_TEXT': 'varchar(max)', 'D3_PASSIV': 'varchar(max)', 'D3_TEXT': 'varchar(max)', 'DSRRK_GILTIG_FOM': 'varchar(max)', 'DSRRK_GILTIG_TOM': 'varchar(max)', 'DSRRK_ID': 'varchar(max)', 'DSRRK_ID_TEXT': 'varchar(max)', 'DSRRK_PASSIV': 'varchar(max)', 'DSRRK_TEXT': 'varchar(max)', 'DSRRL_GILTIG_FOM': 'varchar(max)', 'DSRRL_GILTIG_TOM': 'varchar(max)', 'DSRRL_ID': 'varchar(max)', 'DSRRL_ID_TEXT': 'varchar(max)', 'DSRRL_PASSIV': 'varchar(max)', 'DSRRL_TEXT': 'varchar(max)', 'FRA1I_GILTIG_FOM': 'varchar(max)', 'FRA1I_GILTIG_TOM': 'varchar(max)', 'FRA1I_ID': 'varchar(max)', 'FRA1I_ID_TEXT': 'varchar(max)', 'FRA1I_PASSIV': 'varchar(max)', 'FRA1I_TEXT': 'varchar(max)', 'FRANGI_GILTIG_FOM': 'varchar(max)', 'FRANGI_GILTIG_TOM': 'varchar(max)', 'FRANGI_ID': 'varchar(max)', 'FRANGI_ID_TEXT': 'varchar(max)', 'FRANGI_PASSIV': 'varchar(max)', 'FRANGI_TEXT': 'varchar(max)', 'GFRA1I_GILTIG_FOM': 'varchar(max)', 'GFRA1I_GILTIG_TOM': 'varchar(max)', 'GFRA1I_ID': 'varchar(max)', 'GFRA1I_ID_TEXT': 'varchar(max)', 'GFRA1I_PASSIV': 'varchar(max)', 'GFRA1I_TEXT': 'varchar(max)', 'GFRA1_GILTIG_FOM': 'varchar(max)', 'GFRA1_GILTIG_TOM': 'varchar(max)', 'GFRA1_ID': 'varchar(max)', 'GFRA1_ID_TEXT': 'varchar(max)', 'GFRA1_PASSIV': 'varchar(max)', 'GFRA1_TEXT': 'varchar(max)', 'GRANGI_GILTIG_FOM': 'varchar(max)', 'GRANGI_GILTIG_TOM': 'varchar(max)', 'GRANGI_ID': 'varchar(max)', 'GRANGI_ID_TEXT': 'varchar(max)', 'GRANGI_PASSIV': 'varchar(max)', 'GRANGI_TEXT': 'varchar(max)', 'GRANGO_GILTIG_FOM': 'varchar(max)', 'GRANGO_GILTIG_TOM': 'varchar(max)', 'GRANGO_ID': 'varchar(max)', 'GRANGO_ID_TEXT': 'varchar(max)', 'GRANGO_PASSIV': 'varchar(max)', 'GRANGO_TEXT': 'varchar(max)', 'KKTO1_GILTIG_FOM': 'varchar(max)', 'KKTO1_GILTIG_TOM': 'varchar(max)', 'KKTO1_ID': 'varchar(max)', 'KKTO1_ID_TEXT': 'varchar(max)', 'KKTO1_PASSIV': 'varchar(max)', 'KKTO1_TEXT': 'varchar(max)', 'KKTO_GILTIG_FOM': 'varchar(max)', 'KKTO_GILTIG_TOM': 'varchar(max)', 'KKTO_ID': 'varchar(max)', 'KKTO_ID_TEXT': 'varchar(max)', 'KKTO_PASSIV': 'varchar(max)', 'KKTO_TEXT': 'varchar(max)', 'KONTO_GILTIG_FOM': 'varchar(max)', 'KONTO_GILTIG_TOM': 'varchar(max)', 'KONTO_ID': 'varchar(max)', 'KONTO_ID_TEXT': 'varchar(max)', 'KONTO_PASSIV': 'varchar(max)', 'KONTO_TEXT': 'varchar(max)', 'M2_GILTIG_FOM': 'varchar(max)', 'M2_GILTIG_TOM': 'varchar(max)', 'M2_ID': 'varchar(max)', 'M2_ID_TEXT': 'varchar(max)', 'M2_PASSIV': 'varchar(max)', 'M2_TEXT': 'varchar(max)', 'M3_GILTIG_FOM': 'varchar(max)', 'M3_GILTIG_TOM': 'varchar(max)', 'M3_ID': 'varchar(max)', 'M3_ID_TEXT': 'varchar(max)', 'M3_PASSIV': 'varchar(max)', 'M3_TEXT': 'varchar(max)', 'SKKTO1_GILTIG_FOM': 'varchar(max)', 'SKKTO1_GILTIG_TOM': 'varchar(max)', 'SKKTO1_ID': 'varchar(max)', 'SKKTO1_ID_TEXT': 'varchar(max)', 'SKKTO1_PASSIV': 'varchar(max)', 'SKKTO1_TEXT': 'varchar(max)', 'SKKTO_GILTIG_FOM': 'varchar(max)', 'SKKTO_GILTIG_TOM': 'varchar(max)', 'SKKTO_ID': 'varchar(max)', 'SKKTO_ID_TEXT': 'varchar(max)', 'SKKTO_PASSIV': 'varchar(max)', 'SKKTO_TEXT': 'varchar(max)', 'SRU2_GILTIG_FOM': 'varchar(max)', 'SRU2_GILTIG_TOM': 'varchar(max)', 'SRU2_ID': 'varchar(max)', 'SRU2_ID_TEXT': 'varchar(max)', 'SRU2_PASSIV': 'varchar(max)', 'SRU2_TEXT': 'varchar(max)', 'SRU_GILTIG_FOM': 'varchar(max)', 'SRU_GILTIG_TOM': 'varchar(max)', 'SRU_ID': 'varchar(max)', 'SRU_ID_TEXT': 'varchar(max)', 'SRU_PASSIV': 'varchar(max)', 'SRU_TEXT': 'varchar(max)', 'UPPH_GILTIG_FOM': 'varchar(max)', 'UPPH_GILTIG_TOM': 'varchar(max)', 'UPPH_ID': 'varchar(max)', 'UPPH_ID_TEXT': 'varchar(max)', 'UPPH_PASSIV': 'varchar(max)', 'UPPH_TEXT': 'varchar(max)', 'XB1_GILTIG_FOM': 'varchar(max)', 'XB1_GILTIG_TOM': 'varchar(max)', 'XB1_ID': 'varchar(max)', 'XB1_ID_TEXT': 'varchar(max)', 'XB1_PASSIV': 'varchar(max)', 'XB1_TEXT': 'varchar(max)', 'XB2_GILTIG_FOM': 'varchar(max)', 'XB2_GILTIG_TOM': 'varchar(max)', 'XB2_ID': 'varchar(max)', 'XB2_ID_TEXT': 'varchar(max)', 'XB2_PASSIV': 'varchar(max)', 'XB2_TEXT': 'varchar(max)', 'XDSRRK_GILTIG_FOM': 'varchar(max)', 'XDSRRK_GILTIG_TOM': 'varchar(max)', 'XDSRRK_ID': 'varchar(max)', 'XDSRRK_ID_TEXT': 'varchar(max)', 'XDSRRK_PASSIV': 'varchar(max)', 'XDSRRK_TEXT': 'varchar(max)', 'XDSRRL_GILTIG_FOM': 'varchar(max)', 'XDSRRL_GILTIG_TOM': 'varchar(max)', 'XDSRRL_ID': 'varchar(max)', 'XDSRRL_ID_TEXT': 'varchar(max)', 'XDSRRL_PASSIV': 'varchar(max)', 'XDSRRL_TEXT': 'varchar(max)', 'XKKTO2_GILTIG_FOM': 'varchar(max)', 'XKKTO2_GILTIG_TOM': 'varchar(max)', 'XKKTO2_ID': 'varchar(max)', 'XKKTO2_ID_TEXT': 'varchar(max)', 'XKKTO2_PASSIV': 'varchar(max)', 'XKKTO2_TEXT': 'varchar(max)', 'XKTO2_GILTIG_FOM': 'varchar(max)', 'XKTO2_GILTIG_TOM': 'varchar(max)', 'XKTO2_ID': 'varchar(max)', 'XKTO2_ID_TEXT': 'varchar(max)', 'XKTO2_PASSIV': 'varchar(max)', 'XKTO2_TEXT': 'varchar(max)', 'XXFRA1_GILTIG_FOM': 'varchar(max)', 'XXFRA1_GILTIG_TOM': 'varchar(max)', 'XXFRA1_ID': 'varchar(max)', 'XXFRA1_ID_TEXT': 'varchar(max)', 'XXFRA1_PASSIV': 'varchar(max)', 'XXFRA1_TEXT': 'varchar(max)', 'XXRA1I_GILTIG_FOM': 'varchar(max)', 'XXRA1I_GILTIG_TOM': 'varchar(max)', 'XXRA1I_ID': 'varchar(max)', 'XXRA1I_ID_TEXT': 'varchar(max)', 'XXRA1I_PASSIV': 'varchar(max)', 'XXRA1I_TEXT': 'varchar(max)'},
    kind=dict(
        name=ModelKindName.FULL
    ),
    cron="@daily"
)

        
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = f"""
	SELECT * FROM (SELECT 
 		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _data_modified_utc,
		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _metadata_modified_utc,
		'dsp_rd_sll_se_raindance_udp_udp_150' as _source,
		CONVERT(varchar(max), A1_GILTIG_FOM, 126) AS a1_giltig_fom,
		CONVERT(varchar(max), A1_GILTIG_TOM, 126) AS a1_giltig_tom,
		CAST(A1_ID AS VARCHAR(MAX)) AS a1_id,
		CAST(A1_ID_TEXT AS VARCHAR(MAX)) AS a1_id_text,
		CAST(A1_PASSIV AS VARCHAR(MAX)) AS a1_passiv,
		CAST(A1_TEXT AS VARCHAR(MAX)) AS a1_text,
		CONVERT(varchar(max), A2_GILTIG_FOM, 126) AS a2_giltig_fom,
		CONVERT(varchar(max), A2_GILTIG_TOM, 126) AS a2_giltig_tom,
		CAST(A2_ID AS VARCHAR(MAX)) AS a2_id,
		CAST(A2_ID_TEXT AS VARCHAR(MAX)) AS a2_id_text,
		CAST(A2_PASSIV AS VARCHAR(MAX)) AS a2_passiv,
		CAST(A2_TEXT AS VARCHAR(MAX)) AS a2_text,
		CONVERT(varchar(max), A3_GILTIG_FOM, 126) AS a3_giltig_fom,
		CONVERT(varchar(max), A3_GILTIG_TOM, 126) AS a3_giltig_tom,
		CAST(A3_ID AS VARCHAR(MAX)) AS a3_id,
		CAST(A3_ID_TEXT AS VARCHAR(MAX)) AS a3_id_text,
		CAST(A3_PASSIV AS VARCHAR(MAX)) AS a3_passiv,
		CAST(A3_TEXT AS VARCHAR(MAX)) AS a3_text,
		CONVERT(varchar(max), C1_GILTIG_FOM, 126) AS c1_giltig_fom,
		CONVERT(varchar(max), C1_GILTIG_TOM, 126) AS c1_giltig_tom,
		CAST(C1_ID AS VARCHAR(MAX)) AS c1_id,
		CAST(C1_ID_TEXT AS VARCHAR(MAX)) AS c1_id_text,
		CAST(C1_PASSIV AS VARCHAR(MAX)) AS c1_passiv,
		CAST(C1_TEXT AS VARCHAR(MAX)) AS c1_text,
		CONVERT(varchar(max), C2_GILTIG_FOM, 126) AS c2_giltig_fom,
		CONVERT(varchar(max), C2_GILTIG_TOM, 126) AS c2_giltig_tom,
		CAST(C2_ID AS VARCHAR(MAX)) AS c2_id,
		CAST(C2_ID_TEXT AS VARCHAR(MAX)) AS c2_id_text,
		CAST(C2_PASSIV AS VARCHAR(MAX)) AS c2_passiv,
		CAST(C2_TEXT AS VARCHAR(MAX)) AS c2_text,
		CONVERT(varchar(max), C3_GILTIG_FOM, 126) AS c3_giltig_fom,
		CONVERT(varchar(max), C3_GILTIG_TOM, 126) AS c3_giltig_tom,
		CAST(C3_ID AS VARCHAR(MAX)) AS c3_id,
		CAST(C3_ID_TEXT AS VARCHAR(MAX)) AS c3_id_text,
		CAST(C3_PASSIV AS VARCHAR(MAX)) AS c3_passiv,
		CAST(C3_TEXT AS VARCHAR(MAX)) AS c3_text,
		CONVERT(varchar(max), D3_GILTIG_FOM, 126) AS d3_giltig_fom,
		CONVERT(varchar(max), D3_GILTIG_TOM, 126) AS d3_giltig_tom,
		CAST(D3_ID AS VARCHAR(MAX)) AS d3_id,
		CAST(D3_ID_TEXT AS VARCHAR(MAX)) AS d3_id_text,
		CAST(D3_PASSIV AS VARCHAR(MAX)) AS d3_passiv,
		CAST(D3_TEXT AS VARCHAR(MAX)) AS d3_text,
		CONVERT(varchar(max), DSRRK_GILTIG_FOM, 126) AS dsrrk_giltig_fom,
		CONVERT(varchar(max), DSRRK_GILTIG_TOM, 126) AS dsrrk_giltig_tom,
		CAST(DSRRK_ID AS VARCHAR(MAX)) AS dsrrk_id,
		CAST(DSRRK_ID_TEXT AS VARCHAR(MAX)) AS dsrrk_id_text,
		CAST(DSRRK_PASSIV AS VARCHAR(MAX)) AS dsrrk_passiv,
		CAST(DSRRK_TEXT AS VARCHAR(MAX)) AS dsrrk_text,
		CONVERT(varchar(max), DSRRL_GILTIG_FOM, 126) AS dsrrl_giltig_fom,
		CONVERT(varchar(max), DSRRL_GILTIG_TOM, 126) AS dsrrl_giltig_tom,
		CAST(DSRRL_ID AS VARCHAR(MAX)) AS dsrrl_id,
		CAST(DSRRL_ID_TEXT AS VARCHAR(MAX)) AS dsrrl_id_text,
		CAST(DSRRL_PASSIV AS VARCHAR(MAX)) AS dsrrl_passiv,
		CAST(DSRRL_TEXT AS VARCHAR(MAX)) AS dsrrl_text,
		CONVERT(varchar(max), FRA1I_GILTIG_FOM, 126) AS fra1i_giltig_fom,
		CONVERT(varchar(max), FRA1I_GILTIG_TOM, 126) AS fra1i_giltig_tom,
		CAST(FRA1I_ID AS VARCHAR(MAX)) AS fra1i_id,
		CAST(FRA1I_ID_TEXT AS VARCHAR(MAX)) AS fra1i_id_text,
		CAST(FRA1I_PASSIV AS VARCHAR(MAX)) AS fra1i_passiv,
		CAST(FRA1I_TEXT AS VARCHAR(MAX)) AS fra1i_text,
		CONVERT(varchar(max), FRANGI_GILTIG_FOM, 126) AS frangi_giltig_fom,
		CONVERT(varchar(max), FRANGI_GILTIG_TOM, 126) AS frangi_giltig_tom,
		CAST(FRANGI_ID AS VARCHAR(MAX)) AS frangi_id,
		CAST(FRANGI_ID_TEXT AS VARCHAR(MAX)) AS frangi_id_text,
		CAST(FRANGI_PASSIV AS VARCHAR(MAX)) AS frangi_passiv,
		CAST(FRANGI_TEXT AS VARCHAR(MAX)) AS frangi_text,
		CONVERT(varchar(max), GFRA1I_GILTIG_FOM, 126) AS gfra1i_giltig_fom,
		CONVERT(varchar(max), GFRA1I_GILTIG_TOM, 126) AS gfra1i_giltig_tom,
		CAST(GFRA1I_ID AS VARCHAR(MAX)) AS gfra1i_id,
		CAST(GFRA1I_ID_TEXT AS VARCHAR(MAX)) AS gfra1i_id_text,
		CAST(GFRA1I_PASSIV AS VARCHAR(MAX)) AS gfra1i_passiv,
		CAST(GFRA1I_TEXT AS VARCHAR(MAX)) AS gfra1i_text,
		CONVERT(varchar(max), GFRA1_GILTIG_FOM, 126) AS gfra1_giltig_fom,
		CONVERT(varchar(max), GFRA1_GILTIG_TOM, 126) AS gfra1_giltig_tom,
		CAST(GFRA1_ID AS VARCHAR(MAX)) AS gfra1_id,
		CAST(GFRA1_ID_TEXT AS VARCHAR(MAX)) AS gfra1_id_text,
		CAST(GFRA1_PASSIV AS VARCHAR(MAX)) AS gfra1_passiv,
		CAST(GFRA1_TEXT AS VARCHAR(MAX)) AS gfra1_text,
		CONVERT(varchar(max), GRANGI_GILTIG_FOM, 126) AS grangi_giltig_fom,
		CONVERT(varchar(max), GRANGI_GILTIG_TOM, 126) AS grangi_giltig_tom,
		CAST(GRANGI_ID AS VARCHAR(MAX)) AS grangi_id,
		CAST(GRANGI_ID_TEXT AS VARCHAR(MAX)) AS grangi_id_text,
		CAST(GRANGI_PASSIV AS VARCHAR(MAX)) AS grangi_passiv,
		CAST(GRANGI_TEXT AS VARCHAR(MAX)) AS grangi_text,
		CONVERT(varchar(max), GRANGO_GILTIG_FOM, 126) AS grango_giltig_fom,
		CONVERT(varchar(max), GRANGO_GILTIG_TOM, 126) AS grango_giltig_tom,
		CAST(GRANGO_ID AS VARCHAR(MAX)) AS grango_id,
		CAST(GRANGO_ID_TEXT AS VARCHAR(MAX)) AS grango_id_text,
		CAST(GRANGO_PASSIV AS VARCHAR(MAX)) AS grango_passiv,
		CAST(GRANGO_TEXT AS VARCHAR(MAX)) AS grango_text,
		CONVERT(varchar(max), KKTO1_GILTIG_FOM, 126) AS kkto1_giltig_fom,
		CONVERT(varchar(max), KKTO1_GILTIG_TOM, 126) AS kkto1_giltig_tom,
		CAST(KKTO1_ID AS VARCHAR(MAX)) AS kkto1_id,
		CAST(KKTO1_ID_TEXT AS VARCHAR(MAX)) AS kkto1_id_text,
		CAST(KKTO1_PASSIV AS VARCHAR(MAX)) AS kkto1_passiv,
		CAST(KKTO1_TEXT AS VARCHAR(MAX)) AS kkto1_text,
		CONVERT(varchar(max), KKTO_GILTIG_FOM, 126) AS kkto_giltig_fom,
		CONVERT(varchar(max), KKTO_GILTIG_TOM, 126) AS kkto_giltig_tom,
		CAST(KKTO_ID AS VARCHAR(MAX)) AS kkto_id,
		CAST(KKTO_ID_TEXT AS VARCHAR(MAX)) AS kkto_id_text,
		CAST(KKTO_PASSIV AS VARCHAR(MAX)) AS kkto_passiv,
		CAST(KKTO_TEXT AS VARCHAR(MAX)) AS kkto_text,
		CONVERT(varchar(max), KONTO_GILTIG_FOM, 126) AS konto_giltig_fom,
		CONVERT(varchar(max), KONTO_GILTIG_TOM, 126) AS konto_giltig_tom,
		CAST(KONTO_ID AS VARCHAR(MAX)) AS konto_id,
		CAST(KONTO_ID_TEXT AS VARCHAR(MAX)) AS konto_id_text,
		CAST(KONTO_PASSIV AS VARCHAR(MAX)) AS konto_passiv,
		CAST(KONTO_TEXT AS VARCHAR(MAX)) AS konto_text,
		CONVERT(varchar(max), M2_GILTIG_FOM, 126) AS m2_giltig_fom,
		CONVERT(varchar(max), M2_GILTIG_TOM, 126) AS m2_giltig_tom,
		CAST(M2_ID AS VARCHAR(MAX)) AS m2_id,
		CAST(M2_ID_TEXT AS VARCHAR(MAX)) AS m2_id_text,
		CAST(M2_PASSIV AS VARCHAR(MAX)) AS m2_passiv,
		CAST(M2_TEXT AS VARCHAR(MAX)) AS m2_text,
		CONVERT(varchar(max), M3_GILTIG_FOM, 126) AS m3_giltig_fom,
		CONVERT(varchar(max), M3_GILTIG_TOM, 126) AS m3_giltig_tom,
		CAST(M3_ID AS VARCHAR(MAX)) AS m3_id,
		CAST(M3_ID_TEXT AS VARCHAR(MAX)) AS m3_id_text,
		CAST(M3_PASSIV AS VARCHAR(MAX)) AS m3_passiv,
		CAST(M3_TEXT AS VARCHAR(MAX)) AS m3_text,
		CONVERT(varchar(max), SKKTO1_GILTIG_FOM, 126) AS skkto1_giltig_fom,
		CONVERT(varchar(max), SKKTO1_GILTIG_TOM, 126) AS skkto1_giltig_tom,
		CAST(SKKTO1_ID AS VARCHAR(MAX)) AS skkto1_id,
		CAST(SKKTO1_ID_TEXT AS VARCHAR(MAX)) AS skkto1_id_text,
		CAST(SKKTO1_PASSIV AS VARCHAR(MAX)) AS skkto1_passiv,
		CAST(SKKTO1_TEXT AS VARCHAR(MAX)) AS skkto1_text,
		CONVERT(varchar(max), SKKTO_GILTIG_FOM, 126) AS skkto_giltig_fom,
		CONVERT(varchar(max), SKKTO_GILTIG_TOM, 126) AS skkto_giltig_tom,
		CAST(SKKTO_ID AS VARCHAR(MAX)) AS skkto_id,
		CAST(SKKTO_ID_TEXT AS VARCHAR(MAX)) AS skkto_id_text,
		CAST(SKKTO_PASSIV AS VARCHAR(MAX)) AS skkto_passiv,
		CAST(SKKTO_TEXT AS VARCHAR(MAX)) AS skkto_text,
		CONVERT(varchar(max), SRU2_GILTIG_FOM, 126) AS sru2_giltig_fom,
		CONVERT(varchar(max), SRU2_GILTIG_TOM, 126) AS sru2_giltig_tom,
		CAST(SRU2_ID AS VARCHAR(MAX)) AS sru2_id,
		CAST(SRU2_ID_TEXT AS VARCHAR(MAX)) AS sru2_id_text,
		CAST(SRU2_PASSIV AS VARCHAR(MAX)) AS sru2_passiv,
		CAST(SRU2_TEXT AS VARCHAR(MAX)) AS sru2_text,
		CONVERT(varchar(max), SRU_GILTIG_FOM, 126) AS sru_giltig_fom,
		CONVERT(varchar(max), SRU_GILTIG_TOM, 126) AS sru_giltig_tom,
		CAST(SRU_ID AS VARCHAR(MAX)) AS sru_id,
		CAST(SRU_ID_TEXT AS VARCHAR(MAX)) AS sru_id_text,
		CAST(SRU_PASSIV AS VARCHAR(MAX)) AS sru_passiv,
		CAST(SRU_TEXT AS VARCHAR(MAX)) AS sru_text,
		CONVERT(varchar(max), UPPH_GILTIG_FOM, 126) AS upph_giltig_fom,
		CONVERT(varchar(max), UPPH_GILTIG_TOM, 126) AS upph_giltig_tom,
		CAST(UPPH_ID AS VARCHAR(MAX)) AS upph_id,
		CAST(UPPH_ID_TEXT AS VARCHAR(MAX)) AS upph_id_text,
		CAST(UPPH_PASSIV AS VARCHAR(MAX)) AS upph_passiv,
		CAST(UPPH_TEXT AS VARCHAR(MAX)) AS upph_text,
		CONVERT(varchar(max), XB1_GILTIG_FOM, 126) AS xb1_giltig_fom,
		CONVERT(varchar(max), XB1_GILTIG_TOM, 126) AS xb1_giltig_tom,
		CAST(XB1_ID AS VARCHAR(MAX)) AS xb1_id,
		CAST(XB1_ID_TEXT AS VARCHAR(MAX)) AS xb1_id_text,
		CAST(XB1_PASSIV AS VARCHAR(MAX)) AS xb1_passiv,
		CAST(XB1_TEXT AS VARCHAR(MAX)) AS xb1_text,
		CONVERT(varchar(max), XB2_GILTIG_FOM, 126) AS xb2_giltig_fom,
		CONVERT(varchar(max), XB2_GILTIG_TOM, 126) AS xb2_giltig_tom,
		CAST(XB2_ID AS VARCHAR(MAX)) AS xb2_id,
		CAST(XB2_ID_TEXT AS VARCHAR(MAX)) AS xb2_id_text,
		CAST(XB2_PASSIV AS VARCHAR(MAX)) AS xb2_passiv,
		CAST(XB2_TEXT AS VARCHAR(MAX)) AS xb2_text,
		CONVERT(varchar(max), XDSRRK_GILTIG_FOM, 126) AS xdsrrk_giltig_fom,
		CONVERT(varchar(max), XDSRRK_GILTIG_TOM, 126) AS xdsrrk_giltig_tom,
		CAST(XDSRRK_ID AS VARCHAR(MAX)) AS xdsrrk_id,
		CAST(XDSRRK_ID_TEXT AS VARCHAR(MAX)) AS xdsrrk_id_text,
		CAST(XDSRRK_PASSIV AS VARCHAR(MAX)) AS xdsrrk_passiv,
		CAST(XDSRRK_TEXT AS VARCHAR(MAX)) AS xdsrrk_text,
		CONVERT(varchar(max), XDSRRL_GILTIG_FOM, 126) AS xdsrrl_giltig_fom,
		CONVERT(varchar(max), XDSRRL_GILTIG_TOM, 126) AS xdsrrl_giltig_tom,
		CAST(XDSRRL_ID AS VARCHAR(MAX)) AS xdsrrl_id,
		CAST(XDSRRL_ID_TEXT AS VARCHAR(MAX)) AS xdsrrl_id_text,
		CAST(XDSRRL_PASSIV AS VARCHAR(MAX)) AS xdsrrl_passiv,
		CAST(XDSRRL_TEXT AS VARCHAR(MAX)) AS xdsrrl_text,
		CONVERT(varchar(max), XKKTO2_GILTIG_FOM, 126) AS xkkto2_giltig_fom,
		CONVERT(varchar(max), XKKTO2_GILTIG_TOM, 126) AS xkkto2_giltig_tom,
		CAST(XKKTO2_ID AS VARCHAR(MAX)) AS xkkto2_id,
		CAST(XKKTO2_ID_TEXT AS VARCHAR(MAX)) AS xkkto2_id_text,
		CAST(XKKTO2_PASSIV AS VARCHAR(MAX)) AS xkkto2_passiv,
		CAST(XKKTO2_TEXT AS VARCHAR(MAX)) AS xkkto2_text,
		CONVERT(varchar(max), XKTO2_GILTIG_FOM, 126) AS xkto2_giltig_fom,
		CONVERT(varchar(max), XKTO2_GILTIG_TOM, 126) AS xkto2_giltig_tom,
		CAST(XKTO2_ID AS VARCHAR(MAX)) AS xkto2_id,
		CAST(XKTO2_ID_TEXT AS VARCHAR(MAX)) AS xkto2_id_text,
		CAST(XKTO2_PASSIV AS VARCHAR(MAX)) AS xkto2_passiv,
		CAST(XKTO2_TEXT AS VARCHAR(MAX)) AS xkto2_text,
		CONVERT(varchar(max), XXFRA1_GILTIG_FOM, 126) AS xxfra1_giltig_fom,
		CONVERT(varchar(max), XXFRA1_GILTIG_TOM, 126) AS xxfra1_giltig_tom,
		CAST(XXFRA1_ID AS VARCHAR(MAX)) AS xxfra1_id,
		CAST(XXFRA1_ID_TEXT AS VARCHAR(MAX)) AS xxfra1_id_text,
		CAST(XXFRA1_PASSIV AS VARCHAR(MAX)) AS xxfra1_passiv,
		CAST(XXFRA1_TEXT AS VARCHAR(MAX)) AS xxfra1_text,
		CONVERT(varchar(max), XXRA1I_GILTIG_FOM, 126) AS xxra1i_giltig_fom,
		CONVERT(varchar(max), XXRA1I_GILTIG_TOM, 126) AS xxra1i_giltig_tom,
		CAST(XXRA1I_ID AS VARCHAR(MAX)) AS xxra1i_id,
		CAST(XXRA1I_ID_TEXT AS VARCHAR(MAX)) AS xxra1i_id_text,
		CAST(XXRA1I_PASSIV AS VARCHAR(MAX)) AS xxra1i_passiv,
		CAST(XXRA1I_TEXT AS VARCHAR(MAX)) AS xxra1i_text 
	FROM raindance_udp.udp_150.EK_DIM_OBJ_KONTO ) y

	"""
    return read(query=query, server_url="dsp.rd.sll.se")
    