MODEL (
  column_descriptions (
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    active__slash__passive_status = 'Active / Passive Status',
    actual_number_of_delivery_days = 'Actual Number of Delivery Days',
    additioal_cost_form_2 = 'Additioal Cost Form 2',
    additioal_cost_value_2 = 'Additioal Cost Value 2',
    additional_cost_form_1 = 'Additional Cost Form 1',
    additional_cost_type_1 = 'Additional Cost Type 1',
    additional_cost_type_2 = 'Additional Cost Type 2',
    additional_cost_value_1 = 'Additional Cost Value 1',
    additional_description = 'Additional Description',
    additional_packaging__slash__unit_information = 'Additional Packaging / Unit Information',
    agreement_number = 'Agreement Number',
    agreement_valid_until_date = 'Agreement Valid Until Date',
    alternative_number_differentiates_conditions_for_same_item = 'Alternative Number: Differentiates Conditions for Same Item',
    auto_generate_purchase_orders_from_requirement_planning = 'Auto Generate Purchase Orders from Requirement Planning',
    company_identification_code = 'Company Identification Code',
    copy_description_to_order_line_comment = 'Copy Description to Order Line Comment',
    copy_text__slash__comment_to_order_line_comment = 'Copy Text / Comment to Order Line Comment',
    copy_text_to_work_order = 'Copy Text to Work Order',
    cost_price_markup_type_percent__slash__per_unit = 'Cost Price Markup Type (% / per unit)',
    cost_price_markup_value = 'Cost Price Markup Value',
    country_of_origin = 'Country of Origin',
    currency_identification_code = 'Currency Identification Code',
    current_price_last_changed_date = 'Current Price Last Changed Date',
    current_price_per_unit = 'Current Price per Unit',
    delivery_dates_last_changed_date = 'Delivery Dates Last Changed Date',
    deviation_percentage_entry_point_for_a_major_price_change = 'Deviation percentage entry point for a major price change',
    environment_class_or_classification = 'Environment Class or Classification',
    evaluate_agreement_at_date = 'Evaluate Agreement at Date',
    external_catalogue_type = 'External Catalogue Type',
    external_code_according_to_type = 'External Code According to Type',
    external_drawing_number_reference = 'External Drawing Number Reference',
    external_item_category = 'External Item Category',
    external_item_group = 'External Item Group',
    external_item_identification_code = 'External Item Identification Code',
    external_item_name__slash__description = 'External Item Name / Description',
    external_item_type = 'External Item Type',
    external_revision_number = 'External Revision Number',
    external_system_reference = 'External System Reference',
    external_type = 'External Type',
    general_text__slash__comments_to_item = 'General Text / Comments to Item',
    gross_area_in_m2 = 'Gross Area in m2',
    gross_weight_in_kg_per_unit = 'Gross Weight in kg per Unit',
    gross_volume_in_dm3_per_unit = 'Gross volume in dm3 per Unit',
    hide_from_search = 'Hide from Search',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information Created by User',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    internal_handling_time = 'Internal Handling Time',
    item_identification_code = 'Item Identification Code',
    item_make_sequence_number = 'Item Make Sequence Number',
    item_is_master_in_a_discount_matrix = 'Item is Master in a Discount Matrix',
    item_is_master_in_a_price_matrix = 'Item is Master in a Price Matrix',
    leadtime_for_ex_hyphen_works_terms_part_of_total_delivery_time = 'Leadtime for Ex-Works Terms: Part of Total Delivery Time',
    life_cycle_last_changed_date = 'Life Cycle Last Changed Date',
    life_cycle_last_changed_by_user = 'Life Cycle Last Changed by User',
    life_cycle_status_code = 'Life Cycle Status Code',
    manufacturer_item_code = 'Manufacturer Item Code',
    manufacturer_item_description = 'Manufacturer Item Description',
    manufacturer_name = 'Manufacturer Name',
    market_lead_time_often_used_when_no_delivery_days_agreement = 'Market Lead Time (often used when no delivery days agreement)',
    matrix_group_identification_code = 'Matrix Group Identification Code',
    maximum_deviation_of_delivery_days = 'Maximum Deviation of Delivery Days',
    maximum_number_of_delivery_days = 'Maximum Number of Delivery Days',
    maximum_ordering_quantity = 'Maximum Ordering Quantity',
    mean_average_deviation_of_delivery_days = 'Mean Average Deviation of Delivery Days',
    minimum_deviation_of_delivery_days = 'Minimum Deviation of Delivery Days',
    minimum_number_of_delivery_days = 'Minimum Number of Delivery Days',
    minimum_ordering_quantity = 'Minimum Ordering Quantity',
    net_area_in_m2 = 'Net Area in m2',
    net_volume_in_dm3_per_unit = 'Net Volume in dm3 per Unit',
    net_weight_in_kg_per_unit = 'Net Weight in Kg per Unit',
    new_price_valid_from_date = 'New Price Valid from Date',
    new_price_per_unit = 'New Price per Unit',
    oder_in_minimum_quantity_multiples = 'Oder in Minimum Quantity Multiples',
    owner_code_within_given_type = 'Owner Code Within given Type',
    owner_type = 'Owner Type',
    part_delivery_handling = 'Part Delivery Handling',
    price_per_a_number_of_units = 'Price Per a Number of Units',
    priority_number_differentiate_most_and_least_wanted_alternative = 'Priority Number: Differentiate Most and Least Wanted Alternative',
    recyclable_share_slash_part = 'Recyclable Share/Part',
    relation_ratio_to_base_unit = 'Relation Ratio to Base Unit',
    relation_type_to_base_unit = 'Relation Type to Base Unit',
    sequence_identification_number = 'Sequence Identification Number',
    standard_lead_time_in_days_including_transport__and__handling = 'Standard Lead Time in Days Including Transport & Handling',
    terms_of_delivery_identification_code = 'Terms of Delivery Identification Code',
    terms_of_payment_identification_code = 'Terms of Payment Identification Code',
    totale_quantity_on_agreement = 'Totale Quantity on Agreement',
    unit_identification_code = 'Unit Identification Code',
    use_forecast_order_on_this_item = 'Use Forecast Order on This Item',
    used_quantity_on_agreement = 'Used Quantity on Agreement',
    way_of_transport_identification_code = 'Way of Transport Identification Code'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  adcsf1 AS Additional_Cost_Form_1,
  adcsf2 AS Additioal_Cost_Form_2,
  adcst1 AS Additional_Cost_Type_1,
  adcst2 AS Additional_Cost_Type_2,
  adcsv1 AS Additional_Cost_Value_1,
  adcsv2 AS Additioal_Cost_Value_2,
  adddsc AS Additional_Description,
  ageval AS Evaluate_Agreement_at_Date,
  agporp AS Auto_Generate_Purchase_Orders_from_Requirement_Planning,
  agrnum AS Agreement_Number,
  agrqty AS Totale_Quantity_on_Agreement,
  agrusd AS Used_Quantity_on_Agreement,
  agvunt AS Agreement_Valid_Until_Date,
  altnum AS Alternative_Number_Differentiates_Conditions_for_Same_Item,
  cattyp AS External_Catalogue_Type,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  cntori AS Country_of_Origin,
  compny AS Company_Identification_Code,
  cprmut AS Cost_Price_Markup_Type_percent__slash__per_unit,
  cprmuv AS Cost_Price_Markup_Value,
  cptwor AS Copy_Text_to_Work_Order,
  cpypor AS Copy_Description_to_Order_Line_Comment,
  cpytxt AS Copy_Text__slash__Comment_to_Order_Line_Comment,
  credat AS Information_Created_Date,
  creusr AS Information_Created_by_User,
  curcod AS Currency_Identification_Code,
  curprc AS Current_Price_per_Unit,
  dldact AS Actual_Number_of_Delivery_Days,
  dlddat AS Delivery_Dates_Last_Changed_Date,
  dldmax AS Maximum_Number_of_Delivery_Days,
  dldmin AS Minimum_Number_of_Delivery_Days,
  dlvday AS Standard_Lead_Time_in_Days_Including_Transport__and__Handling,
  dppmpc AS Deviation_percentage_entry_point_for_a_major_price_change,
  dscmtx AS Item_is_Master_in_a_Discount_Matrix,
  eicact AS Active__slash__Passive_Status,
  eiclcs AS Life_Cycle_Status_Code,
  eictxt AS General_Text__slash__Comments_to_Item,
  envcls AS Environment_Class_or_Classification,
  extcod AS External_Code_According_to_Type,
  extdrw AS External_Drawing_Number_Reference,
  extict AS External_Item_Category,
  extigr AS External_Item_Group,
  extitm AS External_Item_Identification_Code,
  extity AS External_Item_Type,
  extnam AS External_Item_Name__slash__Description,
  extrra AS Relation_Ratio_to_Base_Unit,
  extrty AS Relation_Type_to_Base_Unit,
  extsys AS External_System_Reference,
  exttyp AS External_Type,
  extunt AS Unit_Identification_Code,
  exwldt AS Leadtime_for_Ex_hyphen_Works_Terms_Part_of_Total_Delivery_Time,
  grsam2 AS Gross_Area_in_m2,
  grsvdm AS Gross_volume_in_dm3_per_Unit,
  grswkg AS Gross_Weight_in_kg_per_Unit,
  hidsrc AS Hide_from_Search,
  inthnd AS Internal_Handling_Time,
  itkseq AS Item_Make_Sequence_Number,
  itmcod AS Item_Identification_Code,
  lcsdat AS Life_Cycle_Last_Changed_Date,
  lcsusr AS Life_Cycle_Last_Changed_by_User,
  maxddd AS Maximum_Deviation_of_Delivery_Days,
  maxqty AS Maximum_Ordering_Quantity,
  menddd AS Mean_Average_Deviation_of_Delivery_Days,
  minddd AS Minimum_Deviation_of_Delivery_Days,
  minqty AS Minimum_Ordering_Quantity,
  minunt AS Oder_in_Minimum_Quantity_Multiples,
  mrkldt AS Market_Lead_Time_often_used_when_no_delivery_days_agreement,
  mtxgrp AS Matrix_Group_Identification_Code,
  netam2 AS Net_Area_in_m2,
  netvdm AS Net_Volume_in_dm3_per_Unit,
  netwkg AS Net_Weight_in_Kg_per_Unit,
  newprc AS New_Price_per_Unit,
  owncod AS Owner_Code_Within_given_Type,
  owntyp AS Owner_Type,
  pdcitc AS Manufacturer_Item_Code,
  pdcitn AS Manufacturer_Item_Description,
  pdcnam AS Manufacturer_Name,
  prcdat AS Current_Price_Last_Changed_Date,
  prcmtx AS Item_is_Master_in_a_Price_Matrix,
  prcunt AS Price_Per_a_Number_of_Units,
  prinum AS Priority_Number_Differentiate_Most_and_Least_Wanted_Alternative,
  ptdlvm AS Part_Delivery_Handling,
  recycl AS Recyclable_Share_slash_Part,
  revnum AS External_Revision_Number,
  seqnum AS Sequence_Identification_Number,
  tdlcod AS Terms_of_Delivery_Identification_Code,
  tpycod AS Terms_of_Payment_Identification_Code,
  untinf AS Additional_Packaging__slash__Unit_Information,
  usefco AS Use_Forecast_Order_on_This_Item,
  valfrm AS New_Price_Valid_from_Date,
  wtrcod AS Way_of_Transport_Identification_Code
FROM clockwork_consolidated.rainbow_eic