MODEL (
  column_descriptions (
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    accumulated_load_all_levels = 'Accumulated load: all levels',
    accumulated_proddot_time_for_all_levels = 'Accumulated prod. time for all levels',
    accumulated_setup_time_all_levels = 'Accumulated setup time: all levels',
    activate_use_of_barcode_mode = 'Activate Use of Barcode Mode',
    active_slash_passive_status_for_the_item = 'Active/passive status for the item',
    additional_description = 'Additional Description',
    additional_packaging__slash__unit_information = 'Additional Packaging / Unit Information',
    additional_name_for_the_item = 'Additional name for the item',
    agent_hyphen_code_item_owner_or_salesperson = 'Agent-code (item owner or salesperson)',
    allow_return_of_material_for_product = 'Allow Return of Material for Product',
    allow_return_of_material_in_product = 'Allow Return of Material in Product',
    asset_type_identification_code = 'Asset Type Identification Code',
    base_unit_identification_code = 'Base unit identification code',
    billed_rental_of_product = 'Billed Rental of Product',
    breakdown_type_related_to_generating_a_workorder = 'Breakdown type related to generating a workorder',
    budget_unit_identification_code = 'Budget unit identification code',
    calculation_of_kit_costprice = 'Calculation of Kit Costprice',
    calculation_of_kit_salesprice = 'Calculation of Kit Salesprice',
    company__identification_code = 'Company  identification code',
    complete_name_slash_description_to_the_item = 'Complete name/description to the item',
    component_loss__slash__wreck_type = 'Component Loss / Wreck Type',
    component_loss__slash__wreck_value = 'Component Loss / Wreck Value',
    component_transfer_levels = 'Component Transfer Levels',
    consignment_stock = 'Consignment Stock',
    consuming_unit_identification_code = 'Consuming unit identification code',
    copy_item_comment_to_sales_order_line = 'Copy Item Comment To Sales Order Line',
    copy_item_comment_to_purchase_order_line = 'Copy Item Comment to Purchase Order Line',
    copy_item_comments_to_product_on_work_order = 'Copy Item Comments to Product on Work Order',
    cost_center_identification_code = 'Cost Center Identification Code',
    cost_value_level_code = 'Cost Value Level Code',
    costprice_model = 'Costprice model',
    country_of_origin = 'Country of origin',
    critical_item_for_delivery_date_calculation = 'Critical item for delivery date calculation',
    current_version_number = 'Current version number',
    customs_tariff_number_identification_code = 'Customs Tariff Number Identification Code',
    default_production_actual_lot__slash__batch_size = 'Default production actual lot / batch size',
    default_theoretical_production_lot_or_batch_size = 'Default: theoretical production lot or batch size',
    defines_if_this_item_is_a_master_slash_part_in_a_multipackedite = 'Defines if This Item is a Master/Part in a MultiPackedItem',
    defines_if_logistic_discount_is_in_usedot = 'Defines if logistic discount is in use.',
    defines_if_this_item_is_a_master_in_certificates_or_not = 'Defines if this Item is a Master in Certificates or not',
    defining_how_and_if_the_item_is_stocked = 'Defining how and if the item is stocked',
    detail_item_group_identification_code = 'Detail Item Group Identification Code',
    detail_unit_identification_code = 'Detail Unit Identification Code',
    drawing_identification_code = 'Drawing identification code',
    ear_hyphen_code_identification_code = 'EAR-Code Identification Code',
    entry_profile_code = 'Entry Profile Code',
    environment_class_or_classification = 'Environment Class or Classification',
    environment_text__slash__comment = 'Environment text / comment',
    exclude_item_on_external_documents = 'Exclude Item on External Documents',
    exclude_item_on_invoice_documents = 'Exclude Item on Invoice Documents',
    exclude_item_on_transport_documents = 'Exclude Item on Transport Documents',
    extended_infoormation_identification = 'Extended Infoormation Identification',
    external_item_type = 'External item type',
    factory_identifaction_code = 'Factory identifaction code',
    fixed_leadtime_for_item_independent_of_lotsiz = 'Fixed leadtime for item: independent of lotsiz',
    forecast_profile_identification_code = 'Forecast Profile Identification Code',
    formula_for_reporting_quantities_in_other_measures = 'Formula for reporting quantities in other measures',
    gtin_code_for_identifying_the_item_by_code = 'GTIN code for identifying the item by code',
    gtin_code_for_identifying_the_item_by_price = 'GTIN code for identifying the item by price',
    general_text__slash__comments = 'General text / comments',
    generate_component_transfer_request = 'Generate Component Transfer Request',
    generate_requisition_one_hyphen_to_hyphen_one = 'Generate Requisition One-to-One',
    hide_item_from_search_functions = 'Hide Item from Search Functions',
    hide_from_stock_view_slash_reports = 'Hide from Stock View/Reports',
    identifies_how_to_initiate_an_acquisition_of_an_item_when_neede = 'Identifies how to initiate an acquisition of an item when needed.',
    include_replacement_reference_for_consigned_item = 'Include Replacement Reference for Consigned Item',
    indicates_how_to_initiate_a_production_of_an_item_when_needed = 'Indicates how to initiate a production of an item when needed',
    indicates_if_consume_history_log__is_to_be_accumulated_or_not = 'Indicates if consume history log  is to be accumulated or not',
    indicates_if_production_history_log__is_to_be_accumulated_or_no = 'Indicates if production history log  is to be accumulated or not',
    indicates_if_purchase_history_log_is_to_be_accumulated_or_not = 'Indicates if purchase history log is to be accumulated or not',
    indicates_if_sales_history_log_is_to_be_accumulated_or_not = 'Indicates if sales history log is to be accumulated or not',
    indicates_if_this_item_is_master_in_a_bill_of_material__slash__ = 'Indicates if this item is master in a bill of material / receipt or not',
    indicates_if_this_item_is_master_in_a_kit_or_not = 'Indicates if this item is master in a kit or not',
    indicates_if_this_item_is_master_in_a_sparepart_list_or_not = 'Indicates if this item is master in a sparepart list or not',
    indicates_if_this_item_is_master_in_an_alternative_item_list_or = 'Indicates if this item is master in an alternative item list or not',
    individ_group_identification_code = 'Individ group identification code',
    information_created_date = 'Information Created Date',
    information_last_changed_date = 'Information Last Changed Date',
    information_created_by_user = 'Information created by user',
    information_last_changed_by_user = 'Information last changed by user',
    integration_reference_status = 'Integration Reference Status',
    itegration_date_status = 'Itegration Date Status',
    item_asset_information_model_identification_code = 'Item Asset Information Model Identification Code',
    item_colour_code = 'Item Colour Code',
    item_comments = 'Item Comments',
    item_entry_form = 'Item Entry Form',
    item_category_identification_code = 'Item category identification code',
    item_identification_code = 'Item identification code',
    item_typde_identification_code = 'Item typde identification code',
    keywords_for_search_purpose = 'Keywords for Search purpose',
    lifecycle_status_code = 'Lifecycle status code',
    logistics_group_identification_code = 'Logistics group identification code',
    loss_or_wreck_percentage = 'Loss or wreck percentage',
    lowlevel_code_changed_since_last_calculation_on_design_bom = 'Lowlevel code changed since last calculation on design BOM',
    lowlevel_code_changed_since_last_calculation_on_manufaturing_bo = 'Lowlevel code changed since last calculation on manufaturing BOM',
    lowlevel_code_from_last_calculation_for_design_bom = 'Lowlevel code from last calculation for design BOM',
    lowlevel_code_from_last_calculation_for_manufacturing_bom = 'Lowlevel code from last calculation for manufacturing BOM',
    main_customer_identification_code = 'Main Customer Identification Code',
    main_item_group_identification_code = 'Main Item Group identification code',
    manufacturer_name = 'Manufacturer Name',
    manufacturer_product_code = 'Manufacturer Product Code',
    manufacturer_product_name__slash__description = 'Manufacturer Product Name / Description',
    master_in_booking = 'Master in Booking',
    master_in_bulletin_board_system = 'Master in Bulletin Board System',
    master_in_coc__hyphen__certificate_of_conformity = 'Master in CoC - Certificate of Conformity',
    master_in_flag = 'Master in Flag',
    master_in_manufactured_quantity_deviation = 'Master in Manufactured Quantity Deviation',
    master_in_rationing_item_list = 'Master in Rationing Item List',
    master_in_remarks__slash__notes = 'Master in Remarks / Notes',
    master_in_rework_bill_of_material = 'Master in Rework Bill of Material',
    master_in_service_bill_of_material = 'Master in Service Bill of Material',
    master_in_variant_configuration = 'Master in Variant Configuration',
    master_in_a_dangerous_goods_classification = 'Master in a dangerous goods classification',
    master_in_a_replacement_listdot_valid_options_are_yes_or_no = 'Master in a replacement list. Valid options are YES or NO',
    master_in_a_variant_string = 'Master in a variant string',
    master_in_additional_purchase_item_list = 'Master in additional purchase item list',
    master_in_an_additional_sales_item_list = 'Master in an additional sales item list',
    master_in_item_make_catalogue = 'Master in item make catalogue',
    master_in_life_preservation_duration = 'Master in life preservation duration',
    master_in_lucratives_item_list = 'Master in lucratives item list',
    material_return_percentage = 'Material Return Percentage',
    material_usage_in_bill_hyphen_of_hyphen_material = 'Material Usage in Bill-of-Material',
    maximum_consuming_quantity = 'Maximum consuming quantity',
    maximum_purchase_quantity = 'Maximum purchase quantity',
    maximum_sales_quantity = 'Maximum sales quantity',
    minimum_consuming_quantity = 'Minimum consuming quantity',
    minimum_purchase_quantity = 'Minimum purchase quantity',
    minimum_sales_quantity = 'Minimum sales quantity',
    multi_element_discount_group = 'Multi Element Discount Group',
    picture_type = 'Picture type',
    planning_group_identification_code = 'Planning group identification code',
    previous_production_order_link_control = 'Previous Production Order Link Control',
    procurement_control_how_to_obtain_the_item = 'Procurement Control; How to Obtain the Item',
    procurement_product_selection_slash_range_restriction = 'Procurement Product Selection/Range Restriction',
    product_family_identification_code = 'Product Family Identification Code',
    product_model_identification_code = 'Product Model Identification Code',
    product_range_identification_code = 'Product Range Identification Code',
    product_calculation_group_identification_code = 'Product calculation group identification code',
    product_group_identification_code = 'Product group identification code',
    product_information_model_identification_code = 'Product information model identification code',
    product_manager_identification_code = 'Product manager identification code',
    production_demand_calculation_method = 'Production demand calculation method',
    production_planner_identification_code = 'Production planner identification code',
    production_time_in_hours = 'Production time in hours',
    purchase_budget_account_number = 'Purchase budget account number',
    purchase_unit_identification_code = 'Purchase unit identification code',
    purchaser_identification_code = 'Purchaser identification code',
    quality_manager_role = 'Quality Manager Role',
    quality_assurance_control_model_identification_code = 'Quality assurance control model identification code',
    recyclable_share_slash_part = 'Recyclable share/part',
    reference_to_external_item_number = 'Reference to external item number',
    refers_to_a_datasheet_model_where_the_individual_specifications = 'Refers to a Datasheet model where the individual specifications for this Item can be found',
    refers_to_a_bitmapfile_where_a_picture_of_thee_item_is_storeddo = 'Refers to a bitmapfile where a picture of thee item is stored.',
    relation_ratio_from_budget_unit_to_base_unit = 'Relation Ratio from Budget Unit to Base Unit',
    relation_ratio_from_detail_unit_to_base_unit = 'Relation Ratio from Detail Unit to Base Unit',
    relation_ratio_from_purchase_unit_to_base_unit = 'Relation Ratio from Purchase Unit to Base Unit',
    relation_ratio_from_sales_unit_to_base_unit = 'Relation Ratio from Sales Unit to Base Unit',
    relation_ratio_from__consuming_unit_to_base_unit = 'Relation Ratio from  Consuming Unit to Base Unit',
    relation_type_from_budget_unit_to_base_unit = 'Relation Type from Budget Unit to Base Unit',
    relation_type_from_consuming_unit_to_base_unit = 'Relation Type from Consuming Unit to Base Unit',
    relation_type_from_detail_unit_to_base_unit = 'Relation Type from Detail Unit to Base Unit',
    relation_type_from_purchase_unit_to_base_unit = 'Relation Type from Purchase Unit to Base Unit',
    relation_type_from_sales_unit_to_base_unit = 'Relation Type from Sales Unit to Base Unit',
    rule_for_handling_overide_of_maximum_sales_quantitydot = 'Rule for handling overide of maximum sales quantity.',
    rule_for_handling_override_of_maximum_consuming_quantitydot = 'Rule for handling override of maximum consuming quantity.',
    rule_for_handling_override_of_maximum_purchase_quantitydot = 'Rule for handling override of maximum purchase quantity.',
    sales_price_model_defining_standard_or_recommended_price = 'Sales Price Model defining Standard or Recommended Price',
    sales_resupply = 'Sales resupply',
    sales_unit_identification_code = 'Sales unit identification code',
    seller__slash__salesperson_identification_code = 'Seller / Salesperson identification code',
    set_hyphen_up_time_in_hours = 'Set-up time in hours',
    shortname = 'Shortname',
    shortnumber = 'Shortnumber',
    special_treatment = 'Special treatment',
    standard_production_deviation_handling = 'Standard Production Deviation Handling',
    standard_production_deviation_type = 'Standard Production Deviation Type',
    standard_report_deviation = 'Standard Report Deviation',
    standard_report_quantity = 'Standard Report Quantity',
    stock_slash_general_resupply_control = 'Stock/General Resupply Control',
    sub_item_group_identification_code = 'Sub Item Group identification code',
    supplier_identification_code_for_main_supplier = 'Supplier identification code for main supplier',
    tax_group_identification_code = 'Tax group identification code',
    taxation_base_type = 'Taxation Base Type',
    taxation_reference_value_related_to_tax_base = 'Taxation Reference Value related to Tax Base',
    the_date_when_the_life_cycle_last_was_changed = 'The date when the life cycle last was changed',
    the_user_that_last_changed_the_life_cycle = 'The user that last changed the life cycle',
    theoretical_lot_slash_batch_sizedot = 'Theoretical lot/batch size.',
    type_of_loss_or_wreck_related_to_production = 'Type of loss or wreck related to production',
    variant_configuration_group_identification_code = 'Variant Configuration Group Identification Code',
    variant_group_identification_code = 'Variant group identification code',
    video_file_type = 'Video file type',
    video_filename_reference = 'Video filename reference',
    warehouse_identification_code_for_main_warehouse = 'Warehouse identification code for main warehouse',
    work_order_resupply_control = 'Work Order Resupply Control',
    clclot = 'No description found in source docs.',
    scpunt = 'No description found in source docs.'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  accloa AS Accumulated_load_all_levels,
  accnsh AS Indicates_if_consume_history_log__is_to_be_accumulated_or_not,
  accprd AS Accumulated_proddot_time_for_all_levels,
  accset AS Accumulated_setup_time_all_levels,
  acpdch AS Indicates_if_production_history_log__is_to_be_accumulated_or_no,
  acprch AS Indicates_if_purchase_history_log_is_to_be_accumulated_or_not,
  acsalh AS Indicates_if_sales_history_log_is_to_be_accumulated_or_not,
  actlot AS Default_production_actual_lot__slash__batch_size,
  adddsc AS Additional_Description,
  agncod AS Agent_hyphen_code_item_owner_or_salesperson,
  aitmnm AS Additional_name_for_the_item,
  aprctr AS Procurement_Product_Selection_slash_Range_Restriction,
  asmmdl AS Item_Asset_Information_Model_Identification_Code,
  astcod AS Asset_Type_Identification_Code,
  ausctr AS Identifies_how_to_initiate_an_acquisition_of_an_item_when_neede,
  basunt AS Base_unit_identification_code,
  bilmat AS Indicates_if_this_item_is_master_in_a_bill_of_material__slash__,
  bilrtl AS Billed_Rental_of_Product,
  brkdwn AS Breakdown_type_related_to_generating_a_workorder,
  budunt AS Budget_unit_identification_code,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_last_changed_by_user,
  cmplwt AS Component_Loss__slash__Wreck_Type,
  cmplwv AS Component_Loss__slash__Wreck_Value,
  cnsgnd AS Consignment_Stock,
  cnsref AS Include_Replacement_Reference_for_Consigned_Item,
  cnsunt AS Consuming_unit_identification_code,
  cntori AS Country_of_origin,
  compny AS Company__identification_code,
  cpcopo AS Copy_Item_Comment_to_Purchase_Order_Line,
  cpcoso AS Copy_Item_Comment_To_Sales_Order_Line,
  cpcowo AS Copy_Item_Comments_to_Product_on_Work_Order,
  cprmod AS Costprice_model,
  credat AS Information_Created_Date,
  creusr AS Information_created_by_user,
  criitm AS Critical_item_for_delivery_date_calculation,
  csccod AS Cost_Center_Identification_Code,
  cstcod AS Customs_Tariff_Number_Identification_Code,
  ctrgen AS Generate_Component_Transfer_Request,
  ctrlvl AS Component_Transfer_Levels,
  cuscod AS Main_Customer_Identification_Code,
  cvlcod AS Cost_Value_Level_Code,
  digcod AS Detail_Item_Group_Identification_Code,
  drwcod AS Drawing_identification_code,
  dtlunt AS Detail_Unit_Identification_Code,
  dtscod AS Refers_to_a_Datasheet_model_where_the_individual_specifications,
  eanitm AS GTIN_code_for_identifying_the_item_by_code,
  eanprc AS GTIN_code_for_identifying_the_item_by_price,
  earcod AS EAR_hyphen_Code_Identification_Code,
  entfrm AS Item_Entry_Form,
  envcls AS Environment_Class_or_Classification,
  eprcod AS Extended_Infoormation_Identification,
  excexd AS Exclude_Item_on_External_Documents,
  excivd AS Exclude_Item_on_Invoice_Documents,
  exctrd AS Exclude_Item_on_Transport_Documents,
  extnum AS Reference_to_external_item_number,
  exttyp AS External_item_type,
  fcpcod AS Forecast_Profile_Identification_Code,
  fctcod AS Factory_identifaction_code,
  fixtim AS Fixed_leadtime_for_item_independent_of_lotsiz,
  hidsrc AS Hide_Item_from_Search_Functions,
  hidstc AS Hide_from_Stock_View_slash_Reports,
  icccod AS Item_Colour_Code,
  ictcod AS Item_category_identification_code,
  idgcod AS Individ_group_identification_code,
  infmod AS infmod,
  itgdat AS Itegration_Date_Status,
  itgref AS Integration_Reference_Status,
  itmact AS Active_slash_passive_status_for_the_item,
  itmcod AS Item_identification_code,
  itmlcs AS Lifecycle_status_code,
  itmnam AS Complete_name_slash_description_to_the_item,
  itycod AS Item_typde_identification_code,
  keywds AS Keywords_for_Search_purpose,
  lcsdat AS The_date_when_the_life_cycle_last_was_changed,
  lcsusr AS The_user_that_last_changed_the_life_cycle,
  llcchd AS Lowlevel_code_changed_since_last_calculation_on_design_BOM,
  llcchg AS Lowlevel_code_changed_since_last_calculation_on_manufaturing_BO,
  llcdes AS Lowlevel_code_from_last_calculation_for_design_BOM,
  llcode AS Lowlevel_code_from_last_calculation_for_manufacturing_BOM,
  logcod AS Logistics_group_identification_code,
  logdsc AS Defines_if_logistic_discount_is_in_usedot,
  lotsiz AS Default_theoretical_production_lot_or_batch_size,
  lsswrc AS Loss_or_wreck_percentage,
  lwvtyp AS Type_of_loss_or_wreck_related_to_production,
  macofh AS Rule_for_handling_override_of_maximum_consuming_quantitydot,
  macqty AS Maximum_consuming_quantity,
  mapofh AS Rule_for_handling_override_of_maximum_purchase_quantitydot,
  mapqty AS Maximum_purchase_quantity,
  martpc AS Material_Return_Percentage,
  masofh AS Rule_for_handling_overide_of_maximum_sales_quantitydot,
  masqty AS Maximum_sales_quantity,
  matret AS Allow_Return_of_Material_in_Product,
  matuse AS Material_Usage_in_Bill_hyphen_of_hyphen_Material,
  medgrp AS Multi_Element_Discount_Group,
  micqty AS Minimum_consuming_quantity,
  migcod AS Main_Item_Group_identification_code,
  mipqty AS Minimum_purchase_quantity,
  misqty AS Minimum_sales_quantity,
  mstadd AS Master_in_an_additional_sales_item_list,
  mstadp AS Master_in_additional_purchase_item_list,
  mstalt AS Indicates_if_this_item_is_master_in_an_alternative_item_list_or,
  mstbbs AS Master_in_Bulletin_Board_System,
  mstbok AS Master_in_Booking,
  mstcoc AS Master_in_CoC__hyphen__Certificate_of_Conformity,
  mstctf AS Defines_if_this_Item_is_a_Master_in_Certificates_or_not,
  mstdgc AS Master_in_a_dangerous_goods_classification,
  mstflg AS Master_in_Flag,
  mstitk AS Master_in_item_make_catalogue,
  mstlcr AS Master_in_lucratives_item_list,
  mstlpd AS Master_in_life_preservation_duration,
  mstmpi AS Defines_if_This_Item_is_a_Master_slash_Part_in_a_MultiPackedIte,
  mstmqd AS Master_in_Manufactured_Quantity_Deviation,
  mstmrk AS Master_in_Remarks__slash__Notes,
  mstrat AS Master_in_Rationing_Item_List,
  mstrpc AS Master_in_a_replacement_listdot_Valid_options_are_YES_or_NO,
  mstrwk AS Master_in_Rework_Bill_of_Material,
  mstsvc AS Master_in_Service_Bill_of_Material,
  mstvar AS Master_in_a_variant_string,
  mstvrc AS Master_in_Variant_Configuration,
  otomrq AS Generate_Requisition_One_hyphen_to_hyphen_One,
  pcgcod AS Product_calculation_group_identification_code,
  pckitc AS Calculation_of_Kit_Costprice,
  pckits AS Calculation_of_Kit_Salesprice,
  pdcctr AS Indicates_how_to_initiate_a_production_of_an_item_when_needed,
  pdcitc AS Manufacturer_Product_Code,
  pdcitn AS Manufacturer_Product_Name__slash__Description,
  pdcnam AS Manufacturer_Name,
  pfmcod AS Product_Family_Identification_Code,
  pgrcod AS Product_group_identification_code,
  picfil AS Refers_to_a_bitmapfile_where_a_picture_of_thee_item_is_storeddo,
  pictyp AS Picture_type,
  pinmod AS Product_information_model_identification_code,
  plgcod AS Planning_group_identification_code,
  pmdcod AS Product_Model_Identification_Code,
  pmgcod AS Product_manager_identification_code,
  pplcod AS Production_planner_identification_code,
  pprctr AS Previous_Production_Order_Link_Control,
  prbuac AS Purchase_budget_account_number,
  prccod AS Purchaser_identification_code,
  prcctr AS Procurement_Control_How_to_Obtain_the_Item,
  prcunt AS Purchase_unit_identification_code,
  prddmd AS Production_demand_calculation_method,
  prdret AS Allow_Return_of_Material_for_Product,
  prdtim AS Production_time_in_hours,
  prfcod AS Entry_Profile_Code,
  prncod AS Product_Range_Identification_Code,
  qamcod AS Quality_assurance_control_model_identification_code,
  qlmcod AS Quality_Manager_Role,
  qtyfml AS Formula_for_reporting_quantities_in_other_measures,
  recycl AS Recyclable_share_slash_part,
  rrbbud AS Relation_Ratio_from_Budget_Unit_to_Base_Unit,
  rrbcns AS Relation_Ratio_from__Consuming_Unit_to_Base_Unit,
  rrbdtl AS Relation_Ratio_from_Detail_Unit_to_Base_Unit,
  rrbprc AS Relation_Ratio_from_Purchase_Unit_to_Base_Unit,
  rrbsal AS Relation_Ratio_from_Sales_Unit_to_Base_Unit,
  rtbbud AS Relation_Type_from_Budget_Unit_to_Base_Unit,
  rtbcns AS Relation_Type_from_Consuming_Unit_to_Base_Unit,
  rtbdtl AS Relation_Type_from_Detail_Unit_to_Base_Unit,
  rtbprc AS Relation_Type_from_Purchase_Unit_to_Base_Unit,
  rtbsal AS Relation_Type_from_Sales_Unit_to_Base_Unit,
  salkit AS Indicates_if_this_item_is_master_in_a_kit_or_not,
  salrsp AS Sales_resupply,
  salunt AS Sales_unit_identification_code,
  sapcod AS Seller__slash__Salesperson_identification_code,
  settim AS Set_hyphen_up_time_in_hours,
  sigcod AS Sub_Item_Group_identification_code,
  spctrt AS Special_treatment,
  sprkit AS Indicates_if_this_item_is_master_in_a_sparepart_list_or_not,
  sprmod AS Sales_Price_Model_defining_Standard_or_Recommended_Price,
  srtnam AS Shortname,
  srtnum AS Shortnumber,
  stcrsp AS Stock_slash_General_Resupply_Control,
  sthctr AS Defining_how_and_if_the_item_is_stocked,
  strpdh AS Standard_Production_Deviation_Handling,
  strpdt AS Standard_Production_Deviation_Type,
  strpdv AS Standard_Report_Deviation,
  strpqt AS Standard_Report_Quantity,
  supcod AS Supplier_identification_code_for_main_supplier,
  taxbas AS Taxation_Base_Type,
  taxcod AS Taxation_Reference_Value_related_to_Tax_Base,
  thelot AS Theoretical_lot_slash_batch_sizedot,
  txgcod AS Tax_group_identification_code,
  txtenv AS Environment_text__slash__comment,
  txtgen AS General_text__slash__comments,
  txtitm AS Item_Comments,
  untinf AS Additional_Packaging__slash__Unit_Information,
  usebcm AS Activate_Use_of_Barcode_Mode,
  vargrp AS Variant_group_identification_code,
  vcgcod AS Variant_Configuration_Group_Identification_Code,
  vernum AS Current_version_number,
  vidfil AS Video_filename_reference,
  vidtyp AS Video_file_type,
  whscod AS Warehouse_identification_code_for_main_warehouse,
  worrsp AS Work_Order_Resupply_Control
FROM clockwork_consolidated.rainbow_itm