MODEL (
  column_descriptions (
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    additional_text__slash__description = 'Additional Text / Description',
    classification_code = 'Classification Code',
    classification_level = 'Classification Level',
    classification_name_slash_description = 'Classification Name/Description',
    company_identification_code = 'Company Identification Code',
    detailed_item_group_identification_code = 'Detailed Item Group Identification Code',
    general_comments = 'General Comments',
    hide_item_classification_code_from_search = 'Hide Item Classification Code from Search',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information Created by User',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    item_categorization_catalogue_identification_code = 'Item Categorization Catalogue Identification Code',
    item_classification_catalogue_identification_code = 'Item Classification Catalogue Identification Code',
    item_classification_reference_code_in_catalogue = 'Item Classification Reference Code in Catalogue',
    lined_up_categorization_reference = 'Lined up Categorization Reference',
    main_item_group_identification_code = 'Main Item Group Identification Code',
    mapped__and__lined_up_classification = 'Mapped & Lined up Classification',
    order_form_identification_code = 'Order Form Identification Code',
    parent_sequence_number = 'Parent Sequence Number',
    purchase_budget_account_identification_code = 'Purchase Budget Account Identification Code',
    sequence_number = 'Sequence Number',
    sub_item_group_identification_code = 'Sub Item Group Identification Code'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  compny AS Company_Identification_Code,
  credat AS Information_Created_Date,
  creusr AS Information_Created_by_User,
  digcod AS Detailed_Item_Group_Identification_Code,
  gencom AS General_Comments,
  hidsrc AS Hide_Item_Classification_Code_from_Search,
  icscat AS Item_Classification_Catalogue_Identification_Code,
  icscod AS Classification_Code,
  icsmap AS Mapped__and__Lined_up_Classification,
  icsnam AS Classification_Name_slash_Description,
  icsref AS Item_Classification_Reference_Code_in_Catalogue,
  ikscat AS Item_Categorization_Catalogue_Identification_Code,
  iksref AS Lined_up_Categorization_Reference,
  lvlcod AS Classification_Level,
  migcod AS Main_Item_Group_Identification_Code,
  ofmcod AS Order_Form_Identification_Code,
  parseq AS Parent_Sequence_Number,
  prbuac AS Purchase_Budget_Account_Identification_Code,
  seqnum AS Sequence_Number,
  sigcod AS Sub_Item_Group_Identification_Code,
  txtdsc AS Additional_Text__slash__Description
FROM clockwork_consolidated.rainbow_icscat