MODEL (
  column_descriptions (
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    active_slash_passive_status_code = 'Active/Passive Status Code',
    additional_text__slash__description = 'Additional Text / Description',
    alternative_code_for_object_code = 'Alternative Code for Object Code',
    company_identification_code = 'Company identification code',
    general_alternative_1dot_usage_depening_on_object_type = 'General Alternative 1. Usage depening on Object Type',
    general_alternative_2dot_usage_depening_on_object_type = 'General Alternative 2. Usage depening on Object Type',
    general_comments = 'General Comments',
    general_numeric_value_1dot_usage_depening_on_object_type = 'General Numeric Value 1. Usage depening on Object Type',
    general_numeric_value_2dot_usage_depening_on_object_type = 'General Numeric Value 2. Usage depening on Object Type',
    general_percentage_value_1dot_usage_depening_on_object_type = 'General Percentage Value 1. Usage depening on Object Type',
    general_text_value_1dot_usage_depening_on_object_type = 'General Text Value 1. Usage depening on Object Type',
    general_text_value_2dot_usage_depening_on_object_type = 'General Text Value 2. Usage depening on Object Type',
    general_text_value_4dot_usage_depening_on_object_type = 'General Text Value 4. Usage depening on Object Type',
    general_text__slash__comment_1dot_usage_depening_on_object_type = 'General Text / Comment 1. Usage depening on Object Type',
    hide_object_from_search = 'Hide object from Search',
    iso_code_for_object = 'ISO Code for Object',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information Created by User',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    information_model_identification_code = 'Information Model Identification Code',
    object_code_in_external_system = 'Object Code in External System',
    object_identification_code = 'Object Identification Code',
    object_name__slash__description = 'Object Name / Description',
    object_type = 'Object Type',
    short_name = 'Short Name',
    short_number = 'Short Number',
    valid_from_date = 'Valid from Date',
    valid_until_date = 'Valid until Date'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  actpas AS Active_slash_Passive_Status_Code,
  altcod AS Alternative_Code_for_Object_Code,
  altr01 AS General_Alternative_1dot_Usage_depening_on_Object_Type,
  altr02 AS General_Alternative_2dot_Usage_depening_on_Object_Type,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  compny AS Company_identification_code,
  credat AS Information_Created_Date,
  creusr AS Information_Created_by_User,
  extcod AS Object_Code_in_External_System,
  gencom AS General_Comments,
  hidsrc AS Hide_object_from_Search,
  infmdl AS Information_Model_Identification_Code,
  isocod AS ISO_Code_for_Object,
  namdes AS Object_Name__slash__Description,
  objcod AS Object_Identification_Code,
  objn01 AS General_Numeric_Value_1dot_Usage_depening_on_Object_Type,
  objn02 AS General_Numeric_Value_2dot_Usage_depening_on_Object_Type,
  objp01 AS General_Percentage_Value_1dot_Usage_depening_on_Object_Type,
  objt01 AS General_Text_Value_1dot_Usage_depening_on_Object_Type,
  objt02 AS General_Text_Value_2dot_Usage_depening_on_Object_Type,
  objt04 AS General_Text_Value_4dot_Usage_depening_on_Object_Type,
  objtyp AS Object_Type,
  srtnam AS Short_Name,
  srtnum AS Short_Number,
  text01 AS General_Text__slash__Comment_1dot_Usage_depening_on_Object_Type,
  txtdsc AS Additional_Text__slash__Description,
  valfrm AS Valid_from_Date,
  valunt AS Valid_until_Date
FROM clockwork_consolidated.rainbow_obj