MODEL (
  column_descriptions (
    _invoice_log_level = ' Invoice Log Level',
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    activate_and_use_learning_curve = 'Activate and Use Learning Curve',
    allow_material_adjustment_when_ordertraces_cost_is_enabled = 'Allow Material Adjustment when Ordertraces Cost is Enabled',
    allow_multiple_replacements_of_items = 'Allow Multiple Replacements of Items',
    annual_settlement_until = 'Annual Settlement Until',
    automatic_generation_og_item_index_catalogue_by_level = 'Automatic Generation og Item Index Catalogue by Level',
    cad_program_type = 'CAD Program Type',
    cwp_search_option = 'CWP Search Option',
    classificaton_level_in_warrant_structure = 'Classificaton Level in Warrant Structure',
    colour_set_table = 'Colour Set Table',
    common_terms_for_transaction_owners = 'Common Terms for Transaction Owners',
    company_identification_code = 'Company Identification Code',
    company_name__slash__description = 'Company Name / Description',
    constant_1_in_learning_curve = 'Constant 1 in Learning Curve',
    constant_2_in_learning_curve = 'Constant 2 in Learning Curve',
    constant_3_in_learning_curve = 'Constant 3 in Learning Curve',
    contact_person = 'Contact Person',
    corporate_master_og_corporate_slave_company = 'Corporate Master og Corporate Slave Company',
    country_identification_code = 'Country Identification Code',
    credit_control_linked_to_level = 'Credit Control Linked to Level',
    currenct_set_for_budget_exchange_rate = 'Currenct Set for Budget Exchange Rate',
    currenct_set_for_current_exchange_rate = 'Currenct Set for Current Exchange Rate',
    currenct_set_for_fixed_exchange_rate = 'Currenct Set for Fixed Exchange Rate',
    currency_identification_code = 'Currency Identification Code',
    default_claims_order_type = 'Default Claims Order Type',
    default_credit_invoice_group = 'Default Credit Invoice Group',
    default_directory_for_data_received_from_cad_hyphen_host = 'Default Directory for Data Received from CAD-Host',
    default_directory_for_data_send_to_cad_hyphen_host = 'Default Directory for Data Send to CAD-host',
    default_item_classification_system_catalogue = 'Default Item Classification System Catalogue',
    default_manufacturing_order_type = 'Default Manufacturing Order Type',
    default_master_loading_unit_in_shipment = 'Default Master Loading Unit in Shipment',
    default_purchase_order_type = 'Default Purchase Order Type',
    default_qac_warehouse_identification_code = 'Default QAC Warehouse Identification Code',
    default_sales_order_type = 'Default Sales Order Type',
    default_service_department_code_for_cw_service_modue = 'Default Service Department Code for CW Service Modue',
    default_sub_loading_unit_in_shipment = 'Default Sub Loading Unit in Shipment',
    default_warehouse_identification_code = 'Default Warehouse Identification Code',
    defines_i_standard_makes_is_used_or_not = 'Defines i Standard Makes is used or not',
    definition_of_where_to_find_default_user_menu = 'Definition of Where to find Default User Menu',
    delivery_address_line_1 = 'Delivery Address: Line 1',
    delivery_address_line_2 = 'Delivery Address: Line 2',
    delivery_address_line_3 = 'Delivery Address: Line 3',
    delivery_address_line_4 = 'Delivery Address: Line 4',
    display_owner_item_info_on_purchase_invoice = 'Display owner item info on purchase invoice',
    document_storage_form = 'Document Storage Form',
    eori__hyphen__economic_operators_registration_and_identificatio = 'EORI - Economic Operators Registration and Identification Number',
    edit_e_hyphen_mail_before_sending = 'Edit e-mail before sending',
    enable_supplier_sourcing_by_stock_catalogue = 'Enable Supplier Sourcing by Stock Catalogue',
    end_user_payer_level = 'End User Payer Level',
    end_user_to_customer_entry_profile = 'End User to Customer Entry Profile',
    european_community_country_code = 'European Community Country Code',
    factory_identification_code = 'Factory Identification Code',
    fiscal_year_offset_in_months = 'Fiscal Year Offset in Months',
    font_set_table = 'Font Set Table',
    gateway_identification_code = 'Gateway Identification Code',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information Created by User',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    invoice_control_organisation_level = 'Invoice Control Organisation Level',
    invoice_control_value_level_hit = 'Invoice Control Value Level Hit',
    job_queue_identification = 'Job Queue Identification',
    language_identification_code = 'Language Identification Code',
    learning_curve_higher_time_limit = 'Learning Curve Higher Time Limit',
    learning_curve_lower_time_limit = 'Learning Curve Lower Time Limit',
    mcp_calculation_currency_exchange_rate_type = 'MCP Calculation Currency Exchange Rate Type',
    mailing__slash__postal_address_line_1 = 'Mailing / Postal Address: Line 1',
    mailing__slash__postal_address_line_2 = 'Mailing / Postal Address: Line 2',
    mailing__slash__postal_address_line_3 = 'Mailing / Postal Address: Line 3',
    mailing__slash__postal_address_line_4 = 'Mailing / Postal Address: Line 4',
    make_library_level_identification = 'Make Library Level Identification',
    mapping_to_extended_information_on_standard_makes = 'Mapping to Extended Information on Standard Makes',
    master_plan_identification_code = 'Master Plan Identification Code',
    masterplan_period_length = 'Masterplan Period Length',
    menu_picture_name_for_desktop = 'Menu Picture Name for DeskTop',
    merge_production_proposales = 'Merge Production Proposales',
    number_of_digits_in_arrival_transaction_number = 'Number of Digits in Arrival Transaction Number',
    number_of_digits_in_disassembly_order_number = 'Number of Digits in Disassembly Order Number',
    number_of_digits_in_external_order_transaction_number = 'Number of Digits in External Order Transaction Number',
    number_of_digits_in_frame_agreement_number = 'Number of Digits in Frame Agreement Number',
    number_of_digits_in_gateway_entry = 'Number of Digits in Gateway Entry',
    number_of_digits_in_internal_distribution_order = 'Number of Digits in Internal Distribution Order',
    number_of_digits_in_internal_order_transaction_number = 'Number of Digits in Internal Order Transaction Number',
    number_of_digits_in_picking_list = 'Number of Digits in Picking List',
    number_of_digits_in_place_list = 'Number of Digits in Place List',
    number_of_digits_in_purchase_order_number = 'Number of Digits in Purchase Order Number',
    number_of_digits_in_purchase_request_number = 'Number of Digits in Purchase Request Number',
    number_of_digits_in_quality_assurance_control = 'Number of Digits in Quality Assurance Control',
    number_of_digits_in_replenishment_number = 'Number of Digits in Replenishment Number',
    number_of_digits_in_reqdot_planning_number = 'Number of Digits in Req. Planning Number',
    number_of_digits_in_requirement_transaction_number = 'Number of Digits in Requirement Transaction Number',
    number_of_digits_in_sales_order = 'Number of Digits in Sales Order',
    number_of_digits_in_shipment_number = 'Number of Digits in Shipment Number',
    number_of_digits_in_stock_transfer = 'Number of Digits in Stock Transfer',
    number_of_digits_in_workorder_number = 'Number of Digits in Workorder Number',
    number_of_levels_to_be_displayed_in_a_bill_of_material = 'Number of Levels to be Displayed in a Bill of Material',
    number_of_ddgits_in_stocktake_transaction_number = 'Number of dDgits in Stocktake Transaction Number',
    number_of_digits_in_accounting_journal_number = 'Number of digits in Accounting Journal Number',
    numbere_of_digits_in_inbound_invoice_number = 'Numbere of Digits in Inbound Invoice Number',
    numbere_of_digits_in_outbound_invoice_number = 'Numbere of Digits in Outbound Invoice Number',
    organisation_level_in_spend_control = 'Organisation Level in Spend Control',
    organisation_level_in_warrant_structure = 'Organisation Level in Warrant Structure',
    organization_or_registration_number = 'Organization or Registration Number',
    our_client_code_at_factoring_company = 'Our Client Code at Factoring Company',
    path_to_drawing_directory_or_catalogue = 'Path to Drawing Directory or Catalogue',
    path_to_export_directory_or_catalogue = 'Path to Export Directory or Catalogue',
    path_to_import_directory_or_catallogue = 'Path to Import Directory or Catallogue',
    path_to_picture_directory_or_catalogue = 'Path to Picture Directory or Catalogue',
    path_to_scratch_directory_or_catalogue = 'Path to Scratch Directory or Catalogue',
    path_to_text_directory_or_catalouge = 'Path to Text Directory or Catalouge',
    posting_information_of_sales_transactions_last_changed_date = 'Posting Information of Sales Transactions Last Changed Date',
    posting_of_purchase_order_transactions = 'Posting of Purchase Order Transactions',
    posting_of_purchase_transactions_last_changed_date = 'Posting of Purchase Transactions Last Changed Date',
    posting_of_sales_order_transactions = 'Posting of Sales Order Transactions',
    posting_of_stock_transactions = 'Posting of Stock Transactions',
    posting_of_stock_transactions_last_changed_date = 'Posting of Stock Transactions Last Changed Date',
    posting_of_work_order_transactions = 'Posting of Work Order Transactions',
    posting_of_work_transaction_last_changed_date = 'Posting of Work Transaction Last Changed Date',
    prefix_accounting_journal_number = 'Prefix: Accounting Journal Number',
    prefix_shipment_number = 'Prefix: Shipment Number',
    prefix_in_frame_agreement_number_related_to_customer = 'Prefix in Frame Agreement Number related to Customer',
    prefix_in_frame_agreement_number_related_to_supplier = 'Prefix in Frame Agreement Number related to Supplier',
    prefix_in_inbound_invoice_number = 'Prefix in Inbound Invoice Number',
    prefix_in_outbound_invoice_number = 'Prefix in Outbound Invoice Number',
    prefix_in_replenishment_number = 'Prefix in Replenishment Number',
    prefix_in_serial_number_for_disassembly_order = 'Prefix in Serial Number for Disassembly Order',
    prefix_in_serial_number_for_gateway_entry = 'Prefix in Serial Number for Gateway Entry',
    prefix_in_serial_number_for_internal_orders = 'Prefix in Serial Number for Internal Orders',
    prefix_in_serial_number_for_picking_list = 'Prefix in Serial Number for Picking List',
    prefix_in_serial_number_for_place_list = 'Prefix in Serial Number for Place List',
    prefix_in_serial_number_for_quality_assurance_control = 'Prefix in Serial Number for Quality Assurance Control',
    prefix_in_serial_number_for_requirement = 'Prefix in Serial Number for Requirement',
    prefix_in_serial_number_for_requirement_planning_number = 'Prefix in Serial Number for Requirement Planning Number',
    prefix_in_serial_number_for_requisition = 'Prefix in Serial Number for Requisition',
    prefix_in_serial_number_for_sales_order = 'Prefix in Serial Number for Sales Order',
    prefix_in_serial_number_for_workorder = 'Prefix in Serial Number for Workorder',
    prefix_in_serial_number_of_internal_distribution_order = 'Prefix in Serial Number of Internal Distribution Order',
    prefix_in_serial_for_stock_transfer = 'Prefix in Serial for Stock Transfer',
    program_name__and__path_to_view_a_drawing = 'Program (Name & Path) to View a Drawing',
    purchase_budget_level_type = 'Purchase Budget Level Type',
    purpose_level_in_warrant_structure = 'Purpose Level in Warrant Structure',
    request_approve_handling_default = 'Request Approve Handling Default',
    request_search_default = 'Request Search Default',
    sales_order_type_receiver_restrictions = 'Sales Order Type Receiver Restrictions',
    save_shopping_basket = 'Save Shopping Basket',
    serial_sequence_in_accounting_journal_number = 'Serial Sequence in Accounting Journal Number',
    serial_sequence_in_arrival_transaction_number = 'Serial Sequence in Arrival Transaction Number',
    serial_sequence_in_disassembly_order = 'Serial Sequence in Disassembly Order',
    serial_sequence_in_external_order_transaction_number = 'Serial Sequence in External Order Transaction Number',
    serial_sequence_in_frame_agreement_number = 'Serial Sequence in Frame Agreement Number',
    serial_sequence_in_gateway_entry = 'Serial Sequence in Gateway Entry',
    serial_sequence_in_inbound_invoice_number = 'Serial Sequence in Inbound Invoice Number',
    serial_sequence_in_internal_distribution_order = 'Serial Sequence in Internal Distribution Order',
    serial_sequence_in_internal_order_transaction_number = 'Serial Sequence in Internal Order Transaction Number',
    serial_sequence_in_outbound_invoice_number = 'Serial Sequence in Outbound Invoice Number',
    serial_sequence_in_picking_list_number = 'Serial Sequence in Picking List Number',
    serial_sequence_in_place_list_number = 'Serial Sequence in Place List Number',
    serial_sequence_in_purchase_order_transaction_number = 'Serial Sequence in Purchase Order Transaction Number',
    serial_sequence_in_purchase_request = 'Serial Sequence in Purchase Request',
    serial_sequence_in_quality_assurance_control = 'Serial Sequence in Quality Assurance Control',
    serial_sequence_in_replenisment_number = 'Serial Sequence in Replenisment Number',
    serial_sequence_in_requirement_planning_number = 'Serial Sequence in Requirement Planning Number',
    serial_sequence_in_requirement_transaction_number = 'Serial Sequence in Requirement Transaction Number',
    serial_sequence_in_sales_order_number = 'Serial Sequence in Sales Order Number',
    serial_sequence_in_shipment_number = 'Serial Sequence in Shipment Number',
    serial_sequence_in_stock_transfer = 'Serial Sequence in Stock Transfer',
    serial_sequence_in_stocktake_transaction_number = 'Serial Sequence in Stocktake Transaction Number',
    serial_sequence_in_workorder_number = 'Serial Sequence in Workorder Number',
    show_all_capacity_units_in_operation_schedule = 'Show all Capacity Units in Operation Schedule',
    spendig_budget_dimension = 'Spendig Budget Dimension',
    supplier_sourcing_by_sourcing_level = 'Supplier Sourcing by Sourcing Level',
    task_monitor_level = 'Task Monitor Level',
    telefax_number_to_companys_switchboard = 'Telefax Number to Companys Switchboard',
    telephone_number_to_companys_forwarder_office_slash_department_ = 'Telephone Number to Companys Forwarder Office/Department/Manager',
    telephone_number_to_companys_purchase_office_slash_department_s = 'Telephone Number to Companys Purchase Office/Department/Manager',
    telephone_number_to_companys_sales_office_slash_department_slas = 'Telephone Number to Companys Sales Office/Department/Manager',
    telephone_number_to_companys_service_office_slash_department_sl = 'Telephone Number to Companys Service Office/Department/Manager',
    telephone_number_to_companys_switchboard = 'Telephone Number to Companys Switchboard',
    telephone_number_to_companys_warehouse_office_slash_department_ = 'Telephone Number to Companys Warehouse Office/Department/Manager',
    telex_number_to_companys_switchboard = 'Telex Number to Companys Switchboard',
    trace_actual_order_cost_by_fifo = 'Trace Actual Order Cost by FiFo',
    use_guide_text = 'Use Guide Text',
    use_tool_tip = 'Use Tool Tip',
    value_added_tax_registration_number = 'Value Added Tax Registration Number',
    value_level_hit_strategy_in_warrant_structure = 'Value Level Hit strategy in Warrant Structure',
    visiting_address_line_1 = 'Visiting Address: Line 1',
    visiting_address_line_2 = 'Visiting Address: Line 2',
    visiting_address_line_3 = 'Visiting Address: Line 3',
    visiting_address_line_4 = 'Visiting Address: Line 4',
    warehouse_sourcing_level = 'Warehouse Sourcing Level'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  annset AS Annual_Settlement_Until,
  aprmst AS Organisation_Level_in_Warrant_Structure,
  bomlev AS Number_of_Levels_to_be_Displayed_in_a_Bill_of_Material,
  cadpgm AS CAD_Program_Type,
  cadrcv AS Default_Directory_for_Data_Received_from_CAD_hyphen_Host,
  cadsnd AS Default_Directory_for_Data_Send_to_CAD_hyphen_host,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  clifac AS Our_Client_Code_at_Factoring_Company,
  cmntrm AS Common_Terms_for_Transaction_Owners,
  cntcod AS Country_Identification_Code,
  coltab AS Colour_Set_Table,
  compny AS Company_Identification_Code,
  crctrl AS Credit_Control_Linked_to_Level,
  credat AS Information_Created_Date,
  creusr AS Information_Created_by_User,
  ctcprs AS Contact_Person,
  curcod AS Currency_Identification_Code,
  cwpsrc AS CWP_Search_Option,
  digarr AS Number_of_Digits_in_Arrival_Transaction_Number,
  digdsm AS Number_of_Digits_in_Disassembly_Order_Number,
  digeor AS Number_of_Digits_in_External_Order_Transaction_Number,
  digfag AS Number_of_Digits_in_Frame_Agreement_Number,
  diggwe AS Number_of_Digits_in_Gateway_Entry,
  digido AS Number_of_Digits_in_Internal_Distribution_Order,
  digiiv AS Numbere_of_Digits_in_Inbound_Invoice_Number,
  digior AS Number_of_Digits_in_Internal_Order_Transaction_Number,
  digjrn AS Number_of_digits_in_Accounting_Journal_Number,
  digoiv AS Numbere_of_Digits_in_Outbound_Invoice_Number,
  digpil AS Number_of_Digits_in_Picking_List,
  digpll AS Number_of_Digits_in_Place_List,
  digpor AS Number_of_Digits_in_Purchase_Order_Number,
  digprq AS Number_of_Digits_in_Purchase_Request_Number,
  digqac AS Number_of_Digits_in_Quality_Assurance_Control,
  digreq AS Number_of_Digits_in_Requirement_Transaction_Number,
  digrpl AS Number_of_Digits_in_Replenishment_Number,
  digrqp AS Number_of_Digits_in_Reqdot_Planning_Number,
  digshp AS Number_of_Digits_in_Shipment_Number,
  digsor AS Number_of_Digits_in_Sales_Order,
  digstf AS Number_of_Digits_in_Stock_Transfer,
  digstt AS Number_of_dDgits_in_Stocktake_Transaction_Number,
  digwor AS Number_of_Digits_in_Workorder_Number,
  dladr1 AS Delivery_Address_Line_1,
  dladr2 AS Delivery_Address_Line_2,
  dladr3 AS Delivery_Address_Line_3,
  dladr4 AS Delivery_Address_Line_4,
  dmawhs AS Default_Warehouse_Identification_Code,
  docstr AS Document_Storage_Form,
  dqcwhs AS Default_QAC_Warehouse_Identification_Code,
  drwdir AS Path_to_Drawing_Directory_or_Catalogue,
  drwpgm AS Program_Name__and__Path_to_View_a_Drawing,
  ecland AS European_Community_Country_Code,
  ecregn AS EORI__hyphen__Economic_Operators_Registration_and_Identificatio,
  emledt AS Edit_e_hyphen_mail_before_sending,
  euscep AS End_User_to_Customer_Entry_Profile,
  euspyl AS End_User_Payer_Level,
  expdir AS Path_to_Export_Directory_or_Catalogue,
  faxswt AS Telefax_Number_to_Companys_Switchboard,
  fctcod AS Factory_Identification_Code,
  fixdsm AS Prefix_in_Serial_Number_for_Disassembly_Order,
  fixfac AS Prefix_in_Frame_Agreement_Number_related_to_Customer,
  fixfas AS Prefix_in_Frame_Agreement_Number_related_to_Supplier,
  fixgwe AS Prefix_in_Serial_Number_for_Gateway_Entry,
  fixido AS Prefix_in_Serial_Number_of_Internal_Distribution_Order,
  fixiiv AS Prefix_in_Inbound_Invoice_Number,
  fixior AS Prefix_in_Serial_Number_for_Internal_Orders,
  fixjrn AS Prefix_Accounting_Journal_Number,
  fixoiv AS Prefix_in_Outbound_Invoice_Number,
  fixpil AS Prefix_in_Serial_Number_for_Picking_List,
  fixpll AS Prefix_in_Serial_Number_for_Place_List,
  fixprq AS Prefix_in_Serial_Number_for_Requisition,
  fixqac AS Prefix_in_Serial_Number_for_Quality_Assurance_Control,
  fixreq AS Prefix_in_Serial_Number_for_Requirement,
  fixrpl AS Prefix_in_Replenishment_Number,
  fixrqp AS Prefix_in_Serial_Number_for_Requirement_Planning_Number,
  fixshp AS Prefix_Shipment_Number,
  fixsor AS Prefix_in_Serial_Number_for_Sales_Order,
  fixstf AS Prefix_in_Serial_for_Stock_Transfer,
  fixwor AS Prefix_in_Serial_Number_for_Workorder,
  flemnu AS Menu_Picture_Name_for_DeskTop,
  fnttab AS Font_Set_Table,
  frmnam AS Company_Name__slash__Description,
  ftbexc AS Currenct_Set_for_Budget_Exchange_Rate,
  ftcexc AS Currenct_Set_for_Current_Exchange_Rate,
  ftfexc AS Currenct_Set_for_Fixed_Exchange_Rate,
  fyoffs AS Fiscal_Year_Offset_in_Months,
  gtwcod AS Gateway_Identification_Code,
  higbnd AS Learning_Curve_Higher_Time_Limit,
  icscat AS Default_Item_Classification_System_Catalogue,
  icwhit AS Invoice_Control_Value_Level_Hit,
  icworg AS Invoice_Control_Organisation_Level,
  iicgen AS Automatic_Generation_og_Item_Index_Catalogue_by_Level,
  iivdoi AS Display_owner_item_info_on_purchase_invoice,
  ilglvl AS _Invoice_Log_Level,
  impdir AS Path_to_Import_Directory_or_Catallogue,
  infmks AS Mapping_to_Extended_Information_on_Standard_Makes,
  jobque AS Job_Queue_Identification,
  lngcod AS Language_Identification_Code,
  lowbnd AS Learning_Curve_Lower_Time_Limit,
  lrnco1 AS Constant_1_in_Learning_Curve,
  lrnco2 AS Constant_2_in_Learning_Curve,
  lrnco3 AS Constant_3_in_Learning_Curve,
  lrncur AS Activate_and_Use_Learning_Curve,
  maadr1 AS Mailing__slash__Postal_Address_Line_1,
  maadr2 AS Mailing__slash__Postal_Address_Line_2,
  maadr3 AS Mailing__slash__Postal_Address_Line_3,
  maadr4 AS Mailing__slash__Postal_Address_Line_4,
  matadj AS Allow_Material_Adjustment_when_Ordertraces_Cost_is_Enabled,
  mcptyp AS MCP_Calculation_Currency_Exchange_Rate_Type,
  merppr AS Merge_Production_Proposales,
  mkrgrp AS Make_Library_Level_Identification,
  mltrpc AS Allow_Multiple_Replacements_of_Items,
  mplcod AS Master_Plan_Identification_Code,
  mplper AS Masterplan_Period_Length,
  mstslv AS Corporate_Master_og_Corporate_Slave_Company,
  muntyp AS Default_Master_Loading_Unit_in_Shipment,
  ordmst AS Organisation_Level_in_Spend_Control,
  ordtrc AS Trace_Actual_Order_Cost_by_FiFo,
  otccod AS Default_Claims_Order_Type,
  otmcod AS Default_Manufacturing_Order_Type,
  otpcod AS Default_Purchase_Order_Type,
  otscod AS Default_Sales_Order_Type,
  otsrcv AS Sales_Order_Type_Receiver_Restrictions,
  pbacty AS Purchase_Budget_Level_Type,
  phnfwd AS Telephone_Number_to_Companys_Forwarder_Office_slash_Department_,
  phnord AS Telephone_Number_to_Companys_Sales_Office_slash_Department_slas,
  phnprc AS Telephone_Number_to_Companys_Purchase_Office_slash_Department_s,
  phnsvc AS Telephone_Number_to_Companys_Service_Office_slash_Department_sl,
  phnswt AS Telephone_Number_to_Companys_Switchboard,
  phnwhs AS Telephone_Number_to_Companys_Warehouse_Office_slash_Department_,
  picdir AS Path_to_Picture_Directory_or_Catalogue,
  pordat AS Posting_of_Purchase_Transactions_Last_Changed_Date,
  pospor AS Posting_of_Purchase_Order_Transactions,
  possor AS Posting_of_Sales_Order_Transactions,
  poswhs AS Posting_of_Stock_Transactions,
  poswor AS Posting_of_Work_Order_Transactions,
  prcbdg AS Spendig_Budget_Dimension,
  purinv AS Default_Credit_Invoice_Group,
  ralscl AS Purpose_Level_in_Warrant_Structure,
  raltyp AS Classificaton_Level_in_Warrant_Structure,
  regnum AS Organization_or_Registration_Number,
  rqapop AS Request_Approve_Handling_Default,
  rqscop AS Request_Search_Default,
  savbsk AS Save_Shopping_Basket,
  scrdir AS Path_to_Scratch_Directory_or_Catalogue,
  serarr AS Serial_Sequence_in_Arrival_Transaction_Number,
  serdsm AS Serial_Sequence_in_Disassembly_Order,
  sereor AS Serial_Sequence_in_External_Order_Transaction_Number,
  serfag AS Serial_Sequence_in_Frame_Agreement_Number,
  sergwe AS Serial_Sequence_in_Gateway_Entry,
  serido AS Serial_Sequence_in_Internal_Distribution_Order,
  seriiv AS Serial_Sequence_in_Inbound_Invoice_Number,
  serior AS Serial_Sequence_in_Internal_Order_Transaction_Number,
  serjrn AS Serial_Sequence_in_Accounting_Journal_Number,
  seroiv AS Serial_Sequence_in_Outbound_Invoice_Number,
  serpil AS Serial_Sequence_in_Picking_List_Number,
  serpll AS Serial_Sequence_in_Place_List_Number,
  serpor AS Serial_Sequence_in_Purchase_Order_Transaction_Number,
  serprq AS Serial_Sequence_in_Purchase_Request,
  serqac AS Serial_Sequence_in_Quality_Assurance_Control,
  serreq AS Serial_Sequence_in_Requirement_Transaction_Number,
  serrpl AS Serial_Sequence_in_Replenisment_Number,
  serrqp AS Serial_Sequence_in_Requirement_Planning_Number,
  sershp AS Serial_Sequence_in_Shipment_Number,
  sersor AS Serial_Sequence_in_Sales_Order_Number,
  serstf AS Serial_Sequence_in_Stock_Transfer,
  serstt AS Serial_Sequence_in_Stocktake_Transaction_Number,
  serwor AS Serial_Sequence_in_Workorder_Number,
  shwcap AS Show_all_Capacity_Units_in_Operation_Schedule,
  sordat AS Posting_Information_of_Sales_Transactions_Last_Changed_Date,
  srcsup AS Supplier_Sourcing_by_Sourcing_Level,
  suntyp AS Default_Sub_Loading_Unit_in_Shipment,
  svcdpt AS Default_Service_Department_Code_for_CW_Service_Modue,
  sw1sup AS Enable_Supplier_Sourcing_by_Stock_Catalogue,
  tlxswt AS Telex_Number_to_Companys_Switchboard,
  tsklvl AS Task_Monitor_Level,
  txtdir AS Path_to_Text_Directory_or_Catalouge,
  umdlvl AS Definition_of_Where_to_find_Default_User_Menu,
  usegui AS Use_Guide_Text,
  usemks AS Defines_i_Standard_Makes_is_used_or_not,
  usetoo AS Use_Tool_Tip,
  vatnum AS Value_Added_Tax_Registration_Number,
  viadr1 AS Visiting_Address_Line_1,
  viadr2 AS Visiting_Address_Line_2,
  viadr3 AS Visiting_Address_Line_3,
  viadr4 AS Visiting_Address_Line_4,
  whsdat AS Posting_of_Stock_Transactions_Last_Changed_Date,
  whssrc AS Warehouse_Sourcing_Level,
  wordat AS Posting_of_Work_Transaction_Last_Changed_Date,
  wrthit AS Value_Level_Hit_strategy_in_Warrant_Structure
FROM clockwork_consolidated.rainbow_par