MODEL (
  column_descriptions (
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    accrual_handling_at_invoice_control = 'Accrual Handling at Invoice Control',
    chain_identification_code = 'Chain Identification Code',
    company_identification_code = 'Company Identification Code',
    contract__slash__agreement_identification_code = 'Contract / Agreement Identification Code',
    contract__slash__agreement_reference = 'Contract / Agreement Reference',
    convertion_factor_indicating_per_1_or_100 = 'Convertion Factor Indicating per 1 or 100',
    copied_from_original_purchase_order = 'Copied from Original Purchase Order',
    cost_center_identification_code = 'Cost Center Identification Code',
    currency_exchange_rate = 'Currency Exchange Rate',
    currency_exchange_rate_valid_from_date = 'Currency Exchange Rate Valid from Date',
    currency_identification_code = 'Currency Identification Code',
    current_activity_code = 'Current Activity Code',
    current_edi_status_for_podot = 'Current EDI Status for PO.',
    delivery_comments = 'Delivery Comments',
    department_identification_code = 'Department Identification Code',
    despatcher_order_reference_i = 'Despatcher Order Reference I',
    despatchers_name__slash__description = 'Despatchers Name / Description',
    despatchers_reference_ii = 'Despatchers Reference II',
    distribution_period_code_for_accrual = 'Distribution Period Code for Accrual',
    entered_or_registrated_date = 'Entered or Registrated Date',
    entity_identification_code = 'Entity Identification Code',
    exclude_from_messaging = 'Exclude from Messaging',
    expected_delivery_date = 'Expected Delivery Date',
    expected_despatch_date = 'Expected Despatch Date',
    expected_receiving_date = 'Expected Receiving Date',
    fax_timestamp = 'Fax Timestamp',
    fax_transmission_status = 'Fax Transmission Status',
    footing_comments = 'Footing Comments',
    forwarder_identification_code = 'Forwarder Identification Code',
    forwarding_agent_identification_code = 'Forwarding Agent Identification Code',
    forwarding_and_transport_handling_last_changed_date = 'Forwarding and Transport Handling Last Changed Date',
    freight_bill__slash__invoice_reference = 'Freight Bill / Invoice Reference',
    heading_comments = 'Heading Comments',
    how_to_default_vat_hyphen_code_on_an_order_line = 'How to Default VAT-code on an Order Line',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information Created by User',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    internal_comments = 'Internal Comments',
    invoice_approval_stop = 'Invoice Approval Stop',
    language_identification_code = 'Language Identification Code',
    last_delivery_date = 'Last Delivery Date',
    last_delivery_made_on_date = 'Last Delivery Made on Date',
    last_order_confirmation_number = 'Last Order Confirmation Number',
    last_lowest_status_on_purchase_order = 'Last (lowest) Status on Purchase Order',
    linked_to_transaction_number = 'Linked to Transaction Number',
    linked_to_transaction_sequence_number = 'Linked to Transaction Sequence Number',
    linked_to_transaction_type = 'Linked to Transaction Type',
    loading_location_identification_code = 'Loading Location Identification Code',
    master_in_quality_report = 'Master in Quality Report',
    master_in_specified_transaction_address = 'Master in Specified Transaction Address',
    master_in_a_financial_object_table = 'Master in a Financial Object Table',
    master_in_a_freight_table__slash__freight_booking = 'Master in a Freight Table / Freight Booking',
    master_in_a_payment_plan = 'Master in a Payment Plan',
    notified_owner_at_time = 'Notified Owner at Time',
    notified_owner_on_date = 'Notified Owner on Date',
    notify_despatcher_of_new_order = 'Notify Despatcher of New Order',
    number_partly_delivered_lines = 'Number Partly Delivered Lines',
    number_of_fullt_delivered_lines = 'Number of Fullt Delivered Lines',
    number_of_fully_invoiced_lines = 'Number of Fully Invoiced Lines',
    number_of_partly_invoiced_lines = 'Number of Partly Invoiced Lines',
    on_hold_caused_by_identification_code = 'On Hold Caused by Identification Code',
    order_confirmation_handling = 'Order Confirmation Handling',
    order_confirmation_handling_last_changed_date = 'Order Confirmation Handling Last Changed Date',
    order_on_hold_at_date = 'Order On Hold at Date',
    order_priority = 'Order Priority',
    order_type_group = 'Order Type Group',
    order_on_hold_by_user = 'Order on Hold by User',
    our_identification_code_at_despatcher = 'Our Identification Code at Despatcher',
    our_preferred_despatch_slash_delivery_date = 'Our Preferred Despatch/Delivery Date',
    owner_identification_code_despacther_of_order = 'Owner Identification Code: Despacther of Order',
    owner_type_despatcher_of_order = 'Owner Type: Despatcher of Order',
    payer_identification_code = 'Payer Identification Code',
    payer_type = 'Payer Type',
    payer_of_fright_bill_slash_invoice = 'Payer of Fright Bill/Invoice',
    payers_name__slash__description = 'Payers Name / Description',
    project_identification_code = 'Project Identification Code',
    purchase_agent_identification_code = 'Purchase Agent Identification Code',
    purchase_order_approval_handling = 'Purchase Order Approval Handling',
    purchase_order_approval_handling_last_changed_date = 'Purchase Order Approval Handling Last Changed Date',
    purchase_order_color_code = 'Purchase Order Color Code',
    purchase_order_locked_at_time = 'Purchase Order Locked at Time',
    purchase_order_locked_by_user = 'Purchase Order Locked by User',
    purchase_order_number = 'Purchase Order Number',
    purchase_order_on_hold = 'Purchase Order On Hold',
    purchase_order_type_identification_code = 'Purchase Order Type Identification Code',
    purchaser_identification_code = 'Purchaser Identification Code',
    receiver_identification_code = 'Receiver Identification Code',
    receiver_type = 'Receiver Type',
    receivers_name__slash__description = 'Receivers Name / Description',
    receivers_order_reference_i = 'Receivers Order Reference I',
    receivers_order_reference_ii = 'Receivers Order Reference II',
    receivers_order_reference_iii = 'Receivers Order Reference III',
    revision_number = 'Revision Number',
    self_hyphen_billing_handling = 'Self-billing handling',
    terms_defined_for_this_specific_owner = 'Terms Defined for this Specific Owner',
    terms_of_delivery_identification_code = 'Terms of Delivery Identification Code',
    terms_of_delivery_terms_defined_for_this_specific_owner = 'Terms of Delivery Terms Defined for this Specific Owner',
    terms_of_payment_identification_code = 'Terms of Payment Identification Code',
    total_handling_time_in_minutes = 'Total Handling Time in minutes',
    total_number_of_changes_made_to_order = 'Total Number of Changes Made to Order',
    total_number_of_lines_on_purchase_order = 'Total Number of Lines on Purchase Order',
    total_order_discount_percent = 'Total Order Discount Percent',
    total_order_discount_value_in_currency = 'Total Order Discount Value in Currency',
    total_purchase_order_value_in_currency = 'Total Purchase Order Value in Currency',
    transferred_to_purchase_history_log = 'Transferred to Purchase History Log',
    transferred_to_statistics = 'Transferred to Statistics',
    transport_plan_handling = 'Transport Plan Handling',
    value_added_tax_identification_code = 'Value Added Tax Identification Code',
    way_of_transport_identification_code = 'Way of Transport Identification Code',
    way_of_transport_term_defined_for_this_specific_owner = 'Way of Transport Term Defined for this Specific Owner',
    docnbr = 'No description found in source docs.',
    incmrp = 'No description found in source docs.'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  acrctr AS Accrual_Handling_at_Invoice_Control,
  actcod AS Current_Activity_Code,
  acttim AS Purchase_Order_Locked_at_Time,
  actusr AS Purchase_Order_Locked_by_User,
  agncod AS Purchase_Agent_Identification_Code,
  cbchld AS On_Hold_Caused_by_Identification_Code,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  chncod AS Chain_Identification_Code,
  cnfdat AS Order_Confirmation_Handling_Last_Changed_Date,
  cnfnum AS Last_Order_Confirmation_Number,
  cnvexc AS Convertion_Factor_Indicating_per_1_or_100,
  compny AS Company_Identification_Code,
  coppor AS Copied_from_Original_Purchase_Order,
  credat AS Information_Created_Date,
  creusr AS Information_Created_by_User,
  csccod AS Cost_Center_Identification_Code,
  ctaghd AS Contract__slash__Agreement_Reference,
  ctragr AS Contract__slash__Agreement_Identification_Code,
  curcod AS Currency_Identification_Code,
  dathld AS Order_On_Hold_at_Date,
  disprc AS Total_Order_Discount_Percent,
  disval AS Total_Order_Discount_Value_in_Currency,
  dlvdat AS Expected_Delivery_Date,
  dptcod AS Department_Identification_Code,
  dspdat AS Expected_Despatch_Date,
  dspnam AS Despatchers_Name__slash__Description,
  dstper AS Distribution_Period_Code_for_Accrual,
  edists AS Current_EDI_Status_for_POdot,
  ettcod AS Entity_Identification_Code,
  excdat AS Currency_Exchange_Rate_Valid_from_Date,
  excmsg AS Exclude_from_Messaging,
  excrat AS Currency_Exchange_Rate,
  faxdat AS Fax_Timestamp,
  faxsts AS Fax_Transmission_Status,
  frtref AS Freight_Bill__slash__Invoice_Reference,
  fwacod AS Forwarding_Agent_Identification_Code,
  fwdcod AS Forwarder_Identification_Code,
  hldmin AS Total_Handling_Time_in_minutes,
  invapr AS Invoice_Approval_Stop,
  lindpl AS Number_Partly_Delivered_Lines,
  linfdl AS Number_of_Fullt_Delivered_Lines,
  linfin AS Number_of_Fully_Invoiced_Lines,
  linpin AS Number_of_Partly_Invoiced_Lines,
  llccod AS Loading_Location_Identification_Code,
  lngcod AS Language_Identification_Code,
  lsdldt AS Last_Delivery_Made_on_Date,
  lstdlv AS Last_Delivery_Date,
  lststs AS Last_lowest_Status_on_Purchase_Order,
  mstfot AS Master_in_a_Financial_Object_Table,
  mstfrt AS Master_in_a_Freight_Table__slash__Freight_Booking,
  mstpyp AS Master_in_a_Payment_Plan,
  mstqar AS Master_in_Quality_Report,
  msttra AS Master_in_Specified_Transaction_Address,
  ntfdat AS Notified_Owner_on_Date,
  ntfown AS Notify_Despatcher_of_New_Order,
  ntftim AS Notified_Owner_at_Time,
  numchg AS Total_Number_of_Changes_Made_to_Order,
  onhold AS Purchase_Order_On_Hold,
  ordcnf AS Order_Confirmation_Handling,
  ordval AS Total_Purchase_Order_Value_in_Currency,
  orqdat AS Our_Preferred_Despatch_slash_Delivery_Date,
  otpcod AS Purchase_Order_Type_Identification_Code,
  otpgrp AS Order_Type_Group,
  ourcod AS Our_Identification_Code_at_Despatcher,
  ourref AS Receivers_Order_Reference_II,
  owncod AS Owner_Identification_Code_Despacther_of_Order,
  ownctc AS Despatchers_Reference_II,
  ownref AS Despatcher_Order_Reference_I,
  owntyp AS Owner_Type_Despatcher_of_Order,
  paycod AS Payer_Identification_Code,
  payfrt AS Payer_of_Fright_Bill_slash_Invoice,
  paynam AS Payers_Name__slash__Description,
  paytyp AS Payer_Type,
  pcccod AS Purchase_Order_Color_Code,
  poadat AS Purchase_Order_Approval_Handling_Last_Changed_Date,
  poahnd AS Purchase_Order_Approval_Handling,
  pornum AS Purchase_Order_Number,
  prccod AS Purchaser_Identification_Code,
  pricod AS Order_Priority,
  prjcod AS Project_Identification_Code,
  rcvcod AS Receiver_Identification_Code,
  rcvdat AS Expected_Receiving_Date,
  rcvnam AS Receivers_Name__slash__Description,
  rcvtyp AS Receiver_Type,
  regdat AS Entered_or_Registrated_Date,
  reqnum AS Receivers_Order_Reference_III,
  requsr AS Receivers_Order_Reference_I,
  revnum AS Revision_Number,
  sbihnd AS Self_hyphen_billing_handling,
  tdlcod AS Terms_of_Delivery_Identification_Code,
  tdlown AS Terms_of_Delivery_Terms_Defined_for_this_Specific_Owner,
  totlin AS Total_Number_of_Lines_on_Purchase_Order,
  tpycod AS Terms_of_Payment_Identification_Code,
  tpyown AS Terms_Defined_for_this_Specific_Owner,
  trfhst AS Transferred_to_Purchase_History_Log,
  trfsta AS Transferred_to_Statistics,
  trnnum AS Linked_to_Transaction_Number,
  trnseq AS Linked_to_Transaction_Sequence_Number,
  trntyp AS Linked_to_Transaction_Type,
  trsdat AS Forwarding_and_Transport_Handling_Last_Changed_Date,
  trssts AS Transport_Plan_Handling,
  txtdlv AS Delivery_Comments,
  txtfot AS Footing_Comments,
  txtgen AS Internal_Comments,
  txthed AS Heading_Comments,
  usrhld AS Order_on_Hold_by_User,
  vatcod AS Value_Added_Tax_Identification_Code,
  vatuse AS How_to_Default_VAT_hyphen_code_on_an_Order_Line,
  wtrcod AS Way_of_Transport_Identification_Code,
  wtrown AS Way_of_Transport_Term_Defined_for_this_Specific_Owner
FROM clockwork_consolidated.rainbow_poh