MODEL (
  column_descriptions (
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    actual_purchase_price = 'Actual Purchase Price',
    actual_purchased_quantity = 'Actual Purchased Quantity',
    arrived_quantity = 'Arrived Quantity',
    base_purchase_price = 'Base Purchase Price',
    cataloge_buy = 'Cataloge Buy',
    caused_by_code_for_cancellation_of_order_line = 'Caused By Code for Cancellation of Order Line',
    caused_by_code_for_entering__slash__registration_of_this_line = 'Caused by Code for Entering / Registration of this Line',
    caused_by_code_for_putting_this_line_on_hold = 'Caused by Code for putting this Line on Hold',
    change_restriction_time_value = 'Change Restriction Time Value',
    change_restriction_time_value_calendar_type = 'Change Restriction Time Value Calendar Type',
    change_restriction_time_value_date_type = 'Change Restriction Time Value Date Type',
    company_identification_code = 'Company Identification Code',
    confirmed_delivery_date = 'Confirmed Delivery Date',
    confirmed_despatch_date = 'Confirmed Despatch Date',
    confirmed_quantity = 'Confirmed Quantity',
    consigned_replacement_reference = 'Consigned Replacement Reference',
    controlled_quantity = 'Controlled Quantity',
    cost_centre_identification_code = 'Cost centre identification code',
    country_of_origin = 'Country of Origin',
    customs_tariff_number_identificaton_code = 'Customs Tariff Number Identificaton Code',
    delivery_marking = 'Delivery Marking',
    department_identification_code = 'Department Identification Code',
    distribution_period_code_for_accrual = 'Distribution Period Code for Accrual',
    dynamic_financial_information = 'Dynamic Financial Information',
    ear_hyphen_code_identification_code = 'EAR-Code Identification Code',
    entered_or_registrated_date = 'Entered or Registrated Date',
    expected_delivery_date = 'Expected Delivery Date',
    expected_despatch_date = 'Expected Despatch Date',
    external_comments__slash__text = 'External Comments / Text',
    external_item_identification_code = 'External Item Identification Code',
    external_item_name__slash__description = 'External Item Name / Description',
    external_item_catalogue_seqquence_code = 'External item catalogue seqquence code',
    frame_agreement_number = 'Frame Agreement Number',
    gross_volume_in_dm3 = 'Gross volume in dm3',
    gross_weight_in_kilos = 'Gross weight in kilos',
    individ_identification_number = 'Individ Identification Number',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information created by user',
    information_last_changed_by_user = 'Information last changed by user',
    information_last_changed_date = 'Information last changed date',
    internal_comments = 'Internal Comments',
    invoiced_price = 'Invoiced price',
    invoiceed_quantity = 'Invoiceed Quantity',
    item_classification_catalogue_identification = 'Item Classification Catalogue Identification',
    item_classification_reference_code_in_catalogue = 'Item Classification Reference Code in Catalogue',
    item_make_sequence_number = 'Item Make Sequence Number',
    last_delivered_on_date = 'Last Delivered on Date',
    line_item_code_according_to_type = 'Line Item Code according to Type',
    line_item_name__slash__description = 'Line Item Name / Description',
    line_position_number = 'Line Position Number',
    line_status_code_lowest = 'Line Status Code (Lowest)',
    line_type_identifying_different_types_of_items_on_a_line = 'Line Type: Identifying Different Types of Items on a Line',
    line_hyphen_item_is_updated_in_stock = 'Line-item is updated in stock',
    locked_or_available_slash_open_for_replanning = 'Locked or Available/Open for Replanning',
    manual_direct_discount_numeric_value = 'Manual direct discount numeric value',
    manual_direct_discount_type = 'Manual direct discount type',
    manual_direct_discount_value = 'Manual direct discount value',
    master_certificate_sequence_number = 'Master Certificate Sequence Number',
    master_i_quality_report = 'Master i Quality Report',
    master_in_a_qa_hyphen_control_log = 'Master in a QA-Control log',
    master_in_a_reminder_plan = 'Master in a reminder plan',
    master_in_an_individ_list = 'Master in an individ list',
    master_in_material_sub_hyphen_structure = 'Master in material sub-structure',
    master_in_notification = 'Master in notification',
    master_or_child_in_certificates = 'Master or Child in Certificates',
    net_volume_in_dm3 = 'Net volume in dm3',
    net_weight_in_kilo = 'Net weight in kilo',
    order_confirmation_number = 'Order Confirmation Number',
    order_form_identificatoon_code = 'Order Form Identificatoon Code',
    order_form_linked_to_requesting_transaction = 'Order Form Linked to Requesting Transaction',
    original_delivery_date = 'Original Delivery Date',
    original_purchased_quantity = 'Original Purchased Quantity',
    our_preferred_date = 'Our Preferred Date',
    overridden_customs_net_price = 'Overridden Customs Net Price',
    parent_sequence_number = 'Parent Sequence Number',
    project_identification_code = 'Project Identification Code',
    purchase_order_line_number = 'Purchase Order Line Number',
    purchase_order_line_sequence_number = 'Purchase Order Line Sequence Number',
    purchase_order_number = 'Purchase Order Number',
    quantity_to_be_arrived = 'Quantity to be Arrived',
    quantity_to_be_confirmed = 'Quantity to be Confirmed',
    quantity_to_be_controlled = 'Quantity to be Controlled',
    quantity_to_be_invoiced = 'Quantity to be Invoiced',
    quantity_to_be_received = 'Quantity to be Received',
    quantity_to_be_rejected = 'Quantity to be Rejected',
    received_quantity = 'Received Quantity',
    reference_to_external_request = 'Reference to External Request',
    rejected_quantity = 'Rejected Quantity',
    relation_ratio_from_transaction_unit_to_base_unit = 'Relation Ratio from Transaction Unit to Base Unit',
    relation_type_from_transaction_unit_to_base_unit = 'Relation Type from Transaction Unit to Base Unit',
    requested_by_cw_user = 'Requested by CW User',
    requested_by_transaction_number = 'Requested by transaction number',
    requested_by_transaction_sequence_number = 'Requested by transaction sequence number',
    requested_by_transaction_type = 'Requested by transaction type',
    requested_from_transaction_by_link = 'Requested from transaction by link',
    revision_number = 'Revision number',
    system_direct_discount_numeric_value = 'System direct discount numeric value',
    system_direct_discount_type = 'System direct discount type',
    system_direct_discount_value = 'System direct discount value',
    total_additional_direct_cost = 'Total additional direct cost',
    total_additional_indirect_cost = 'Total additional indirect cost',
    total_direct_discount_percentage = 'Total direct discount percentage',
    total_direct_discount_value = 'Total direct discount value',
    total_indirect_discount_percentage = 'Total indirect discount percentage',
    total_indirect_discount_value = 'Total indirect discount value',
    total_material_sub_hyphen_structure_cost_value = 'Total material sub-structure cost value',
    total_number_of_pallets = 'Total number of pallets',
    total_number_of_parcels = 'Total number of parcels',
    total_purchase_value = 'Total purchase value',
    transaction_line_currently_on_hold_and_waiting = 'Transaction Line Currently on Hold and Waiting',
    transaction_unit_identification_code = 'Transaction Unit Identification Code',
    type_of_rejection = 'Type of Rejection',
    value_added_tax_identification_code = 'Value added tax identification code',
    variant_string_identification_code = 'Variant String Identification Code',
    volume_per_unit_or_total = 'Volume per unit or total',
    warehouse_identification_code = 'Warehouse identification code',
    weight_per_unit_or_total = 'Weight per unit or total'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  agrnum AS Frame_Agreement_Number,
  catbuy AS Cataloge_Buy,
  cbccnl AS Caused_By_Code_for_Cancellation_of_Order_Line,
  cbcent AS Caused_by_Code_for_Entering__slash__Registration_of_this_Line,
  cbchld AS Caused_by_Code_for_putting_this_Line_on_Hold,
  chgdat AS Information_last_changed_date,
  chgrtd AS Change_Restriction_Time_Value_Date_Type,
  chgrtt AS Change_Restriction_Time_Value_Calendar_Type,
  chgrtv AS Change_Restriction_Time_Value,
  chgusr AS Information_last_changed_by_user,
  cnfdsp AS Confirmed_Despatch_Date,
  cnfnum AS Order_Confirmation_Number,
  cnfrcv AS Confirmed_Delivery_Date,
  cntori AS Country_of_Origin,
  compny AS Company_Identification_Code,
  credat AS Information_Created_Date,
  creusr AS Information_created_by_user,
  csccod AS Cost_centre_identification_code,
  cstcod AS Customs_Tariff_Number_Identificaton_Code,
  cstprc AS Overridden_Customs_Net_Price,
  ctfseq AS Master_Certificate_Sequence_Number,
  dfiseq AS Dynamic_Financial_Information,
  dlvdat AS Expected_Delivery_Date,
  dlvmrk AS Delivery_Marking,
  dptcod AS Department_Identification_Code,
  dsctyp AS Type_of_Rejection,
  dspdat AS Expected_Despatch_Date,
  dstper AS Distribution_Period_Code_for_Accrual,
  earcod AS EAR_hyphen_Code_Identification_Code,
  extitm AS External_Item_Identification_Code,
  extnam AS External_Item_Name__slash__Description,
  extreq AS Reference_to_External_Request,
  extseq AS External_item_catalogue_seqquence_code,
  grsvdm AS Gross_volume_in_dm3,
  grswkg AS Gross_weight_in_kilos,
  icscat AS Item_Classification_Catalogue_Identification,
  icsref AS Item_Classification_Reference_Code_in_Catalogue,
  idncod AS Individ_Identification_Number,
  itkseq AS Item_Make_Sequence_Number,
  lincod AS Line_Item_Code_according_to_Type,
  linnam AS Line_Item_Name__slash__Description,
  linnum AS Purchase_Order_Line_Number,
  lintyp AS Line_Type_Identifying_Different_Types_of_Items_on_a_Line,
  lstdat AS Last_Delivered_on_Date,
  lststs AS Line_Status_Code_Lowest,
  manddn AS Manual_direct_discount_numeric_value,
  manddt AS Manual_direct_discount_type,
  manddv AS Manual_direct_discount_value,
  matcst AS Total_material_sub_hyphen_structure_cost_value,
  mstctf AS Master_or_Child_in_Certificates,
  mstidn AS Master_in_an_individ_list,
  mstmat AS Master_in_material_sub_hyphen_structure,
  mstnot AS Master_in_notification,
  mstqac AS Master_in_a_QA_hyphen_Control_log,
  mstqar AS Master_i_Quality_Report,
  mstrmp AS Master_in_a_reminder_plan,
  netvdm AS Net_volume_in_dm3,
  netwkg AS Net_weight_in_kilo,
  numpal AS Total_number_of_pallets,
  numpcl AS Total_number_of_parcels,
  ofmcod AS Order_Form_Identificatoon_Code,
  ofmreq AS Order_Form_Linked_to_Requesting_Transaction,
  onhold AS Transaction_Line_Currently_on_Hold_and_Waiting,
  orqdat AS Our_Preferred_Date,
  ownseq AS Parent_Sequence_Number,
  plnsts AS Locked_or_Available_slash_Open_for_Replanning,
  pornum AS Purchase_Order_Number,
  posnum AS Line_Position_Number,
  prcact AS Actual_Purchase_Price,
  prcbas AS Base_Purchase_Price,
  prcinv AS Invoiced_price,
  prjcod AS Project_Identification_Code,
  q2barr AS Quantity_to_be_Arrived,
  q2bcnf AS Quantity_to_be_Confirmed,
  q2bdsc AS Quantity_to_be_Rejected,
  q2binv AS Quantity_to_be_Invoiced,
  q2bqac AS Quantity_to_be_Controlled,
  q2brcv AS Quantity_to_be_Received,
  qtyarr AS Arrived_Quantity,
  qtycnf AS Confirmed_Quantity,
  qtydsc AS Rejected_Quantity,
  qtyinv AS Invoiceed_Quantity,
  qtyord AS Original_Purchased_Quantity,
  qtyprc AS Actual_Purchased_Quantity,
  qtyqac AS Controlled_Quantity,
  qtyrcv AS Received_Quantity,
  qtysad AS qtysad,
  rcvdat AS Original_Delivery_Date,
  regdat AS Entered_or_Registrated_Date,
  reqnum AS Requested_by_transaction_number,
  reqseq AS Requested_by_transaction_sequence_number,
  reqtrn AS Requested_from_transaction_by_link,
  reqtyp AS Requested_by_transaction_type,
  requsr AS Requested_by_CW_User,
  revnum AS Revision_number,
  rplref AS Consigned_Replacement_Reference,
  seqnum AS Purchase_Order_Line_Sequence_Number,
  stcupd AS Line_hyphen_item_is_updated_in_stock,
  sysddn AS System_direct_discount_numeric_value,
  sysddt AS System_direct_discount_type,
  sysddv AS System_direct_discount_value,
  tatadc AS Total_additional_direct_cost,
  totaic AS Total_additional_indirect_cost,
  totddp AS Total_direct_discount_percentage,
  totddv AS Total_direct_discount_value,
  totidp AS Total_indirect_discount_percentage,
  totidv AS Total_indirect_discount_value,
  totval AS Total_purchase_value,
  trnrra AS Relation_Ratio_from_Transaction_Unit_to_Base_Unit,
  trnrty AS Relation_Type_from_Transaction_Unit_to_Base_Unit,
  trnunt AS Transaction_Unit_Identification_Code,
  txtgen AS Internal_Comments,
  txtitm AS External_Comments__slash__Text,
  vatcod AS Value_added_tax_identification_code,
  vdmtyp AS Volume_per_unit_or_total,
  vrscod AS Variant_String_Identification_Code,
  whscod AS Warehouse_identification_code,
  wkgtyp AS Weight_per_unit_or_total
FROM clockwork_consolidated.rainbow_pol