MODEL (
  column_descriptions (
    _fax_timestamp = ' Fax Timestamp',
    _fax_transmission_status = ' Fax Transmission Status',
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    actual_date_related_to_expiration_date = 'Actual Date related to Expiration Date',
    additional_markup_percentage = 'Additional markup percentage',
    advance_payment_status_code = 'Advance Payment Status Code',
    assorted_order_discount_matrix_identification_code = 'Assorted Order Discount Matrix Identification Code',
    chain_identification_code = 'Chain Identification Code',
    committed_order_value = 'Committed Order Value',
    company_identification_code = 'Company identification code',
    convertion_factor__indicating_per_1_or_100 = 'Convertion factor  indicating per 1 or 100',
    cost_centre_identification_code = 'Cost centre identification code',
    cross_docking_customer_number = 'Cross Docking customer number',
    cross_docking_delivery_order = 'Cross Docking delivery order',
    currency_identification_code = 'Currency Identification Code',
    currency_exchange_rate = 'Currency exchange rate',
    currency_exchange_rate_valid_from_date = 'Currency exchange rate valid from date',
    currency_type = 'Currency type',
    current_activity_code = 'Current activity code',
    deadline_date = 'Deadline Date',
    default_markup_percentage = 'Default markup percentage',
    default_price_method = 'Default price method',
    delivery_address_is_changed = 'Delivery Address is Changed',
    department_identification_code = 'Department identification code',
    despatcher_identification_code_within_a_given_receiver_type = 'Despatcher identification code within a given receiver type',
    despatcher_type_identifying_a_set_of_despatchers = 'Despatcher type: identifying a set of despatchers',
    despatchers_reference_i = 'Despatchers Reference I',
    despatchers_reference_ii = 'Despatchers Reference II',
    despatchers_name_slash_description = 'Despatchers name/description',
    edi_message_status_indicator = 'EDI message status indicator',
    end_user_identification_code = 'End User Identification Code',
    end_user_name_slash_description = 'End User Name/Description',
    entered_or_registrated_date = 'Entered or Registrated Date',
    entity_identification_code = 'Entity Identification Code',
    expected_despatch_date_from_owner_at_exdotworks_conditions = 'Expected despatch date from owner at ex.works conditions',
    expected_receiving_date_at_reciever = 'Expected receiving date at reciever',
    expiration_date_related_to_quotation_og_loan = 'Expiration Date related to Quotation og Loan',
    external_text__slash__comments_delivery = 'External Text / Comments: Delivery',
    external_text__slash__comments_footing = 'External Text / Comments: Footing',
    external_text__slash__comments_heading = 'External Text / Comments: Heading',
    external_order_number__idot_edot_edi_hyphen_order_ = 'External order number ( i. e. EDI-order )',
    external_text__slash__comments_invoice = 'External text / Comments: Invoice',
    external_trade_catalogue = 'External trade catalogue',
    fixed_discount_percentage = 'Fixed Discount Percentage',
    fixed_item_discount_identification_code = 'Fixed Item Discount Identification Code',
    forwarder_agent_code = 'Forwarder agent code',
    forwarder_identification_code = 'Forwarder identification code',
    freight_code = 'Freight Code',
    global_variant_model_identification_code = 'Global Variant Model Identification Code',
    handling_of_components_in_component_transfer_order = 'Handling of Components in Component Transfer Order',
    how_to_default_vat_on_an_order_line = 'How to Default VAT on an Order Line',
    how_to_treat_and_print_delivery_text = 'How to treat and print delivery text',
    how_to_treat_and_print_fotting_text = 'How to treat and print fotting text',
    how_to_treat_and_print_general_text = 'How to treat and print general text',
    how_to_treat_and_print_heading_text = 'How to treat and print heading text',
    include_in_material_requirement_planning = 'Include in Material Requirement Planning',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information created by user',
    information_last_changed_by_user = 'Information last changed by user',
    information_last_changed_date = 'Information last changed date',
    internal_text__slash__comments = 'Internal Text / Comments',
    invoice_fee_handling = 'Invoice Fee Handling',
    invoice_plan_number = 'Invoice plan number',
    language_identification_code = 'Language Identification Code',
    last_delivery_date = 'Last delivery date',
    last_lowest_status_on_sales_order = 'Last (lowest) Status on Sales Order',
    loading_location_identification_code = 'Loading Location Identification Code',
    manual_discount_numeric_value = 'Manual discount numeric value',
    manual_discount_type = 'Manual discount type',
    manual_disount_value = 'Manual disount value',
    manually_entered_freight_cost = 'Manually Entered Freight Cost',
    master_in_a_financial_object_table = 'Master in a financial object table',
    master_in_a_freight_table = 'Master in a freight table',
    master_in_specified_transaction_address = 'Master in specified transaction address',
    next_delivery_due_on_date = 'Next delivery due on date',
    no_delivery_prior_to_this_date = 'No Delivery Prior to this Date',
    notified_owner_at_time = 'Notified owner at time',
    notified_owner_on_date = 'Notified owner on date',
    notify_receiver_of_new_order = 'Notify Receiver of New Order',
    on_hold_and_waiting_caused_by = 'On hold and waiting caused by',
    order_priority = 'Order Priority',
    order_type_group = 'Order Type Group',
    order_confirmation = 'Order confirmation',
    owner_identification_code_within_a_given_owner_type = 'Owner identification code within a given owner type',
    owner_type_identifying_a_set_of_receivers = 'Owner type: identifying a set of receivers',
    owners_requested_delivery_date = 'Owners Requested Delivery Date',
    payer_owner_type = 'Payer owner type',
    payers_name_slash_description = 'Payers name/description',
    payment_owner_code = 'Payment owner code',
    picking_team_identification_code = 'Picking Team Identification Code',
    project_identification_code = 'Project identification code',
    put_on_hold_at_date__and__time = 'Put On Hold at Date & Time',
    quotation_probability = 'Quotation Probability',
    receival_slash_delivery_from_time_of_date = 'Receival/Delivery from Time of Date',
    receival_slash_delivery_until_time_of_date = 'Receival/Delivery until Time of Date',
    receivers_reference_ii = 'Receivers Reference II',
    receivers_reference_iii = 'Receivers Reference III',
    receivers_reference_number_i = 'Receivers Reference Number I',
    receivers_name_slash_description = 'Receivers name/description',
    reference_to_original_order = 'Reference to Original Order',
    route_identification_code = 'Route identification code',
    sales_item_discount_matrix_identification_code = 'Sales Item Discount Matrix Identification Code',
    sales_order_approval_handling = 'Sales Order Approval Handling',
    sales_order_color_code = 'Sales Order Color Code',
    sales_order_discount_matrix_identification_code = 'Sales Order Discount Matrix Identification Code',
    sales_order_locked_at_date = 'Sales Order Locked at Date',
    sales_order_locked_by_user = 'Sales Order Locked by User',
    sales_price_list_code = 'Sales Price List Code',
    sales_agent_identification_code = 'Sales agent identification code',
    sales_order_number = 'Sales order number',
    sales_order_type = 'Sales order type',
    seller__slash__salesperson_identification_code = 'Seller / Salesperson identification code',
    service__and__billing_contract_code = 'Service & Billing Contract Code',
    service__and__billing_generated_code = 'Service & Billing: Generated Code',
    service__and__billing_use_main_reference = 'Service & Billing: Use Main Reference',
    service__and__billing_use_reference = 'Service & Billing: Use Reference',
    single_or_consolidated_invoice_by_receiver_or_payer = 'Single or Consolidated Invoice by Receiver or Payer',
    single_transport_is_required = 'Single transport is required',
    system_discount_numeric_value = 'System discount numeric value',
    system_discount_type = 'System discount type',
    system_discount_value = 'System discount value',
    tells_if_project_price_is_used_on_this_order = 'Tells if project price is used on this order',
    terms_of_delivery_identification_code = 'Terms of delivery identification code',
    terms_of_payment_identification_code = 'Terms of payment identification code',
    total_additional_cost_value = 'Total Additional Cost Value',
    total_additional_sales_value = 'Total Additional Sales Value',
    total_estimated_cost_value = 'Total Estimated Cost Value',
    total_gross_area_on_order_in_m2 = 'Total Gross Area on Order in m2',
    total_net_area_on_order_in_m2 = 'Total Net Area on Order in m2',
    total_order_value_in_currency = 'Total Order Value in Currency',
    total_gross_volume = 'Total gross volume',
    total_gross_weight = 'Total gross weight',
    total_handling_time_in_minutes = 'Total handling time in minutes',
    total_net_volume = 'Total net volume',
    total_net_weight = 'Total net weight',
    total_number_of_changes_to_order = 'Total number of changes to order',
    total_order_discount_value_in_currency = 'Total order discount value in currency',
    total_order_discount_value_in_percent = 'Total order discount value in percent',
    transaction_currently_on_hold_or_stopped = 'Transaction Currently On Hold or Stopped',
    transaction_put_on_hold_by_user = 'Transaction Put on Hold by User',
    transferred_to_sales_history_log = 'Transferred to sales history log',
    transferred_to_statistics = 'Transferred to statistics',
    transport_plan_status = 'Transport plan status',
    value_added_tax_identification_code = 'Value added tax identification code',
    way_of_transport_identification_code = 'Way of transport identification code',
    tdlown_terms_defined_for_this_specific_owner = 'Terms defined for this specific owner',
    tpyown_terms_defined_for_this_specific_owner = 'Terms defined for this specific owner',
    wtrown_terms_defined_for_this_specific_owner = 'Terms defined for this specific owner'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  actcod AS Current_activity_code,
  actdat AS Actual_Date_related_to_Expiration_Date,
  acttim AS Sales_Order_Locked_at_Date,
  actusr AS Sales_Order_Locked_by_User,
  addcst AS Total_Additional_Cost_Value,
  addmrk AS Additional_markup_percentage,
  addsal AS Total_Additional_Sales_Value,
  agncod AS Sales_agent_identification_code,
  aodmid AS Assorted_Order_Discount_Matrix_Identification_Code,
  cbchld AS On_hold_and_waiting_caused_by,
  cdcusn AS Cross_Docking_customer_number,
  cddlvo AS Cross_Docking_delivery_order,
  chgdat AS Information_last_changed_date,
  chgusr AS Information_last_changed_by_user,
  chncod AS Chain_Identification_Code,
  cnvexc AS Convertion_factor__indicating_per_1_or_100,
  compny AS Company_identification_code,
  copsor AS Reference_to_Original_Order,
  covval AS Committed_Order_Value,
  credat AS Information_Created_Date,
  creusr AS Information_created_by_user,
  csccod AS Cost_centre_identification_code,
  cstval AS Total_Estimated_Cost_Value,
  ctrhnd AS Handling_of_Components_in_Component_Transfer_Order,
  curcod AS Currency_Identification_Code,
  curtyp AS Currency_type,
  dathld AS Put_On_Hold_at_Date__and__Time,
  ddldat AS Deadline_Date,
  defprc AS Default_price_method,
  disprc AS Total_order_discount_value_in_percent,
  disval AS Total_order_discount_value_in_currency,
  dlachg AS Delivery_Address_is_Changed,
  dlvdat AS Next_delivery_due_on_date,
  dptcod AS Department_identification_code,
  dspcod AS Despatcher_identification_code_within_a_given_receiver_type,
  dspdat AS Expected_despatch_date_from_owner_at_exdotworks_conditions,
  dspnam AS Despatchers_name_slash_description,
  dsptyp AS Despatcher_type_identifying_a_set_of_despatchers,
  edists AS EDI_message_status_indicator,
  ettcod AS Entity_Identification_Code,
  euscod AS End_User_Identification_Code,
  eusnam AS End_User_Name_slash_Description,
  excdat AS Currency_exchange_rate_valid_from_date,
  excrat AS Currency_exchange_rate,
  expdat AS Expiration_Date_related_to_Quotation_og_Loan,
  extord AS External_order_number__idot_edot_EDI_hyphen_order_,
  faxdat AS _Fax_Timestamp,
  faxsts AS _Fax_Transmission_Status,
  fixdsc AS Fixed_Discount_Percentage,
  frtcod AS Freight_Code,
  fwacod AS Forwarder_agent_code,
  fwdcod AS Forwarder_identification_code,
  gencod AS Service__and__Billing_Generated_Code,
  grsam2 AS Total_Gross_Area_on_Order_in_m2,
  grsvdm AS Total_gross_volume,
  grswgk AS Total_gross_weight,
  gvrcod AS Global_Variant_Model_Identification_Code,
  hldmin AS Total_handling_time_in_minutes,
  incmrp AS Include_in_Material_Requirement_Planning,
  invfee AS Invoice_Fee_Handling,
  ipdnum AS Invoice_plan_number,
  llccod AS Loading_Location_Identification_Code,
  lngcod AS Language_Identification_Code,
  lsdldt AS Last_delivery_date,
  lststs AS Last_lowest_Status_on_Sales_Order,
  manddn AS Manual_discount_numeric_value,
  manddt AS Manual_discount_type,
  manddv AS Manual_disount_value,
  manfrt AS Manually_Entered_Freight_Cost,
  markup AS Default_markup_percentage,
  mstfot AS Master_in_a_financial_object_table,
  mstfrt AS Master_in_a_freight_table,
  mstpyp AS Advance_Payment_Status_Code,
  msttra AS Master_in_specified_transaction_address,
  ndldat AS No_Delivery_Prior_to_this_Date,
  netam2 AS Total_Net_Area_on_Order_in_m2,
  netvdm AS Total_net_volume,
  netwgk AS Total_net_weight,
  ntfdat AS Notified_owner_on_date,
  ntfown AS Notify_Receiver_of_New_Order,
  ntftim AS Notified_owner_at_time,
  numchg AS Total_number_of_changes_to_order,
  onhold AS Transaction_Currently_On_Hold_or_Stopped,
  ordcnf AS Order_confirmation,
  ordval AS Total_Order_Value_in_Currency,
  otscod AS Sales_order_type,
  otsgrp AS Order_Type_Group,
  ourctc AS Despatchers_Reference_II,
  ourref AS Despatchers_Reference_I,
  owncod AS Owner_identification_code_within_a_given_owner_type,
  ownctc AS Receivers_Reference_III,
  owndat AS Owners_Requested_Delivery_Date,
  ownref AS Receivers_Reference_Number_I,
  ownrf2 AS Receivers_Reference_II,
  owntyp AS Owner_type_identifying_a_set_of_receivers,
  paycod AS Payment_owner_code,
  paynam AS Payers_name_slash_description,
  paytyp AS Payer_owner_type,
  pctcod AS Picking_Team_Identification_Code,
  prbblt AS Quotation_Probability,
  pricod AS Order_Priority,
  prjcod AS Project_identification_code,
  prjprc AS Tells_if_project_price_is_used_on_this_order,
  prttxd AS How_to_treat_and_print_delivery_text,
  prttxf AS How_to_treat_and_print_fotting_text,
  prttxg AS How_to_treat_and_print_general_text,
  prttxh AS How_to_treat_and_print_heading_text,
  rcvdat AS Expected_receiving_date_at_reciever,
  rcvfrm AS Receival_slash_Delivery_from_Time_of_Date,
  rcvnam AS Receivers_name_slash_description,
  rcvunt AS Receival_slash_Delivery_until_Time_of_Date,
  regdat AS Entered_or_Registrated_Date,
  rutcod AS Route_identification_code,
  sapcod AS Seller__slash__Salesperson_identification_code,
  sbccod AS Service__and__Billing_Contract_Code,
  scccod AS Sales_Order_Color_Code,
  sdxcod AS Sales_Order_Discount_Matrix_Identification_Code,
  sifcod AS Fixed_Item_Discount_Identification_Code,
  sixcod AS Sales_Item_Discount_Matrix_Identification_Code,
  snginv AS Single_or_Consolidated_Invoice_by_Receiver_or_Payer,
  sngtrs AS Single_transport_is_required,
  soahnd AS Sales_Order_Approval_Handling,
  sornum AS Sales_order_number,
  splcod AS Sales_Price_List_Code,
  sysddn AS System_discount_numeric_value,
  sysddt AS System_discount_type,
  sysddv AS System_discount_value,
  tdlcod AS Terms_of_delivery_identification_code,
  tdlown AS tdlown_Terms_defined_for_this_specific_owner,
  tpycod AS Terms_of_payment_identification_code,
  tpyown AS tpyown_Terms_defined_for_this_specific_owner,
  trfhst AS Transferred_to_sales_history_log,
  trfsta AS Transferred_to_statistics,
  trssts AS Transport_plan_status,
  txtdlv AS External_Text__slash__Comments_Delivery,
  txtfot AS External_Text__slash__Comments_Footing,
  txtgen AS Internal_Text__slash__Comments,
  txthed AS External_Text__slash__Comments_Heading,
  txtinv AS External_text__slash__Comments_Invoice,
  usemai AS Service__and__Billing_Use_Main_Reference,
  useref AS Service__and__Billing_Use_Reference,
  usrhld AS Transaction_Put_on_Hold_by_User,
  vatcod AS Value_added_tax_identification_code,
  vatuse AS How_to_Default_VAT_on_an_Order_Line,
  wtrcod AS Way_of_transport_identification_code,
  wtrown AS wtrown_Terms_defined_for_this_specific_owner,
  xtccod AS External_trade_catalogue
FROM clockwork_consolidated.rainbow_soh