MODEL (
  column_descriptions (
    _entry_caused_by = ' Entry Caused by',
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    actual_date_related_to_expiry_date = 'Actual Date related to Expiry Date',
    actual_cost_value = 'Actual cost value',
    actual_sales_price = 'Actual sales price',
    actuale_quantity_to_be_invoiced_now = 'Actuale Quantity to be Invoiced Now',
    agent_identification_code__item_owner_or_salesperson_ = 'Agent identification code ( item owner or salesperson )',
    area_per_unit_or_in_total = 'Area per Unit or in Total',
    arrived_quantity = 'Arrived quantity',
    assembled_quantity = 'Assembled quantity',
    company_identification_code = 'Company identification code',
    confirmed_quantity = 'Confirmed quantity',
    cost_centre_identification_code = 'Cost centre identification code',
    country_of_origindot = 'Country of origin.',
    credit_reference_transaction_number = 'Credit Reference Transaction Number',
    credit_reference_transaction_sequence = 'Credit Reference Transaction Sequence',
    credit_transaction_reference_type = 'Credit Transaction Reference Type',
    current_despatch_date = 'Current Despatch Date',
    current_receiving_date = 'Current Receiving Date',
    customs_tariff_number_identification_code = 'Customs Tariff Number Identification Code',
    deadline_date_and_time_for_picking_list_generation = 'Deadline (Date and Time) for Picking List Generation',
    defines_if_individes_have_been_selected_for_this_line = 'Defines if individes have been selected for this line',
    delivered_quantity = 'Delivered quantity',
    delivery_marking = 'Delivery Marking',
    delivery_reference_code = 'Delivery Reference Code',
    department_identification_code = 'Department identification code',
    dynamic_financial_information_sequence_number = 'Dynamic Financial Information Sequence Number',
    ear_hyphen_code_identification_code = 'EAR-Code Identification Code',
    edi__hyphen__message_status_indicator = 'EDI - message status indicator',
    entered_or_registrated_date = 'Entered or Registrated Date',
    entry_form__hyphen__where_extra_lines_are_added = 'Entry Form - Where Extra Lines are Added',
    estimated_cost_value = 'Estimated cost value',
    exclude_item_on_external_documents = 'Exclude Item on External Documents',
    exclude_item_on_invoice_dcuments = 'Exclude Item on Invoice Dcuments',
    exclude_item_on_transport_documents = 'Exclude Item on Transport Documents',
    exclude_from_individ_handling = 'Exclude from Individ Handling',
    expiration_date_related_to_quotation_or_loan = 'Expiration Date related to Quotation or Loan',
    external_comments__slash__text = 'External Comments / Text',
    external_contract__slash__agreement_number = 'External Contract / Agreement Number',
    external_item_identification_code = 'External Item Identification Code',
    external_item_name__slash__description = 'External Item Name / Description',
    external_sequence_number_i_customers_item_catalogue = 'External Sequence Number i Customers Item Catalogue',
    external_text__slash__comments_invoice = 'External Text / Comments: Invoice',
    external_trade_catalogue_identification_code = 'External Trade Catalogue Identification Code',
    external_quantity_to_be_picked_not_in_stock = 'External quantity to be picked: not in stock',
    first_confirmed_despatch_date = 'First Confirmed Despatch Date',
    first_confirmed_receiving_date = 'First Confirmed Receiving Date',
    first_or_next_delivery_due_on_date = 'First or next delivery due on date',
    fixed_item_discount_identification_code = 'Fixed Item Discount Identification Code',
    gross_area_in_m2 = 'Gross Area in m2',
    gross_price = 'Gross price',
    gross_volume_in_dm3 = 'Gross volume in dm3',
    gross_weight_in_kilos = 'Gross weight in kilos',
    how_to_treat_and_print_general_text = 'How to treat and print general text',
    how_to_treat_and_print_item_text = 'How to treat and print item text',
    identifier_entry_form = 'Identifier Entry Form',
    indicates_if_line_is_currently_on_hold_or_not = 'Indicates if line is currently on hold or not',
    individ_identification_number = 'Individ Identification Number',
    information_created_date = 'Information Created Date',
    information_created_by_user = 'Information created by user',
    information_last_changed_by_user = 'Information last changed by user',
    information_last_changed_date = 'Information last changed date',
    internal_comments__slash__text = 'Internal Comments / Text',
    invoiced_quantity = 'Invoiced quantity',
    item_classification_catalogue_identification = 'Item Classification Catalogue Identification',
    item_classification_reference_code_in_catalogue = 'Item Classification Reference Code in Catalogue',
    item_controlled_addition = 'Item controlled addition',
    keep_original_cost = 'Keep Original Cost',
    last_delivered_on_date = 'Last Delivered on Date',
    last_statuscode_on_line = 'Last statuscode on line',
    line_hyphen_item_is_updated_in_stock = 'Line-item is updated in stock',
    line_item_code_according_to_type = 'Line item code according to type',
    line_put_on_hold_caused_by = 'Line put on hold caused by',
    line_type_identifying_different_types_of_item_on_a_line = 'Line type: identifying different types of item on a line',
    linked_to_engineer_to_order = 'Linked to Engineer to Order',
    manual_discount_numeric_value = 'Manual discount numeric value',
    manual_discount_type = 'Manual discount type',
    manual_discount_value = 'Manual discount value',
    master_additional_sales_sequence_number = 'Master Additional Sales Sequence Number',
    master_certificate_sequence_number_reference = 'Master Certificate Sequence Number Reference',
    master_kit_sequence_number_reference = 'Master Kit Sequence Number Reference',
    master_in_additonal_sales_item = 'Master in Additonal Sales Item',
    master_or_child_in_certificates = 'Master or Child in Certificates',
    master_or_child_in_kit = 'Master or Child in Kit',
    name_or_description_of_line_item = 'Name or description of line item',
    net_area_in_m2 = 'Net Area in m2',
    net_volume_in_dm3 = 'Net volume in dm3',
    net_weight_in_kilos = 'Net weight in kilos',
    order_form_identification_code = 'Order Form Identification Code',
    order_form_linked_to_requesting_transaction = 'Order Form Linked to Requesting Transaction',
    original_item_identification_code = 'Original Item Identification Code',
    originally_available_quantity_at_order_entry = 'Originally available quantity at order entry',
    originally_base_sales_price = 'Originally base sales price',
    originally_ordered_quantity = 'Originally ordered quantity',
    overrided_customs_net_price = 'Overrided Customs Net Price',
    owner_controlled_addition = 'Owner controlled addition',
    owners_requested_date = 'Owners Requested Date',
    packed_quantity = 'Packed quantity',
    pending__slash__backorder_quantity = 'Pending / backorder quantity',
    picked_quantity = 'Picked quantity',
    position_number = 'Position number',
    price_dimension = 'Price dimension',
    produced_cost_to_be_booked = 'Produced cost to be booked',
    produced_quantity = 'Produced quantity',
    project_identification_code = 'Project identification code',
    purchased_cost_to_be_booked = 'Purchased cost to be booked',
    purchased_quantity = 'Purchased quantity',
    quantity_reserved_but_not_picked_from_production = 'Quantity Reserved but not Picked from Production',
    quantity_reserved_but_not_picked_from_purchase = 'Quantity Reserved but not Picked from Purchase',
    quantity_received = 'Quantity received',
    quantity_returned = 'Quantity returned',
    quantity_to_be_returned = 'Quantity to be Returned',
    quantity_to_be_arrived = 'Quantity to be arrived',
    quantity_to_be_assembled = 'Quantity to be assembled',
    quantity_to_be_confirmed = 'Quantity to be confirmed',
    quantity_to_be_delivered = 'Quantity to be delivered',
    quantity_to_be_invoiced = 'Quantity to be invoiced',
    quantity_to_be_packed = 'Quantity to be packed',
    quantity_to_be_picked_in_stock = 'Quantity to be picked in stock',
    quantity_to_be_produced = 'Quantity to be produced',
    quantity_to_be_purchased = 'Quantity to be purchased',
    quantity_to_be_received = 'Quantity to be received',
    quantity_to_be_reserved_in_stock = 'Quantity to be reserved in stock',
    receiving_slash_delivery_from_time_of_date = 'Receiving/Delivery from Time of Date',
    receiving_slash_delivery_until_time_of_date = 'Receiving/Delivery until Time of Date',
    relation_ratio_from_transaction_unit_to_base_unit = 'Relation Ratio from Transaction Unit to Base Unit',
    relation_type_from_transaction_unit_to_base_unit = 'Relation Type from Transaction Unit to Base Unit',
    requested_by_cw_user = 'Requested by CW User',
    reserved_quantity_in_stock = 'Reserved quantity in stock',
    sales_item_discount_matrix_identification_code = 'Sales Item Discount Matrix Identification Code',
    sales_price_list_identification_code = 'Sales Price List Identification Code',
    sales_order_line_number = 'Sales order line number',
    sales_order_line_sequence_number = 'Sales order line sequence number',
    sales_order_number = 'Sales order number',
    sales_price_method = 'Sales price method',
    service__and__billing_bill_hyphen_of_hyphen_delivery_sequence_n = 'Service & Billing Bill-of-Delivery Sequence No. reference',
    sold_quantity = 'Sold quantity',
    system_discount_numeric_value = 'System discount numeric value',
    system_discount_type = 'System discount type',
    system_discount_value = 'System discount value',
    to_be_invoied_as_an_addition_to_invoice_plan = 'To be Invoied as an Addition to Invoice Plan',
    total_direct_cost_value = 'Total direct cost value',
    total_direct_discount_percentage = 'Total direct discount percentage',
    total_direct_discount_value = 'Total direct discount value',
    total_indirect_cost_value = 'Total indirect cost value',
    total_indirect_discount_percentage = 'Total indirect discount percentage',
    total_indirect_discount_value = 'Total indirect discount value',
    total_line_value = 'Total line value',
    total_number_of_pallets = 'Total number of pallets',
    total_number_of_parcels = 'Total number of parcels',
    trade_catalogue_item_code = 'Trade Catalogue Item Code',
    transaction_unit_identification_code = 'Transaction unit identification code',
    transfer_to_clockwork_service__and__billing = 'Transfer to ClockWork Service & Billing',
    value_added_taxcode = 'Value added taxcode',
    variant_string_identification_code = 'Variant string identification code',
    volume_per_unit_or_total = 'Volume per unit or total',
    warehouse_identification_code = 'Warehouse identification code',
    weight_per_unit_or_total = 'Weight per unit or total'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  actcst AS Actual_cost_value,
  actdat AS Actual_Date_related_to_Expiry_Date,
  adsseq AS Master_Additional_Sales_Sequence_Number,
  agncod AS Agent_identification_code__item_owner_or_salesperson_,
  agrnum AS External_Contract__slash__Agreement_Number,
  am2typ AS Area_per_Unit_or_in_Total,
  bodseq AS Service__and__Billing_Bill_hyphen_of_hyphen_Delivery_Sequence_N,
  cbchld AS Line_put_on_hold_caused_by,
  cbycod AS _Entry_Caused_by,
  chgdat AS Information_last_changed_date,
  chgusr AS Information_last_changed_by_user,
  cnfdsp AS First_Confirmed_Despatch_Date,
  cnfrcv AS First_Confirmed_Receiving_Date,
  cntori AS Country_of_origindot,
  compny AS Company_identification_code,
  credat AS Information_Created_Date,
  creref AS Credit_Reference_Transaction_Number,
  creseq AS Credit_Reference_Transaction_Sequence,
  creusr AS Information_created_by_user,
  csccod AS Cost_centre_identification_code,
  cstcod AS Customs_Tariff_Number_Identification_Code,
  cstprc AS Overrided_Customs_Net_Price,
  ctfseq AS Master_Certificate_Sequence_Number_Reference,
  cwsbtr AS Transfer_to_ClockWork_Service__and__Billing,
  dfiseq AS Dynamic_Financial_Information_Sequence_Number,
  dlvdat AS First_or_next_delivery_due_on_date,
  dlvmrk AS Delivery_Marking,
  dptcod AS Department_identification_code,
  dspdat AS Current_Despatch_Date,
  earcod AS EAR_hyphen_Code_Identification_Code,
  edists AS EDI__hyphen__message_status_indicator,
  entfrm AS Entry_Form__hyphen__Where_Extra_Lines_are_Added,
  estcst AS Estimated_cost_value,
  etocod AS Linked_to_Engineer_to_Order,
  excexd AS Exclude_Item_on_External_Documents,
  excidn AS Exclude_from_Individ_Handling,
  excivd AS Exclude_Item_on_Invoice_Dcuments,
  exctrd AS Exclude_Item_on_Transport_Documents,
  expdat AS Expiration_Date_related_to_Quotation_or_Loan,
  extcod AS Trade_Catalogue_Item_Code,
  extitm AS External_Item_Identification_Code,
  extnam AS External_Item_Name__slash__Description,
  extseq AS External_Sequence_Number_i_Customers_Item_Catalogue,
  grsam2 AS Gross_Area_in_m2,
  grsvdm AS Gross_volume_in_dm3,
  grswkg AS Gross_weight_in_kilos,
  icscat AS Item_Classification_Catalogue_Identification,
  icsref AS Item_Classification_Reference_Code_in_Catalogue,
  idfent AS Identifier_Entry_Form,
  idncod AS Individ_Identification_Number,
  idnsel AS Defines_if_individes_have_been_selected_for_this_line,
  invnow AS Actuale_Quantity_to_be_Invoiced_Now,
  ipiadd AS To_be_Invoied_as_an_Addition_to_Invoice_Plan,
  itmadd AS Item_controlled_addition,
  kepcst AS Keep_Original_Cost,
  kitseq AS Master_Kit_Sequence_Number_Reference,
  lincod AS Line_item_code_according_to_type,
  linnam AS Name_or_description_of_line_item,
  linnum AS Sales_order_line_number,
  lintyp AS Line_type_identifying_different_types_of_item_on_a_line,
  lstdat AS Last_Delivered_on_Date,
  lststs AS Last_statuscode_on_line,
  manddn AS Manual_discount_numeric_value,
  manddt AS Manual_discount_type,
  manddv AS Manual_discount_value,
  mstads AS Master_in_Additonal_Sales_Item,
  mstctf AS Master_or_Child_in_Certificates,
  mstkit AS Master_or_Child_in_Kit,
  netam2 AS Net_Area_in_m2,
  netvdm AS Net_volume_in_dm3,
  netwkg AS Net_weight_in_kilos,
  numpal AS Total_number_of_pallets,
  numpcl AS Total_number_of_parcels,
  ofmcod AS Order_Form_Identification_Code,
  ofmreq AS Order_Form_Linked_to_Requesting_Transaction,
  onhold AS Indicates_if_line_is_currently_on_hold_or_not,
  orgitm AS Original_Item_Identification_Code,
  ownadd AS Owner_controlled_addition,
  owndat AS Owners_Requested_Date,
  pckdat AS Deadline_Date_and_Time_for_Picking_List_Generation,
  posnum AS Position_number,
  prcact AS Actual_sales_price,
  prcbas AS Originally_base_sales_price,
  prccst AS Purchased_cost_to_be_booked,
  prcdim AS Price_dimension,
  prcgrs AS Gross_price,
  prcmth AS Sales_price_method,
  prcrsv AS Quantity_Reserved_but_not_Picked_from_Purchase,
  prdcst AS Produced_cost_to_be_booked,
  prdrsv AS Quantity_Reserved_but_not_Picked_from_Production,
  prjcod AS Project_identification_code,
  prttxg AS How_to_treat_and_print_general_text,
  prttxi AS How_to_treat_and_print_item_text,
  q2barr AS Quantity_to_be_arrived,
  q2basm AS Quantity_to_be_assembled,
  q2bcnf AS Quantity_to_be_confirmed,
  q2bdlv AS Quantity_to_be_delivered,
  q2bext AS External_quantity_to_be_picked_not_in_stock,
  q2binv AS Quantity_to_be_invoiced,
  q2bpck AS Quantity_to_be_picked_in_stock,
  q2bpkd AS Quantity_to_be_packed,
  q2bprc AS Quantity_to_be_purchased,
  q2bprd AS Quantity_to_be_produced,
  q2brcv AS Quantity_to_be_received,
  q2bret AS Quantity_to_be_Returned,
  q2brsv AS Quantity_to_be_reserved_in_stock,
  qtyarr AS Arrived_quantity,
  qtyasm AS Assembled_quantity,
  qtyava AS Originally_available_quantity_at_order_entry,
  qtycnf AS Confirmed_quantity,
  qtydlv AS Delivered_quantity,
  qtyinv AS Invoiced_quantity,
  qtyord AS Originally_ordered_quantity,
  qtypck AS Picked_quantity,
  qtypkd AS Packed_quantity,
  qtypnd AS Pending__slash__backorder_quantity,
  qtyprc AS Purchased_quantity,
  qtyprd AS Produced_quantity,
  qtyrcv AS Quantity_received,
  qtyret AS Quantity_returned,
  qtyrsv AS Reserved_quantity_in_stock,
  qtysld AS Sold_quantity,
  rcvdat AS Current_Receiving_Date,
  rcvfrm AS Receiving_slash_Delivery_from_Time_of_Date,
  rcvunt AS Receiving_slash_Delivery_until_Time_of_Date,
  refcod AS Delivery_Reference_Code,
  reftyp AS Credit_Transaction_Reference_Type,
  regdat AS Entered_or_Registrated_Date,
  requsr AS Requested_by_CW_User,
  seqnum AS Sales_order_line_sequence_number,
  sifcod AS Fixed_Item_Discount_Identification_Code,
  sixcod AS Sales_Item_Discount_Matrix_Identification_Code,
  sornum AS Sales_order_number,
  splcod AS Sales_Price_List_Identification_Code,
  stcupd AS Line_hyphen_item_is_updated_in_stock,
  sysddn AS System_discount_numeric_value,
  sysddt AS System_discount_type,
  sysddv AS System_discount_value,
  totadc AS Total_direct_cost_value,
  totaic AS Total_indirect_cost_value,
  totddp AS Total_direct_discount_percentage,
  totddv AS Total_direct_discount_value,
  totidp AS Total_indirect_discount_percentage,
  totidv AS Total_indirect_discount_value,
  totval AS Total_line_value,
  trnrra AS Relation_Ratio_from_Transaction_Unit_to_Base_Unit,
  trnrty AS Relation_Type_from_Transaction_Unit_to_Base_Unit,
  trnunt AS Transaction_unit_identification_code,
  txtgen AS Internal_Comments__slash__Text,
  txtinv AS External_Text__slash__Comments_Invoice,
  txtitm AS External_Comments__slash__Text,
  vatcod AS Value_added_taxcode,
  vdmtyp AS Volume_per_unit_or_total,
  vrscod AS Variant_string_identification_code,
  whscod AS Warehouse_identification_code,
  wkgtyp AS Weight_per_unit_or_total,
  xtccod AS External_Trade_Catalogue_Identification_Code
FROM clockwork_consolidated.rainbow_sol