MODEL (
  column_descriptions (
    _default_line_type = ' Default Line Type',
    _data_modified_utc = 'When data was modified at source.',
    _metadata_modified_utc = 'When data was inserted here.',
    _source_catalog = 'Which catalog the source came from.',
    accept_self_hyphen_billing_invoice = 'Accept Self-billing Invoice',
    account_manager = 'Account Manager',
    additional_supplier_name = 'Additional Supplier Name',
    address_control_indicates_that_the_address_is_to_be_verified_at = 'Address control: indicates that the address is to be verified at transaction entry',
    agent_identification_code = 'Agent identification code',
    allow_automatic_order_from_request = 'Allow Automatic Order From Request',
    approved_for_business_from_date = 'Approved for Business from Date',
    approved_for_business_until_date = 'Approved for Business until Date',
    automatic_generate_purchase_order_based_on_requirement__slash__ = 'Automatic Generate Purchase Order based on Requirement / Reorder',
    bank_account_number = 'Bank Account Number',
    barcode_technical_type = 'Barcode Technical Type',
    bonus_calculation_method = 'Bonus calculation method',
    business_approval_classification = 'Business approval classification',
    cause_by_code_for_delivery_stop = 'Cause by code for delivery stop',
    chain_identification_code = 'Chain Identification Code',
    chain_member_from_date = 'Chain Member from date',
    chain_member_until_date = 'Chain Member until Date',
    company_identification_code = 'Company identification code',
    confirm_purchase_forecast_order = 'Confirm Purchase Forecast Order',
    consignment_order_reference_on_receivers_reference_ii = 'Consignment Order Reference on Receivers Reference II',
    consignment_on_separate_order = 'Consignment on Separate Order',
    corporate_client_identification_code = 'Corporate Client Identification Code',
    country_identification_code = 'Country identification code',
    credit_balance_method_indicates_how_to_check_credit_balance = 'Credit balance method: indicates how to check credit balance',
    credit_balance_setup_code = 'Credit balance setup code',
    currency_identification_code = 'Currency identification code',
    currency_type = 'Currency type',
    current_abc_classification_forecast_value = 'Current ABC Classification: Forecast Value',
    current_abc_classification_forecast_value_changed_date = 'Current ABC Classification: Forecast Value Changed Date',
    current_abc_classification_forecast_value_changed_by_user = 'Current ABC Classification: Forecast Value Changed by User',
    current_abc_classification_extra_use = 'Current ABC classification: extra use',
    current_abc_classification_extra_use_last_changed_by_user = 'Current ABC classification: extra use: last changed by user',
    current_abc_classification_extra_use_last_changed_date = 'Current ABC classification: extra use last changed date',
    current_abc_classification_purchase_value = 'Current ABC classification: purchase value',
    current_abc_classification_purchase_value_last_changed_by_user = 'Current ABC classification: purchase value: last changed by user',
    current_abc_classification_purchase_value_last_changed_date = 'Current ABC classification: purchase value: last changed date',
    current_abc_classification_service_level = 'Current ABC classification: service level',
    current_abc_classification_service_level_last_changed_by_user = 'Current ABC classification: service level: last changed by user',
    current_abc_classification_service_level_last_changed_date = 'Current ABC classification: service level: last changed date',
    current_service_level_value_delivery = 'Current service level value: delivery',
    current_service_level_value_delivery_last_changed_by_user = 'Current service level value: delivery: last changed by user',
    current_service_level_value_delivery_last_changed_date = 'Current service level value: delivery: last changed date',
    current_service_level_value_quality_assurance_control = 'Current service level value: quality assurance control',
    deadline_for_reply_on_forecast_order_in_days = 'Deadline for Reply on Forecast Order in Days',
    default_external_trade_catalogue = 'Default external trade catalogue',
    default_sales_price_method = 'Default sales price method',
    delivery_address_line_1 = 'Delivery Address: Line 1',
    delivery_address_line_2 = 'Delivery Address: Line 2',
    delivery_address_line_3 = 'Delivery Address: Line 3',
    delivery_address_line_4 = 'Delivery Address: Line 4',
    delivery_group_identification_code = 'Delivery group identification code',
    department_identification_code = 'Department identification code',
    district_identification_code = 'District identification code',
    document_set_identification_code = 'Document Set identification code',
    eori__hyphen__economic_operators_registration_and_identificatio = 'EORI - Economic Operators Registration and Identification Number',
    enable_delivery_address_entry = 'Enable Delivery Address Entry',
    enable_visiting_address_entry = 'Enable Visiting Address Entry',
    entry_profile_code = 'Entry Profile Code',
    environment_class_or_classification = 'Environment Class or Classification',
    environment_class_or_classification_valid_from_date = 'Environment Class or Classification Valid from Date',
    environment_class_or_classification_valid_until_date = 'Environment Class or Classification Valid until Date',
    european_community_country_code = 'European Community Country Code',
    external_update_status = 'External update status',
    fixed_discount_percentage = 'Fixed discount percentage',
    forwarder_agent_identification_code = 'Forwarder agent identification code',
    forwarder_identification_code = 'Forwarder identification code',
    general_ranking_by_dice = 'General Ranking by Dice',
    general_text__slash__comments = 'General Text / Comments',
    generate_purchase_forecast_order = 'Generate Purchase Forecast Order',
    hide_supplier_from_search_functions = 'Hide Supplier from Search Functions',
    horizin_in_number_of_days_to_accept_self_hyphen_billing_invoice = 'Horizin in Number of Days to Accept Self-billing Invoice',
    how_to_notify_supplier_on_forecast_order = 'How to Notify Supplier on Forecast Order',
    iban_bank_account = 'IBAN Bank Account',
    indicated_if_contract_discounts_is_defined_for_this_supplier = 'Indicated if contract discounts is defined for this supplier',
    indicates_if_contract_prices_is_defined_for_this_supplier = 'Indicates if contract prices is defined for this supplier',
    indicates_if_delivery_groups_are_defined_for_this_owner_only = 'Indicates if delivery groups are defined for this owner only',
    indicates_if_terms_of_payment_is_defined_for_this_supplier_only = 'Indicates if terms of payment is defined for this supplier only.',
    information_created_date = 'Information Created Date',
    information_last_changed_date = 'Information Last Changed Date',
    information_last_changed_by_user = 'Information Last Changed by User',
    information_created_by_user = 'Information created by user',
    internal_or_external_supplier = 'Internal or External Supplier',
    invoice_approval_stop = 'Invoice Approval Stop',
    invoice_frequence__indicates_how_often_the_supplier_will_be_inv = 'Invoice frequence  indicates how often the supplier will be invoiced.',
    language_identification_code = 'Language Identification Code',
    leadtime_for_ex_hyphen_works_terms_part_of_standard_leadtime = 'Leadtime for ex-works terms: part of standard leadtime',
    leadtime_for_general_and_internal_handling_of_goods_in_and_out = 'Leadtime for general and internal handling of goods in and out',
    mailing__slash__postal_address_line_1 = 'Mailing / Postal Address: Line 1',
    mailing__slash__postal_address_line_2 = 'Mailing / Postal Address: Line 2',
    mailing__slash__postal_address_line_3 = 'Mailing / Postal Address: Line 3',
    mailing__slash__postal_address_line_4 = 'Mailing / Postal Address: Line 4',
    main_contact_person = 'Main Contact Person',
    markup_percentage_on_default_salesprice = 'Markup percentage on default salesprice',
    master_external_update_status = 'Master External Update Status',
    master_in_bulletin_board = 'Master in Bulletin Board',
    master_in_remarks__slash__notes = 'Master in Remarks / Notes',
    notify_supplier_of_new_order = 'Notify Supplier of New Order',
    order_priority = 'Order Priority',
    organization_or_registration_number = 'Organization or Registration Number',
    our_identification_code_in_suppliers_system = 'Our Identification Code in Suppliers System',
    partial_delivery_indicates_if_and_how_part_deliveries_are_allow = 'Partial delivery: indicates if and how part deliveries are allowed',
    phone_number_suppliers_main_contact_person = 'Phone number suppliers main contact person',
    planned_abc_classification_extra_use = 'Planned ABC classification: extra use',
    planned_abc_classification_purchase_value = 'Planned ABC classification: purchase value',
    planned_abc_classification_service_level = 'Planned ABC classification: service level',
    planned_abc_hyphen_classification_forecast_value = 'Planned ABC-Classification: Forecast Value',
    planned_service_level_value_delivery = 'Planned service level value: delivery',
    planned_service_level_value_quality_assurance_control = 'Planned service level value: quality assurance control',
    post_account_number = 'Post account number',
    purchaser_identification_code = 'Purchaser identification code',
    region_identification_code = 'Region identification code',
    swift_bank_code = 'SWIFT Bank Code',
    sales_order_discount_matrix_identification_code = 'Sales order discount matrix identification code',
    sales_order_fixed_item_discount_identification_code = 'Sales order fixed item discount identification code',
    sales_order_item_discount_matrix_identification_code = 'Sales order item discount matrix identification code',
    sales_price_list_code = 'Sales price list code',
    shortname = 'Shortname',
    shortnumber = 'Shortnumber',
    split_orders_at_this_level_when_generating = 'Split Orders at this Level When Generating',
    standard_leadtime = 'Standard leadtime',
    supplier_code_in_external_system = 'Supplier Code in External System',
    supplier_entry_form = 'Supplier Entry Form',
    supplier_group_identification_code = 'Supplier Group Identification Code',
    supplier_linked_to_owner_code_according_to_type = 'Supplier Linked to Owner Code according to Type',
    supplier_linked_to_owner_type = 'Supplier Linked to Owner Type',
    supplier_category_identification_code = 'Supplier category identification code',
    supplier_identification_code = 'Supplier identification code',
    supplier_type_identification_code = 'Supplier type identification code',
    suppliers_active_or_passive_status_cude = 'Suppliers active or passive status cude',
    suppliers_lifecycle_status_code = 'Suppliers lifecycle status code',
    suppliers_name__slash__description = 'Suppliers name / description',
    telefax_number_to_suppliers_switchboard = 'Telefax number to suppliers switchboard',
    telephon_number_to_suppliers_warehouse_office_slash_department_ = 'Telephon number to suppliers warehouse office/department/manager',
    telephone_number_to_suppliers_forwarder_office_slash_department = 'Telephone number to suppliers forwarder office/department/manager',
    telephone_number_to_suppliers_purchase_office_slash_department_ = 'Telephone number to suppliers purchase office/department/manager',
    telephone_number_to_suppliers_service_office_slash_department_s = 'Telephone number to suppliers service office/department/manager',
    telephone_number_to_suppliers_swithcboard = 'Telephone number to suppliers swithcboard',
    telex_number_to_suppliers_switchboard = 'Telex number to suppliers switchboard',
    temporary_delivery_stop_to_and_forth_this_supplier = 'Temporary delivery stop to and forth this supplier',
    terms_of_payment_identification_code = 'Terms of payment identification code',
    use_self_hyphen_billing_invoice = 'Use Self-billing Invoice',
    value_added_tax_registration_number = 'Value Added Tax Registration Number',
    value_added_tax_identification_code = 'Value added tax identification code',
    visiting_address_line_1 = 'Visiting Address: Line 1',
    visiting_address_line_2 = 'Visiting Address: Line 2',
    visiting_address_line_3 = 'Visiting Address: Line 3',
    visiting_address_line_4 = 'Visiting Address: Line 4',
    visma_business__hyphen__bitmapped_preferences = 'Visma Business - bitmapped preferences',
    warehouse_identification_code = 'Warehouse Identification Code',
    csvlqd_current_service_level_value_quality_assurance_control_last_chan = 'Current service level value: quality assurance control: last changed date',
    csvlqu_current_service_level_value_quality_assurance_control_last_chan = 'Current service level value: quality assurance control: last changed by user'
  )
);

SELECT
  _data_modified_utc AS _data_modified_utc,
  _metadata_modified_utc AS _metadata_modified_utc,
  _source_catalog AS _source_catalog,
  abcexd AS Current_ABC_classification_extra_use_last_changed_date,
  abcexu AS Current_ABC_classification_extra_use_last_changed_by_user,
  abcfvd AS Current_ABC_Classification_Forecast_Value_Changed_Date,
  abcfvu AS Current_ABC_Classification_Forecast_Value_Changed_by_User,
  abcpvd AS Current_ABC_classification_purchase_value_last_changed_date,
  abcpvu AS Current_ABC_classification_purchase_value_last_changed_by_user,
  abcsld AS Current_ABC_classification_service_level_last_changed_date,
  abcslu AS Current_ABC_classification_service_level_last_changed_by_user,
  acmcod AS Account_Manager,
  adrctr AS Address_control_indicates_that_the_address_is_to_be_verified_at,
  agncod AS Agent_identification_code,
  agporp AS Automatic_Generate_Purchase_Order_based_on_Requirement__slash__,
  appcls AS Business_approval_classification,
  appfda AS Approved_for_Business_from_Date,
  appuda AS Approved_for_Business_until_Date,
  asupnm AS Additional_Supplier_Name,
  auorrq AS Allow_Automatic_Order_From_Request,
  bankac AS Bank_Account_Number,
  barcod AS Barcode_Technical_Type,
  bnsccm AS Bonus_calculation_method,
  cabcex AS Current_ABC_classification_extra_use,
  cabcfv AS Current_ABC_Classification_Forecast_Value,
  cabcpv AS Current_ABC_classification_purchase_value,
  cabcsl AS Current_ABC_classification_service_level,
  ccdlvs AS Cause_by_code_for_delivery_stop,
  chgdat AS Information_Last_Changed_Date,
  chgusr AS Information_Last_Changed_by_User,
  chncod AS Chain_Identification_Code,
  chnfrm AS Chain_Member_from_date,
  chnunt AS Chain_Member_until_Date,
  clicod AS Corporate_Client_Identification_Code,
  cnfpfc AS Confirm_Purchase_Forecast_Order,
  cnsrr2 AS Consignment_Order_Reference_on_Receivers_Reference_II,
  cnssep AS Consignment_on_Separate_Order,
  cntcod AS Country_identification_code,
  compny AS Company_identification_code,
  crbcod AS Credit_balance_setup_code,
  crbplm AS Credit_balance_method_indicates_how_to_check_credit_balance,
  credat AS Information_Created_Date,
  creusr AS Information_created_by_user,
  csldld AS Current_service_level_value_delivery_last_changed_date,
  csldlu AS Current_service_level_value_delivery_last_changed_by_user,
  csldlv AS Current_service_level_value_delivery,
  csvclq AS Current_service_level_value_quality_assurance_control,
  csvlqd AS csvlqd_Current_service_level_value_quality_assurance_control_last_chan,
  csvlqu AS csvlqu_Current_service_level_value_quality_assurance_control_last_chan,
  ctcprs AS Main_Contact_Person,
  ctrdis AS Indicated_if_contract_discounts_is_defined_for_this_supplier,
  ctrpri AS Indicates_if_contract_prices_is_defined_for_this_supplier,
  curcod AS Currency_identification_code,
  curtyp AS Currency_type,
  dcscod AS Document_Set_identification_code,
  defprc AS Default_sales_price_method,
  dicing AS General_Ranking_by_Dice,
  dladr1 AS Delivery_Address_Line_1,
  dladr2 AS Delivery_Address_Line_2,
  dladr3 AS Delivery_Address_Line_3,
  dladr4 AS Delivery_Address_Line_4,
  dlgcod AS Delivery_group_identification_code,
  dlgown AS Indicates_if_delivery_groups_are_defined_for_this_owner_only,
  dlvstp AS Temporary_delivery_stop_to_and_forth_this_supplier,
  dstcod AS District_identification_code,
  ecland AS European_Community_Country_Code,
  ecregn AS EORI__hyphen__Economic_Operators_Registration_and_Identificatio,
  enblda AS Enable_Delivery_Address_Entry,
  enblva AS Enable_Visiting_Address_Entry,
  entfrm AS Supplier_Entry_Form,
  envcls AS Environment_Class_or_Classification,
  envfda AS Environment_Class_or_Classification_Valid_from_Date,
  envuda AS Environment_Class_or_Classification_Valid_until_Date,
  extcod AS Supplier_Code_in_External_System,
  extprf AS Visma_Business__hyphen__bitmapped_preferences,
  exwldt AS Leadtime_for_ex_hyphen_works_terms_part_of_standard_leadtime,
  faxswt AS Telefax_number_to_suppliers_switchboard,
  fcoddl AS Deadline_for_Reply_on_Forecast_Order_in_Days,
  fixdsc AS Fixed_discount_percentage,
  fwacod AS Forwarder_agent_identification_code,
  fwdcod AS Forwarder_identification_code,
  genpfc AS Generate_Purchase_Forecast_Order,
  gentxt AS General_Text__slash__Comments,
  hidsrc AS Hide_Supplier_from_Search_Functions,
  hndldt AS Leadtime_for_general_and_internal_handling_of_goods_in_and_out,
  ibancd AS IBAN_Bank_Account,
  intext AS Internal_or_External_Supplier,
  invapr AS Invoice_Approval_Stop,
  invfrq AS Invoice_frequence__indicates_how_often_the_supplier_will_be_inv,
  lintyp AS _Default_Line_Type,
  lngcod AS Language_Identification_Code,
  maadr1 AS Mailing__slash__Postal_Address_Line_1,
  maadr2 AS Mailing__slash__Postal_Address_Line_2,
  maadr3 AS Mailing__slash__Postal_Address_Line_3,
  maadr4 AS Mailing__slash__Postal_Address_Line_4,
  markup AS Markup_percentage_on_default_salesprice,
  mstbbs AS Master_in_Bulletin_Board,
  mstmrk AS Master_in_Remarks__slash__Notes,
  mstupe AS Master_External_Update_Status,
  ntffco AS How_to_Notify_Supplier_on_Forecast_Order,
  ntfown AS Notify_Supplier_of_New_Order,
  ourcod AS Our_Identification_Code_in_Suppliers_System,
  owncod AS Supplier_Linked_to_Owner_Code_according_to_Type,
  owntyp AS Supplier_Linked_to_Owner_Type,
  pabcex AS Planned_ABC_classification_extra_use,
  pabcfv AS Planned_ABC_hyphen_Classification_Forecast_Value,
  pabcpv AS Planned_ABC_classification_purchase_value,
  pabcsl AS Planned_ABC_classification_service_level,
  pdpcod AS Department_identification_code,
  phnext AS Phone_number_suppliers_main_contact_person,
  phnfwd AS Telephone_number_to_suppliers_forwarder_office_slash_department,
  phnprc AS Telephone_number_to_suppliers_purchase_office_slash_department_,
  phnsvc AS Telephone_number_to_suppliers_service_office_slash_department_s,
  phnswt AS Telephone_number_to_suppliers_swithcboard,
  phnwhs AS Telephon_number_to_suppliers_warehouse_office_slash_department_,
  postac AS Post_account_number,
  prccod AS Purchaser_identification_code,
  prfcod AS Entry_Profile_Code,
  pricod AS Order_Priority,
  psvcld AS Planned_service_level_value_delivery,
  psvclq AS Planned_service_level_value_quality_assurance_control,
  ptdlvm AS Partial_delivery_indicates_if_and_how_part_deliveries_are_allow,
  regcod AS Region_identification_code,
  regnum AS Organization_or_Registration_Number,
  sbiacp AS Accept_Self_hyphen_billing_Invoice,
  sbihrz AS Horizin_in_Number_of_Days_to_Accept_Self_hyphen_billing_Invoice,
  sbiuse AS Use_Self_hyphen_billing_Invoice,
  sctcod AS Supplier_category_identification_code,
  sdxcod AS Sales_order_discount_matrix_identification_code,
  sgrcod AS Supplier_Group_Identification_Code,
  sifcod AS Sales_order_fixed_item_discount_identification_code,
  sixcod AS Sales_order_item_discount_matrix_identification_code,
  splcod AS Sales_price_list_code,
  splord AS Split_Orders_at_this_Level_When_Generating,
  srtnam AS Shortname,
  srtnum AS Shortnumber,
  stdldt AS Standard_leadtime,
  stycod AS Supplier_type_identification_code,
  supact AS Suppliers_active_or_passive_status_cude,
  supcod AS Supplier_identification_code,
  suplcy AS Suppliers_lifecycle_status_code,
  supnam AS Suppliers_name__slash__description,
  swiftc AS SWIFT_Bank_Code,
  tlxswt AS Telex_number_to_suppliers_switchboard,
  tpycod AS Terms_of_payment_identification_code,
  tpyown AS Indicates_if_terms_of_payment_is_defined_for_this_supplier_only,
  updeco AS External_update_status,
  vatcod AS Value_added_tax_identification_code,
  vatnum AS Value_Added_Tax_Registration_Number,
  viadr1 AS Visiting_Address_Line_1,
  viadr2 AS Visiting_Address_Line_2,
  viadr3 AS Visiting_Address_Line_3,
  viadr4 AS Visiting_Address_Line_4,
  whscod AS Warehouse_Identification_Code,
  xtccod AS Default_external_trade_catalogue
FROM clockwork_consolidated.rainbow_sup