
MODEL (
    kind VIEW
);

SELECT
    adcsf1 AS 'additional_cost_form_1',
	adcsf2 AS 'additioal_cost_form_2',
	adcst1 AS 'additional_cost_type_1',
	adcst2 AS 'additional_cost_type_2',
	adcsv1 AS 'additional_cost_value_1',
	adcsv2 AS 'additioal_cost_value_2',
	adddsc AS 'additional_description',
	ageval AS 'evaluate_agreement_at_date',
	agporp AS 'auto_generate_purchase_orders_from_requirement_planning',
	agrnum AS 'agreement_number',
	agrqty AS 'totale_quantity_on_agreement',
	agrusd AS 'used_quantity_on_agreement',
	agvunt AS 'agreement_valid_until_date',
	altnum AS 'alternative_number_differentiates_conditions_for_same_item',
	cattyp AS 'external_catalogue_type',
	chgdat AS 'information_last_changed_date',
	chgusr AS 'information_last_changed_by_user',
	cntori AS 'country_of_origin',
	compny AS 'company_identification_code',
	cprmut AS 'cost_price_markup_type_percent__slash__per_unit',
	cprmuv AS 'cost_price_markup_value',
	cptwor AS 'copy_text_to_work_order',
	cpypor AS 'copy_description_to_order_line_comment',
	cpytxt AS 'copy_text__slash__comment_to_order_line_comment',
	credat AS 'information_created_date',
	creusr AS 'information_created_by_user',
	curcod AS 'currency_identification_code',
	curprc AS 'current_price_per_unit',
	dldact AS 'actual_number_of_delivery_days',
	dlddat AS 'delivery_dates_last_changed_date',
	dldmax AS 'maximum_number_of_delivery_days',
	dldmin AS 'minimum_number_of_delivery_days',
	dlvday AS 'standard_lead_time_in_days_including_transport__and__handling',
	dppmpc AS 'deviation_percentage_entry_point_for_a_major_price_change',
	dscmtx AS 'item_is_master_in_a_discount_matrix',
	eicact AS 'active__slash__passive_status',
	eiclcs AS 'life_cycle_status_code',
	eictxt AS 'general_text__slash__comments_to_item',
	envcls AS 'environment_class_or_classification',
	extcod AS 'external_code_according_to_type',
	extdrw AS 'external_drawing_number_reference',
	extict AS 'external_item_category',
	extigr AS 'external_item_group',
	extitm AS 'external_item_identification_code',
	extity AS 'external_item_type',
	extnam AS 'external_item_name__slash__description',
	extrra AS 'relation_ratio_to_base_unit',
	extrty AS 'relation_type_to_base_unit',
	extsys AS 'external_system_reference',
	exttyp AS 'external_type',
	extunt AS 'unit_identification_code',
	exwldt AS 'leadtime_for_ex_hyphen_works_terms_part_of_total_delivery_time',
	grsam2 AS 'gross_area_in_m2',
	grsvdm AS 'gross_volume_in_dm3_per_unit',
	grswkg AS 'gross_weight_in_kg_per_unit',
	hidsrc AS 'hide_from_search',
	inthnd AS 'internal_handling_time',
	itkseq AS 'item_make_sequence_number',
	itmcod AS 'item_identification_code',
	lcsdat AS 'life_cycle_last_changed_date',
	lcsusr AS 'life_cycle_last_changed_by_user',
	maxddd AS 'maximum_deviation_of_delivery_days',
	maxqty AS 'maximum_ordering_quantity',
	menddd AS 'mean_average_deviation_of_delivery_days',
	minddd AS 'minimum_deviation_of_delivery_days',
	minqty AS 'minimum_ordering_quantity',
	minunt AS 'oder_in_minimum_quantity_multiples',
	mrkldt AS 'market_lead_time_often_used_when_no_delivery_days_agreement',
	mtxgrp AS 'matrix_group_identification_code',
	netam2 AS 'net_area_in_m2',
	netvdm AS 'net_volume_in_dm3_per_unit',
	netwkg AS 'net_weight_in_kg_per_unit',
	newprc AS 'new_price_per_unit',
	owncod AS 'owner_code_within_given_type',
	owntyp AS 'owner_type',
	pdcitc AS 'manufacturer_item_code',
	pdcitn AS 'manufacturer_item_description',
	pdcnam AS 'manufacturer_name',
	prcdat AS 'current_price_last_changed_date',
	prcmtx AS 'item_is_master_in_a_price_matrix',
	prcunt AS 'price_per_a_number_of_units',
	prinum AS 'priority_number_differentiate_most_and_least_wanted_alternative',
	ptdlvm AS 'part_delivery_handling',
	recycl AS 'recyclable_share_slash_part',
	revnum AS 'external_revision_number',
	seqnum AS 'sequence_identification_number',
	tdlcod AS 'terms_of_delivery_identification_code',
	tpycod AS 'terms_of_payment_identification_code',
	untinf AS 'additional_packaging__slash__unit_information',
	usefco AS 'use_forecast_order_on_this_item',
	valfrm AS 'new_price_valid_from_date',
	wtrcod AS 'way_of_transport_identification_code',
	data_modified,
	source_catalog
FROM clockwork.rainbow_eic
    