
MODEL (
    kind VIEW
);

SELECT
    agrnum AS 'agreement_or_contract_number',
	appdat AS 'approved_date',
	appsts AS 'approval_status_code',
	appusr AS 'approved_by_user',
	balseq AS 'reference_to_record_in_balance_update_logdot',
	chgdat AS 'information_last_changed_date',
	chgusr AS 'information_last_changed_by_user',
	cmpdat AS 'completed_date',
	cmpsts AS 'completion_status_code',
	cmpusr AS 'completed_by_user',
	cnvexc AS 'currency_convertion_factor_1_slash_100',
	compny AS 'company_identification_code',
	credat AS 'information_created_date',
	creusr AS 'information_created_by_user',
	crtcod AS 'cart_identification_code',
	curcod AS 'currency_identification_code',
	dfiseq AS 'reference_to_transaction_record_in_dynamic_financial_informatio',
	dlgdat AS 'delegated_date',
	dlgidc AS 'delegate_to_identity_code',
	dlgidt AS 'delegate_to_identity_type',
	dlgsts AS 'delegation_status_code',
	dlvdat AS 'date_for_last_delivery',
	dlvusr AS 'delivered_slash_received_by_user',
	dspcod AS 'despatcher_code_according_to_type',
	dspdat AS 'despatch_date',
	dspnam AS 'despatcher_name',
	dsptyp AS 'despatcher_type',
	dstper AS 'distribution_period_code_for_accrual',
	enttyp AS 'type__slash__method_of_entry',
	excrat AS 'exchange_rate',
	extitm AS 'external_item_identification_code',
	extnam AS 'external_item_name__slash__description',
	extseq AS 'external_catalogue_sequence_number',
	faiseq AS 'contract_sequence_number',
	fivdat AS 'forwarded_invoice_at_date',
	fivsts AS 'forward_invoice_to_status',
	fivusr AS 'invoice_forwarded_by_user',
	hidprc AS 'hide_price_on_dokuments',
	hndseq AS 'handling_sequence',
	icscat AS 'item_classification_catalogue',
	icsref AS 'item_classification_reference_code_in_catalogue',
	idncod AS 'individ_identification_number',
	infsts AS 'information_status',
	lincod AS 'line_item_code_according_to_type',
	linnam AS 'line_item_name__slash__description',
	lintyp AS 'line_item_type',
	maploc AS 'visualized_mapped_location',
	mrqalt AS 'requisition_alternatives_exists_in_table_mrqalt',
	mrqnum AS 'requisition_number',
	mstseq AS 'reference_to_master_record_in_mrqmst',
	ofmcod AS 'order_form_identification_code',
	ordbk1 AS 'order_break_value_1',
	orddat AS 'latest_ordering_date',
	oreval AS 're_hyphen_evaluate_open_request_at_date',
	otscod AS 'default_sales_order_type',
	prccst AS 'price__slash__cost_per_unit',
	rascat AS 'requisition_assortment_classification_system_code',
	rasref AS 'requisition_classification_reference_in_catalogue',
	ratsts AS 'ration_control_status',
	rcvcod AS 'receiver_code_according_to_type',
	rcvdat AS 'receiving_date',
	rcvnam AS 'receiver_name',
	rcvtyp AS 'receiver_type',
	recusr AS 'requisition_entered_by_user',
	reqdat AS 'requisition_entered_at_date',
	reqqty AS 'requested_quantity',
	reqrra AS 'relation_ratio_from_transaction_unit_to_base_unit',
	reqrty AS 'relation_type_from_transaction_unit_to_base_unit',
	reqsts AS 'requisition_status_code',
	requnt AS 'unit_identification_code',
	rfqsts AS 'request_for_information_status',
	rplref AS 'consigned_replacement_reference',
	rsptyp AS 'resupply_type',
	rtndat AS 'return_date_for_loan',
	seqnum AS 'requisition_line_sequence_number',
	splmst AS 'splitted_or_changed_line_from_original_master',
	srctyp AS 'source_type_for_barcode_order',
	tadref AS 'delivery_address_reference_sequence_number',
	tndnum AS 'request_for_quotation_number',
	tndseq AS 'request_for_quotation_sequence_number',
	txtext AS 'external_text__slash__comment',
	txtint AS 'internal_comment__slash__text',
	valcur AS 'total_line_value_in_foreign_currency',
	valloc AS 'total_line_value_in_local_currency',
	vatcod AS 'value_added_tax_code',
	vrfsts AS 'verification_status',
	vrscod AS 'variant_string',
	wwfseq AS 'not_in_use',
	data_modified,
	source_catalog
FROM clockwork.rainbow_mrqlin
    