
MODEL (
    kind VIEW
);

SELECT
    astcod AS 'asset_type_identification_code',
	basunt AS 'base_unit_identification_code',
	budunt AS 'budget_unit_identification_code',
	chgdat AS 'information_last_changed_date',
	chgusr AS 'information_last_changed_by_user',
	cnsunt AS 'consuming_unit_identification_code',
	compny AS 'company_identification_code',
	credat AS 'information_created_date',
	creusr AS 'information_created_by_user',
	csccod AS 'cost_center_identification_code',
	dtlunt AS 'detail_unit_identification_code',
	fcpcod AS 'forecast_profile_identification_code',
	ictcod AS 'item_category_identification_code',
	idgcod AS 'individ_group_identification_code',
	itycod AS 'item_type_identification_code',
	logcod AS 'logistic_group_identification_code',
	migcod AS 'main_item_group_identification_code',
	pfmcod AS 'product_family_identification_code',
	pgrcod AS 'product_group_identification_code',
	plgcod AS 'planning_group_identification_code',
	pmdcod AS 'product_model_identification_code',
	pmgcod AS 'product_manager_role_identification_code',
	pplcod AS 'product_planner_role_identification_code',
	prbuac AS 'purchase_budget_account_identification_code',
	prccod AS 'purchaser_role_identification_code',
	prcunt AS 'purchase_unit',
	prncod AS 'product_range_identification_code',
	qamcod AS 'quality_assurance_model_identification_code',
	qlmcod AS 'quality_manager_role',
	reinit AS 'reinitiate_values_when_changed_on_item',
	rrbbud AS 'relation_ratio_from_budget_unit_to_base_unit',
	rrbcns AS 'relation_ratio_from_consuming_unit_to_base_unit',
	rrbdtl AS 'relation_ratio_from_detail_unit_to_base_unit',
	rrbprc AS 'relation_ratio_from_purchase_unit_to_base_unit',
	rrbsal AS 'relation_ratio_from_sales_unit_to_base_unit',
	rtbbud AS 'relation_type_from_budget_unit_to_base_unit',
	rtbcns AS 'relation_type_from_consuming_unit_to_base_unit',
	rtbdtl AS 'relation_tyoe_from_detail_unit_to_base_unit',
	rtbprc AS 'relation_type_from_purchase_unit_to_base_unit',
	rtbsal AS 'relation_type_from_sales_unit_to_base_unit',
	salunt AS 'sales_unit_idenfication_code',
	sapcod AS 'seller__slash__salesperson_identification_code',
	sigcod AS 'sub_item_group_identification_code',
	signam AS 'sub_item_group_name__slash__description',
	srtnam AS 'shortname',
	srtnum AS 'shortnumber',
	sublvl AS 'sub_level_required',
	txgcod AS 'tax_group_identification_cocde',
	txtdsc AS 'additional_text__slash__description',
	data_modified,
	source_catalog
FROM clockwork.rainbow_sig
    