
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from models.mssql import read


@model(
    columns={'FRAM_GILTIG_FOM': 'varchar(max)',
 'FRAM_GILTIG_TOM': 'varchar(max)',
 'FRAM_ID': 'varchar(max)',
 'FRAM_ID_TEXT': 'varchar(max)',
 'FRAM_PASSIV': 'varchar(max)',
 'FRAM_TEXT': 'varchar(max)',
 'FRANGO_GILTIG_FOM': 'varchar(max)',
 'FRANGO_GILTIG_TOM': 'varchar(max)',
 'FRANGO_ID': 'varchar(max)',
 'FRANGO_ID_TEXT': 'varchar(max)',
 'FRANGO_PASSIV': 'varchar(max)',
 'FRANGO_TEXT': 'varchar(max)',
 'KGRUPP_GILTIG_FOM': 'varchar(max)',
 'KGRUPP_GILTIG_TOM': 'varchar(max)',
 'KGRUPP_ID': 'varchar(max)',
 'KGRUPP_ID_TEXT': 'varchar(max)',
 'KGRUPP_PASSIV': 'varchar(max)',
 'KGRUPP_TEXT': 'varchar(max)',
 'KKLASS_GILTIG_FOM': 'varchar(max)',
 'KKLASS_GILTIG_TOM': 'varchar(max)',
 'KKLASS_ID': 'varchar(max)',
 'KKLASS_ID_TEXT': 'varchar(max)',
 'KKLASS_PASSIV': 'varchar(max)',
 'KKLASS_TEXT': 'varchar(max)',
 'KONTO_GILTIG_FOM': 'varchar(max)',
 'KONTO_GILTIG_TOM': 'varchar(max)',
 'KONTO_ID': 'varchar(max)',
 'KONTO_ID_TEXT': 'varchar(max)',
 'KONTO_PASSIV': 'varchar(max)',
 'KONTO_TEXT': 'varchar(max)',
 'RAD_GILTIG_FOM': 'varchar(max)',
 'RAD_GILTIG_TOM': 'varchar(max)',
 'RAD_ID': 'varchar(max)',
 'RAD_ID_TEXT': 'varchar(max)',
 'RAD_PASSIV': 'varchar(max)',
 'RAD_TEXT': 'varchar(max)',
 'TSIK_GILTIG_FOM': 'varchar(max)',
 'TSIK_GILTIG_TOM': 'varchar(max)',
 'TSIK_ID': 'varchar(max)',
 'TSIK_ID_TEXT': 'varchar(max)',
 'TSIK_PASSIV': 'varchar(max)',
 'TSIK_TEXT': 'varchar(max)'},
    cron="@daily"
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = """
	SELECT top 1000
 		CAST(FRAM_GILTIG_FOM AS VARCHAR(MAX)) AS fram_giltig_fom,
		CAST(FRAM_GILTIG_TOM AS VARCHAR(MAX)) AS fram_giltig_tom,
		CAST(FRAM_ID AS VARCHAR(MAX)) AS fram_id,
		CAST(FRAM_ID_TEXT AS VARCHAR(MAX)) AS fram_id_text,
		CAST(FRAM_PASSIV AS VARCHAR(MAX)) AS fram_passiv,
		CAST(FRAM_TEXT AS VARCHAR(MAX)) AS fram_text,
		CAST(FRANGO_GILTIG_FOM AS VARCHAR(MAX)) AS frango_giltig_fom,
		CAST(FRANGO_GILTIG_TOM AS VARCHAR(MAX)) AS frango_giltig_tom,
		CAST(FRANGO_ID AS VARCHAR(MAX)) AS frango_id,
		CAST(FRANGO_ID_TEXT AS VARCHAR(MAX)) AS frango_id_text,
		CAST(FRANGO_PASSIV AS VARCHAR(MAX)) AS frango_passiv,
		CAST(FRANGO_TEXT AS VARCHAR(MAX)) AS frango_text,
		CAST(KGRUPP_GILTIG_FOM AS VARCHAR(MAX)) AS kgrupp_giltig_fom,
		CAST(KGRUPP_GILTIG_TOM AS VARCHAR(MAX)) AS kgrupp_giltig_tom,
		CAST(KGRUPP_ID AS VARCHAR(MAX)) AS kgrupp_id,
		CAST(KGRUPP_ID_TEXT AS VARCHAR(MAX)) AS kgrupp_id_text,
		CAST(KGRUPP_PASSIV AS VARCHAR(MAX)) AS kgrupp_passiv,
		CAST(KGRUPP_TEXT AS VARCHAR(MAX)) AS kgrupp_text,
		CAST(KKLASS_GILTIG_FOM AS VARCHAR(MAX)) AS kklass_giltig_fom,
		CAST(KKLASS_GILTIG_TOM AS VARCHAR(MAX)) AS kklass_giltig_tom,
		CAST(KKLASS_ID AS VARCHAR(MAX)) AS kklass_id,
		CAST(KKLASS_ID_TEXT AS VARCHAR(MAX)) AS kklass_id_text,
		CAST(KKLASS_PASSIV AS VARCHAR(MAX)) AS kklass_passiv,
		CAST(KKLASS_TEXT AS VARCHAR(MAX)) AS kklass_text,
		CAST(KONTO_GILTIG_FOM AS VARCHAR(MAX)) AS konto_giltig_fom,
		CAST(KONTO_GILTIG_TOM AS VARCHAR(MAX)) AS konto_giltig_tom,
		CAST(KONTO_ID AS VARCHAR(MAX)) AS konto_id,
		CAST(KONTO_ID_TEXT AS VARCHAR(MAX)) AS konto_id_text,
		CAST(KONTO_PASSIV AS VARCHAR(MAX)) AS konto_passiv,
		CAST(KONTO_TEXT AS VARCHAR(MAX)) AS konto_text,
		CAST(RAD_GILTIG_FOM AS VARCHAR(MAX)) AS rad_giltig_fom,
		CAST(RAD_GILTIG_TOM AS VARCHAR(MAX)) AS rad_giltig_tom,
		CAST(RAD_ID AS VARCHAR(MAX)) AS rad_id,
		CAST(RAD_ID_TEXT AS VARCHAR(MAX)) AS rad_id_text,
		CAST(RAD_PASSIV AS VARCHAR(MAX)) AS rad_passiv,
		CAST(RAD_TEXT AS VARCHAR(MAX)) AS rad_text,
		CAST(TSIK_GILTIG_FOM AS VARCHAR(MAX)) AS tsik_giltig_fom,
		CAST(TSIK_GILTIG_TOM AS VARCHAR(MAX)) AS tsik_giltig_tom,
		CAST(TSIK_ID AS VARCHAR(MAX)) AS tsik_id,
		CAST(TSIK_ID_TEXT AS VARCHAR(MAX)) AS tsik_id_text,
		CAST(TSIK_PASSIV AS VARCHAR(MAX)) AS tsik_passiv,
		CAST(TSIK_TEXT AS VARCHAR(MAX)) AS tsik_text 
	FROM utdata.utdata295.EK_DIM_OBJ_KONTO_TSIK_IK
	"""
    return read(query=query, server_url="lsfp3.rd.sll.se")
