
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read


@model(
    columns={'ATTEST': 'bit',
 'ATTESTDATUM1': 'datetime',
 'ATTESTDATUM2': 'datetime',
 'ATTESTSIGN1': 'varchar(3)',
 'ATTESTSIGN2': 'varchar(3)',
 'AVTBES_ID': 'varchar(7)',
 'BELOPP_SEK': 'numeric',
 'BELOPP_VAL': 'numeric',
 'BETALNINGSSPARR': 'bit',
 'BETALT_SEK': 'numeric',
 'BETALT_VAL': 'numeric',
 'BETDAGAR': 'numeric',
 'BPUTF_V': 'numeric',
 'BUDGET_V': 'numeric',
 'DEFDATUM': 'datetime',
 'DEFSIGN': 'varchar(3)',
 'DOKTYP': 'numeric',
 'DOKUMENTID': 'varchar(20)',
 'DOK_ANTAL': 'numeric',
 'EREF': 'varchar(40)',
 'EXTERNANM': 'varchar(80)',
 'EXTERNID': 'varchar(19)',
 'EXTERNNR': 'varchar(27)',
 'FAKTSTATUS': 'varchar(4)',
 'FAKTURADATUM': 'datetime',
 'FAKTURA_REGDATUM': 'datetime',
 'FORETAG': 'numeric',
 'FORFALLODATUM': 'datetime',
 'FRI1_ID': 'varchar(4)',
 'FRI2_ID': 'varchar(3)',
 'F_DOK_ANTAL': 'numeric',
 'F_MED': 'numeric',
 'FÖPROC_ID': 'varchar(4)',
 'FÖRBEL_V': 'numeric',
 'HUVUDTEXT': 'varchar(30)',
 'IB': 'varchar(1)',
 'ID_ID': 'varchar(16)',
 'INTERNVERNR': 'numeric',
 'KATEGORI': 'numeric',
 'KONTO_ID': 'varchar(4)',
 'KONTSIGN': 'varchar(3)',
 'KRAVNIVA': 'numeric',
 'KST_ID': 'varchar(5)',
 'KUNDID': 'varchar(16)',
 'KUNDRTYP': 'varchar(2)',
 'LFRAM_V': 'numeric',
 'MED': 'numeric',
 'MOMS_SEK': 'numeric',
 'MOMS_VAL': 'numeric',
 'MOTP_ID': 'varchar(4)',
 'MOTTATTDAT': 'datetime',
 'MOTTATTSIGN': 'varchar(3)',
 'NR': 'numeric',
 'OCRNR': 'varchar(40)',
 'ORGVAL_V': 'numeric',
 'OVERDRDAGAR': 'numeric',
 'PNYCKEL': 'varchar(10)',
 'PRG_V': 'numeric',
 'PROC_ID': 'varchar(1)',
 'PROJ_ID': 'varchar(5)',
 'RADTEXT': 'varchar(30)',
 'RADTYPNR': 'numeric',
 'RANTEDEB': 'bit',
 'REGDATUM': 'datetime',
 'REGDAT_ID': 'varchar(20)',
 'REGSIGN': 'varchar(3)',
 'SENASTBETDATUM': 'datetime',
 'STATUS': 'varchar(1)',
 'TAB_AVTTYP': 'varchar(4)',
 'TAB_BEHÄND': 'varchar(4)',
 'TAB_BETP': 'varchar(2)',
 'TAB_BETV': 'varchar(2)',
 'TAB_CMALL': 'varchar(14)',
 'TAB_EFAKT': 'varchar(1)',
 'TAB_MOMS': 'varchar(2)',
 'TAB_MOTP': 'varchar(4)',
 'TAB_RDEB': 'varchar(2)',
 'TAB_RESENH': 'varchar(3)',
 'URSPRUNGS_VERIFIKAT': 'varchar(27)',
 'URSPTEXT': 'varchar(30)',
 'URS_ID': 'varchar(2)',
 'UTFALL_V': 'numeric',
 'UTILITY': 'numeric',
 'UTSKRDATUM': 'datetime',
 'VALUTA_ID': 'varchar(3)',
 'VERDATUM': 'datetime',
 'VERDOKREF': 'varchar(200)',
 'VERK_ID': 'varchar(2)',
 'VERNR': 'numeric',
 'VERRAD': 'numeric',
 'VERTYP': 'varchar(6)',
 'VREF': 'varchar(40)',
 'YKAT_ID': 'varchar(4)'},
    kind=ModelKindName.FULL,
    cron="@daily"
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = """
	SELECT top 1000
 		CAST(ATTEST AS VARCHAR(MAX)) AS attest,
		CONVERT(varchar(max), ATTESTDATUM1, 126) AS attestdatum1,
		CONVERT(varchar(max), ATTESTDATUM2, 126) AS attestdatum2,
		CAST(ATTESTSIGN1 AS VARCHAR(MAX)) AS attestsign1,
		CAST(ATTESTSIGN2 AS VARCHAR(MAX)) AS attestsign2,
		CAST(AVTBES_ID AS VARCHAR(MAX)) AS avtbes_id,
		CAST(BELOPP_SEK AS VARCHAR(MAX)) AS belopp_sek,
		CAST(BELOPP_VAL AS VARCHAR(MAX)) AS belopp_val,
		CAST(BETALNINGSSPARR AS VARCHAR(MAX)) AS betalningssparr,
		CAST(BETALT_SEK AS VARCHAR(MAX)) AS betalt_sek,
		CAST(BETALT_VAL AS VARCHAR(MAX)) AS betalt_val,
		CAST(BETDAGAR AS VARCHAR(MAX)) AS betdagar,
		CAST(BPUTF_V AS VARCHAR(MAX)) AS bputf_v,
		CAST(BUDGET_V AS VARCHAR(MAX)) AS budget_v,
		CONVERT(varchar(max), DEFDATUM, 126) AS defdatum,
		CAST(DEFSIGN AS VARCHAR(MAX)) AS defsign,
		CAST(DOK_ANTAL AS VARCHAR(MAX)) AS dok_antal,
		CAST(DOKTYP AS VARCHAR(MAX)) AS doktyp,
		CAST(DOKUMENTID AS VARCHAR(MAX)) AS dokumentid,
		CAST(EREF AS VARCHAR(MAX)) AS eref,
		CAST(EXTERNANM AS VARCHAR(MAX)) AS externanm,
		CAST(EXTERNID AS VARCHAR(MAX)) AS externid,
		CAST(EXTERNNR AS VARCHAR(MAX)) AS externnr,
		CAST(F_DOK_ANTAL AS VARCHAR(MAX)) AS f_dok_antal,
		CAST(F_MED AS VARCHAR(MAX)) AS f_med,
		CAST(FAKTSTATUS AS VARCHAR(MAX)) AS faktstatus,
		CONVERT(varchar(max), FAKTURA_REGDATUM, 126) AS faktura_regdatum,
		CONVERT(varchar(max), FAKTURADATUM, 126) AS fakturadatum,
		CAST(FORETAG AS VARCHAR(MAX)) AS foretag,
		CONVERT(varchar(max), FORFALLODATUM, 126) AS forfallodatum,
		CAST(FRI1_ID AS VARCHAR(MAX)) AS fri1_id,
		CAST(FRI2_ID AS VARCHAR(MAX)) AS fri2_id,
		CAST(FÖPROC_ID AS VARCHAR(MAX)) AS föproc_id,
		CAST(FÖRBEL_V AS VARCHAR(MAX)) AS förbel_v,
		CAST(HUVUDTEXT AS VARCHAR(MAX)) AS huvudtext,
		CAST(IB AS VARCHAR(MAX)) AS ib,
		CAST(ID_ID AS VARCHAR(MAX)) AS id_id,
		CAST(INTERNVERNR AS VARCHAR(MAX)) AS internvernr,
		CAST(KATEGORI AS VARCHAR(MAX)) AS kategori,
		CAST(KONTO_ID AS VARCHAR(MAX)) AS konto_id,
		CAST(KONTSIGN AS VARCHAR(MAX)) AS kontsign,
		CAST(KRAVNIVA AS VARCHAR(MAX)) AS kravniva,
		CAST(KST_ID AS VARCHAR(MAX)) AS kst_id,
		CAST(KUNDID AS VARCHAR(MAX)) AS kundid,
		CAST(KUNDRTYP AS VARCHAR(MAX)) AS kundrtyp,
		CAST(LFRAM_V AS VARCHAR(MAX)) AS lfram_v,
		CAST(MED AS VARCHAR(MAX)) AS med,
		CAST(MOMS_SEK AS VARCHAR(MAX)) AS moms_sek,
		CAST(MOMS_VAL AS VARCHAR(MAX)) AS moms_val,
		CAST(MOTP_ID AS VARCHAR(MAX)) AS motp_id,
		CONVERT(varchar(max), MOTTATTDAT, 126) AS mottattdat,
		CAST(MOTTATTSIGN AS VARCHAR(MAX)) AS mottattsign,
		CAST(NR AS VARCHAR(MAX)) AS nr,
		CAST(OCRNR AS VARCHAR(MAX)) AS ocrnr,
		CAST(ORGVAL_V AS VARCHAR(MAX)) AS orgval_v,
		CAST(OVERDRDAGAR AS VARCHAR(MAX)) AS overdrdagar,
		CAST(PNYCKEL AS VARCHAR(MAX)) AS pnyckel,
		CAST(PRG_V AS VARCHAR(MAX)) AS prg_v,
		CAST(PROC_ID AS VARCHAR(MAX)) AS proc_id,
		CAST(PROJ_ID AS VARCHAR(MAX)) AS proj_id,
		CAST(RADTEXT AS VARCHAR(MAX)) AS radtext,
		CAST(RADTYPNR AS VARCHAR(MAX)) AS radtypnr,
		CAST(RANTEDEB AS VARCHAR(MAX)) AS rantedeb,
		CAST(REGDAT_ID AS VARCHAR(MAX)) AS regdat_id,
		CONVERT(varchar(max), REGDATUM, 126) AS regdatum,
		CAST(REGSIGN AS VARCHAR(MAX)) AS regsign,
		CONVERT(varchar(max), SENASTBETDATUM, 126) AS senastbetdatum,
		CAST(STATUS AS VARCHAR(MAX)) AS status,
		CAST(TAB_AVTTYP AS VARCHAR(MAX)) AS tab_avttyp,
		CAST(TAB_BEHÄND AS VARCHAR(MAX)) AS tab_behänd,
		CAST(TAB_BETP AS VARCHAR(MAX)) AS tab_betp,
		CAST(TAB_BETV AS VARCHAR(MAX)) AS tab_betv,
		CAST(TAB_CMALL AS VARCHAR(MAX)) AS tab_cmall,
		CAST(TAB_EFAKT AS VARCHAR(MAX)) AS tab_efakt,
		CAST(TAB_MOMS AS VARCHAR(MAX)) AS tab_moms,
		CAST(TAB_MOTP AS VARCHAR(MAX)) AS tab_motp,
		CAST(TAB_RDEB AS VARCHAR(MAX)) AS tab_rdeb,
		CAST(TAB_RESENH AS VARCHAR(MAX)) AS tab_resenh,
		CAST(URS_ID AS VARCHAR(MAX)) AS urs_id,
		CAST(URSPRUNGS_VERIFIKAT AS VARCHAR(MAX)) AS ursprungs_verifikat,
		CAST(URSPTEXT AS VARCHAR(MAX)) AS ursptext,
		CAST(UTFALL_V AS VARCHAR(MAX)) AS utfall_v,
		CAST(UTILITY AS VARCHAR(MAX)) AS utility,
		CONVERT(varchar(max), UTSKRDATUM, 126) AS utskrdatum,
		CAST(VALUTA_ID AS VARCHAR(MAX)) AS valuta_id,
		CONVERT(varchar(max), VERDATUM, 126) AS verdatum,
		CAST(VERDOKREF AS VARCHAR(MAX)) AS verdokref,
		CAST(VERK_ID AS VARCHAR(MAX)) AS verk_id,
		CAST(VERNR AS VARCHAR(MAX)) AS vernr,
		CAST(VERRAD AS VARCHAR(MAX)) AS verrad,
		CAST(VERTYP AS VARCHAR(MAX)) AS vertyp,
		CAST(VREF AS VARCHAR(MAX)) AS vref,
		CAST(YKAT_ID AS VARCHAR(MAX)) AS ykat_id 
	FROM utdata.utdata295.RK_FAKTA_KUNDFAKT_VERIFIKAT
	"""
    return read(query=query, server_url="lsfp3.rd.sll.se")
