
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read


@model(
    columns={'ANSTALLD_ID': 'varchar(max)',
 'ANSTFORM_ID': 'varchar(max)',
 'ATTESTDATUM1': 'varchar(max)',
 'ATTESTDATUM2': 'varchar(max)',
 'ATTESTSIGN1': 'varchar(max)',
 'ATTESTSIGN2': 'varchar(max)',
 'AVTBES_ID': 'varchar(max)',
 'BUDGET_V': 'varchar(max)',
 'DEFDATUM': 'varchar(max)',
 'DEFSIGN': 'varchar(max)',
 'EXTERNANM': 'varchar(max)',
 'EXTERNID': 'varchar(max)',
 'EXTERNNR': 'varchar(max)',
 'FRI1_ID': 'varchar(max)',
 'FRI2_ID': 'varchar(max)',
 'HUVUDTEXT': 'varchar(max)',
 'IB': 'varchar(max)',
 'ID_ID': 'varchar(max)',
 'INTERNVERNR': 'varchar(max)',
 'KATEGORI': 'varchar(max)',
 'KONTO_ID': 'varchar(max)',
 'KONTSIGN': 'varchar(max)',
 'KST_ID': 'varchar(max)',
 'LFRAM_V': 'varchar(max)',
 'LONEANTAL1_V': 'varchar(max)',
 'LONEANTAL2_V': 'varchar(max)',
 'LONEART_ID': 'varchar(max)',
 'LONEBELOPP1_V': 'varchar(max)',
 'LONEBELOPP2_V': 'varchar(max)',
 'MOTP_ID': 'varchar(max)',
 'ORGVAL_V': 'varchar(max)',
 'PERSONALKAT_ID': 'varchar(max)',
 'PNYCKEL': 'varchar(max)',
 'PRG_V': 'varchar(max)',
 'PROC_ID': 'varchar(max)',
 'PROJ_ID': 'varchar(max)',
 'RADTEXT': 'varchar(max)',
 'RADTYPNR': 'varchar(max)',
 'REGDATUM': 'varchar(max)',
 'REGDAT_ID': 'varchar(max)',
 'REGSIGN': 'varchar(max)',
 'STATUS': 'varchar(max)',
 'TRANSDATUM': 'varchar(max)',
 'URSPTEXT': 'varchar(max)',
 'URS_ID': 'varchar(max)',
 'UTFALL_V': 'varchar(max)',
 'UTILITY': 'varchar(max)',
 'VALUTA_ID': 'varchar(max)',
 'VERDATUM': 'varchar(max)',
 'VERDOKREF': 'varchar(max)',
 'VERK_ID': 'varchar(max)',
 'VERNR': 'varchar(max)',
 'VERRAD': 'varchar(max)',
 'VERTYP': 'varchar(max)',
 'YKAT_ID': 'varchar(max)'},
    kind=ModelKindName.FULL,
    cron="@daily"
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = """
	SELECT top 1000
 		CAST(ANSTALLD_ID AS VARCHAR(MAX)) AS anstalld_id,
		CAST(ANSTFORM_ID AS VARCHAR(MAX)) AS anstform_id,
		CAST(ATTESTDATUM1 AS VARCHAR(MAX)) AS attestdatum1,
		CAST(ATTESTDATUM2 AS VARCHAR(MAX)) AS attestdatum2,
		CAST(ATTESTSIGN1 AS VARCHAR(MAX)) AS attestsign1,
		CAST(ATTESTSIGN2 AS VARCHAR(MAX)) AS attestsign2,
		CAST(AVTBES_ID AS VARCHAR(MAX)) AS avtbes_id,
		CAST(BUDGET_V AS VARCHAR(MAX)) AS budget_v,
		CAST(DEFDATUM AS VARCHAR(MAX)) AS defdatum,
		CAST(DEFSIGN AS VARCHAR(MAX)) AS defsign,
		CAST(EXTERNANM AS VARCHAR(MAX)) AS externanm,
		CAST(EXTERNID AS VARCHAR(MAX)) AS externid,
		CAST(EXTERNNR AS VARCHAR(MAX)) AS externnr,
		CAST(FRI1_ID AS VARCHAR(MAX)) AS fri1_id,
		CAST(FRI2_ID AS VARCHAR(MAX)) AS fri2_id,
		CAST(HUVUDTEXT AS VARCHAR(MAX)) AS huvudtext,
		CAST(IB AS VARCHAR(MAX)) AS ib,
		CAST(ID_ID AS VARCHAR(MAX)) AS id_id,
		CAST(INTERNVERNR AS VARCHAR(MAX)) AS internvernr,
		CAST(KATEGORI AS VARCHAR(MAX)) AS kategori,
		CAST(KONTO_ID AS VARCHAR(MAX)) AS konto_id,
		CAST(KONTSIGN AS VARCHAR(MAX)) AS kontsign,
		CAST(KST_ID AS VARCHAR(MAX)) AS kst_id,
		CAST(LFRAM_V AS VARCHAR(MAX)) AS lfram_v,
		CAST(LONEANTAL1_V AS VARCHAR(MAX)) AS loneantal1_v,
		CAST(LONEANTAL2_V AS VARCHAR(MAX)) AS loneantal2_v,
		CAST(LONEART_ID AS VARCHAR(MAX)) AS loneart_id,
		CAST(LONEBELOPP1_V AS VARCHAR(MAX)) AS lonebelopp1_v,
		CAST(LONEBELOPP2_V AS VARCHAR(MAX)) AS lonebelopp2_v,
		CAST(MOTP_ID AS VARCHAR(MAX)) AS motp_id,
		CAST(ORGVAL_V AS VARCHAR(MAX)) AS orgval_v,
		CAST(PERSONALKAT_ID AS VARCHAR(MAX)) AS personalkat_id,
		CAST(PNYCKEL AS VARCHAR(MAX)) AS pnyckel,
		CAST(PRG_V AS VARCHAR(MAX)) AS prg_v,
		CAST(PROC_ID AS VARCHAR(MAX)) AS proc_id,
		CAST(PROJ_ID AS VARCHAR(MAX)) AS proj_id,
		CAST(RADTEXT AS VARCHAR(MAX)) AS radtext,
		CAST(RADTYPNR AS VARCHAR(MAX)) AS radtypnr,
		CAST(REGDAT_ID AS VARCHAR(MAX)) AS regdat_id,
		CAST(REGDATUM AS VARCHAR(MAX)) AS regdatum,
		CAST(REGSIGN AS VARCHAR(MAX)) AS regsign,
		CAST(STATUS AS VARCHAR(MAX)) AS status,
		CAST(TRANSDATUM AS VARCHAR(MAX)) AS transdatum,
		CAST(URS_ID AS VARCHAR(MAX)) AS urs_id,
		CAST(URSPTEXT AS VARCHAR(MAX)) AS ursptext,
		CAST(UTFALL_V AS VARCHAR(MAX)) AS utfall_v,
		CAST(UTILITY AS VARCHAR(MAX)) AS utility,
		CAST(VALUTA_ID AS VARCHAR(MAX)) AS valuta_id,
		CAST(VERDATUM AS VARCHAR(MAX)) AS verdatum,
		CAST(VERDOKREF AS VARCHAR(MAX)) AS verdokref,
		CAST(VERK_ID AS VARCHAR(MAX)) AS verk_id,
		CAST(VERNR AS VARCHAR(MAX)) AS vernr,
		CAST(VERRAD AS VARCHAR(MAX)) AS verrad,
		CAST(VERTYP AS VARCHAR(MAX)) AS vertyp,
		CAST(YKAT_ID AS VARCHAR(MAX)) AS ykat_id 
	FROM utdata.utdata295.EK_FAKTA_VERIFIKAT_LON
	"""
    return read(query=query, server_url="lsfp3.rd.sll.se")
