
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from models.raindance_src_to_raw import pipe


@model(
    columns={'ATTESTDATUM1': 'varchar(max)',
 'ATTESTDATUM2': 'varchar(max)',
 'ATTESTSIGN1': 'varchar(max)',
 'ATTESTSIGN2': 'varchar(max)',
 'AVTBES_ID': 'varchar(max)',
 'BUDGET_V': 'varchar(max)',
 'DEFDATUM': 'varchar(max)',
 'DEFSIGN': 'varchar(max)',
 'EXTERNANM': 'varchar(max)',
 'EXTERNID': 'varchar(max)',
 'EXTERNNR': 'varchar(max)',
 'FRI1_ID': 'varchar(max)',
 'FRI2_ID': 'varchar(max)',
 'HUVUDTEXT': 'varchar(max)',
 'IB': 'varchar(max)',
 'ID_ID': 'varchar(max)',
 'INTERNVERNR': 'varchar(max)',
 'KATEGORI': 'varchar(max)',
 'KONTO_ID': 'varchar(max)',
 'KONTSIGN': 'varchar(max)',
 'KST_ID': 'varchar(max)',
 'LFRAM_V': 'varchar(max)',
 'MOTP_ID': 'varchar(max)',
 'ORGVAL_V': 'varchar(max)',
 'PNYCKEL': 'varchar(max)',
 'PRG_V': 'varchar(max)',
 'PROC_ID': 'varchar(max)',
 'PROJ_ID': 'varchar(max)',
 'RADTEXT': 'varchar(max)',
 'RADTYPNR': 'varchar(max)',
 'REGDATUM': 'varchar(max)',
 'REGDAT_ID': 'varchar(max)',
 'REGSIGN': 'varchar(max)',
 'STATUS': 'varchar(max)',
 'URSPTEXT': 'varchar(max)',
 'URS_ID': 'varchar(max)',
 'UTFALL_V': 'varchar(max)',
 'UTILITY': 'varchar(max)',
 'VALUTA_ID': 'varchar(max)',
 'VERDATUM': 'varchar(max)',
 'VERDOKREF': 'varchar(max)',
 'VERK_ID': 'varchar(max)',
 'VERNR': 'varchar(max)',
 'VERRAD': 'varchar(max)',
 'VERTYP': 'varchar(max)',
 'YKAT_ID': 'varchar(max)'},
    cron="@daily"
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = """SELECT CAST(ATTESTDATUM1 AS VARCHAR(MAX)) AS ATTESTDATUM1,
CAST(ATTESTDATUM2 AS VARCHAR(MAX)) AS ATTESTDATUM2,
CAST(ATTESTSIGN1 AS VARCHAR(MAX)) AS ATTESTSIGN1,
CAST(ATTESTSIGN2 AS VARCHAR(MAX)) AS ATTESTSIGN2,
CAST(AVTBES_ID AS VARCHAR(MAX)) AS AVTBES_ID,
CAST(BUDGET_V AS VARCHAR(MAX)) AS BUDGET_V,
CAST(DEFDATUM AS VARCHAR(MAX)) AS DEFDATUM,
CAST(DEFSIGN AS VARCHAR(MAX)) AS DEFSIGN,
CAST(EXTERNANM AS VARCHAR(MAX)) AS EXTERNANM,
CAST(EXTERNID AS VARCHAR(MAX)) AS EXTERNID,
CAST(EXTERNNR AS VARCHAR(MAX)) AS EXTERNNR,
CAST(FRI1_ID AS VARCHAR(MAX)) AS FRI1_ID,
CAST(FRI2_ID AS VARCHAR(MAX)) AS FRI2_ID,
CAST(HUVUDTEXT AS VARCHAR(MAX)) AS HUVUDTEXT,
CAST(IB AS VARCHAR(MAX)) AS IB,
CAST(ID_ID AS VARCHAR(MAX)) AS ID_ID,
CAST(INTERNVERNR AS VARCHAR(MAX)) AS INTERNVERNR,
CAST(KATEGORI AS VARCHAR(MAX)) AS KATEGORI,
CAST(KONTO_ID AS VARCHAR(MAX)) AS KONTO_ID,
CAST(KONTSIGN AS VARCHAR(MAX)) AS KONTSIGN,
CAST(KST_ID AS VARCHAR(MAX)) AS KST_ID,
CAST(LFRAM_V AS VARCHAR(MAX)) AS LFRAM_V,
CAST(MOTP_ID AS VARCHAR(MAX)) AS MOTP_ID,
CAST(ORGVAL_V AS VARCHAR(MAX)) AS ORGVAL_V,
CAST(PNYCKEL AS VARCHAR(MAX)) AS PNYCKEL,
CAST(PRG_V AS VARCHAR(MAX)) AS PRG_V,
CAST(PROC_ID AS VARCHAR(MAX)) AS PROC_ID,
CAST(PROJ_ID AS VARCHAR(MAX)) AS PROJ_ID,
CAST(RADTEXT AS VARCHAR(MAX)) AS RADTEXT,
CAST(RADTYPNR AS VARCHAR(MAX)) AS RADTYPNR,
CAST(REGDAT_ID AS VARCHAR(MAX)) AS REGDAT_ID,
CAST(REGDATUM AS VARCHAR(MAX)) AS REGDATUM,
CAST(REGSIGN AS VARCHAR(MAX)) AS REGSIGN,
CAST(STATUS AS VARCHAR(MAX)) AS STATUS,
CAST(URS_ID AS VARCHAR(MAX)) AS URS_ID,
CAST(URSPTEXT AS VARCHAR(MAX)) AS URSPTEXT,
CAST(UTFALL_V AS VARCHAR(MAX)) AS UTFALL_V,
CAST(UTILITY AS VARCHAR(MAX)) AS UTILITY,
CAST(VALUTA_ID AS VARCHAR(MAX)) AS VALUTA_ID,
CAST(VERDATUM AS VARCHAR(MAX)) AS VERDATUM,
CAST(VERDOKREF AS VARCHAR(MAX)) AS VERDOKREF,
CAST(VERK_ID AS VARCHAR(MAX)) AS VERK_ID,
CAST(VERNR AS VARCHAR(MAX)) AS VERNR,
CAST(VERRAD AS VARCHAR(MAX)) AS VERRAD,
CAST(VERTYP AS VARCHAR(MAX)) AS VERTYP,
CAST(YKAT_ID AS VARCHAR(MAX)) AS YKAT_ID FROM utdata.utdata295.EK_FAKTA_VERIFIKAT_AVTBES"""
    return pipe(query=query)
