
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read


@model(
    columns={'ABONNEMANGSID': 'varchar(40)',
 'ANM': 'varchar(80)',
 'ANSTDATUM': 'datetime',
 'ANSTSIGN': 'varchar(3)',
 'ANTAL_KORR': 'numeric',
 'ATTEST': 'bit',
 'BELOPP_SEK': 'numeric',
 'BELOPP_VAL': 'numeric',
 'BETALNINGSSPARR': 'bit',
 'BETALT_SEK': 'numeric',
 'BETALT_VAL': 'numeric',
 'BETDAGAR': 'numeric',
 'BETPAMDATUM': 'datetime',
 'BETVAG_BANKKONTO': 'varchar(40)',
 'BETVAG_BGNR': 'varchar(40)',
 'BETVAG_CBNR': 'varchar(40)',
 'BETVAG_FACNR': 'varchar(40)',
 'BETVAG_PGNR': 'varchar(40)',
 'BETVAG_UTLNR': 'varchar(40)',
 'BOKBELOPP_INT': 'numeric',
 'BOKBELOPP_VAL': 'numeric',
 'BOKSTATUS': 'varchar(6)',
 'BOKTYP': 'numeric',
 'BUNTNR': 'numeric',
 'DETALJTYP': 'varchar(2)',
 'DOKREF': 'varchar(200)',
 'DOK_ANTAL': 'numeric',
 'DRANTESATS': 'numeric',
 'DUMMY3': 'varchar(4)',
 'EREF': 'varchar(40)',
 'FAKTSTATUS': 'varchar(4)',
 'FAKTSTATUS2': 'varchar(4)',
 'FAKTURADATUM': 'datetime',
 'FORFALLODATUM': 'datetime',
 'IRANTEBER_VAL': 'numeric',
 'KLARDATUM': 'datetime',
 'KRABATTDATUM': 'datetime',
 'KRABATT_VAL': 'numeric',
 'KRAVNIVA': 'numeric',
 'KUNDID': 'varchar(16)',
 'KUNDRTYP': 'varchar(2)',
 'KURSDIV': 'numeric',
 'KURSMULT': 'numeric',
 'MED': 'numeric',
 'MOMS_SEK': 'numeric',
 'MOMS_VAL': 'numeric',
 'MOTTATTDAT': 'datetime',
 'MOTTATTSIGN': 'varchar(3)',
 'NR': 'numeric',
 'OCRNR': 'varchar(40)',
 'ORDERID': 'varchar(40)',
 'OVERDRDAGAR': 'numeric',
 'RANTEDEB': 'bit',
 'RANTEDEBDATUM': 'datetime',
 'RANTEDEB_VAL': 'numeric',
 'REGDATUM': 'datetime',
 'REGSIGN': 'varchar(3)',
 'RESKONTRA': 'varchar(2)',
 'SENASTBETDATUM': 'datetime',
 'TAB_AVTTYP': 'varchar(4)',
 'TAB_BEHÄND': 'varchar(4)',
 'TAB_BETP': 'varchar(2)',
 'TAB_BETV': 'varchar(2)',
 'TAB_CMALL': 'varchar(14)',
 'TAB_EFAKT': 'varchar(1)',
 'TAB_MOMS': 'varchar(2)',
 'TAB_MOTP': 'varchar(4)',
 'TAB_RDEB': 'varchar(2)',
 'TAB_RESENH': 'varchar(3)',
 'UTILITY': 'numeric',
 'UTSKRDATUM': 'datetime',
 'VERDATUM': 'datetime',
 'VERNR': 'numeric',
 'VERRAD': 'int',
 'VREF': 'varchar(40)',
 'ZVFREFERENS': 'varchar(40)'},
    kind=ModelKindName.FULL,
    cron="@daily"
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = """
	SELECT top 1000
 		CAST(ABONNEMANGSID AS VARCHAR(MAX)) AS abonnemangsid,
		CAST(ANM AS VARCHAR(MAX)) AS anm,
		CONVERT(varchar(max), ANSTDATUM, 126) AS anstdatum,
		CAST(ANSTSIGN AS VARCHAR(MAX)) AS anstsign,
		CAST(ANTAL_KORR AS VARCHAR(MAX)) AS antal_korr,
		CAST(ATTEST AS VARCHAR(MAX)) AS attest,
		CAST(BELOPP_SEK AS VARCHAR(MAX)) AS belopp_sek,
		CAST(BELOPP_VAL AS VARCHAR(MAX)) AS belopp_val,
		CAST(BETALNINGSSPARR AS VARCHAR(MAX)) AS betalningssparr,
		CAST(BETALT_SEK AS VARCHAR(MAX)) AS betalt_sek,
		CAST(BETALT_VAL AS VARCHAR(MAX)) AS betalt_val,
		CAST(BETDAGAR AS VARCHAR(MAX)) AS betdagar,
		CONVERT(varchar(max), BETPAMDATUM, 126) AS betpamdatum,
		CAST(BETVAG_BANKKONTO AS VARCHAR(MAX)) AS betvag_bankkonto,
		CAST(BETVAG_BGNR AS VARCHAR(MAX)) AS betvag_bgnr,
		CAST(BETVAG_CBNR AS VARCHAR(MAX)) AS betvag_cbnr,
		CAST(BETVAG_FACNR AS VARCHAR(MAX)) AS betvag_facnr,
		CAST(BETVAG_PGNR AS VARCHAR(MAX)) AS betvag_pgnr,
		CAST(BETVAG_UTLNR AS VARCHAR(MAX)) AS betvag_utlnr,
		CAST(BOKBELOPP_INT AS VARCHAR(MAX)) AS bokbelopp_int,
		CAST(BOKBELOPP_VAL AS VARCHAR(MAX)) AS bokbelopp_val,
		CAST(BOKSTATUS AS VARCHAR(MAX)) AS bokstatus,
		CAST(BOKTYP AS VARCHAR(MAX)) AS boktyp,
		CAST(BUNTNR AS VARCHAR(MAX)) AS buntnr,
		CAST(DETALJTYP AS VARCHAR(MAX)) AS detaljtyp,
		CAST(DOK_ANTAL AS VARCHAR(MAX)) AS dok_antal,
		CAST(DOKREF AS VARCHAR(MAX)) AS dokref,
		CAST(DRANTESATS AS VARCHAR(MAX)) AS drantesats,
		CAST(DUMMY3 AS VARCHAR(MAX)) AS dummy3,
		CAST(EREF AS VARCHAR(MAX)) AS eref,
		CAST(FAKTSTATUS AS VARCHAR(MAX)) AS faktstatus,
		CAST(FAKTSTATUS2 AS VARCHAR(MAX)) AS faktstatus2,
		CONVERT(varchar(max), FAKTURADATUM, 126) AS fakturadatum,
		CONVERT(varchar(max), FORFALLODATUM, 126) AS forfallodatum,
		CAST(IRANTEBER_VAL AS VARCHAR(MAX)) AS iranteber_val,
		CONVERT(varchar(max), KLARDATUM, 126) AS klardatum,
		CAST(KRABATT_VAL AS VARCHAR(MAX)) AS krabatt_val,
		CONVERT(varchar(max), KRABATTDATUM, 126) AS krabattdatum,
		CAST(KRAVNIVA AS VARCHAR(MAX)) AS kravniva,
		CAST(KUNDID AS VARCHAR(MAX)) AS kundid,
		CAST(KUNDRTYP AS VARCHAR(MAX)) AS kundrtyp,
		CAST(KURSDIV AS VARCHAR(MAX)) AS kursdiv,
		CAST(KURSMULT AS VARCHAR(MAX)) AS kursmult,
		CAST(MED AS VARCHAR(MAX)) AS med,
		CAST(MOMS_SEK AS VARCHAR(MAX)) AS moms_sek,
		CAST(MOMS_VAL AS VARCHAR(MAX)) AS moms_val,
		CONVERT(varchar(max), MOTTATTDAT, 126) AS mottattdat,
		CAST(MOTTATTSIGN AS VARCHAR(MAX)) AS mottattsign,
		CAST(NR AS VARCHAR(MAX)) AS nr,
		CAST(OCRNR AS VARCHAR(MAX)) AS ocrnr,
		CAST(ORDERID AS VARCHAR(MAX)) AS orderid,
		CAST(OVERDRDAGAR AS VARCHAR(MAX)) AS overdrdagar,
		CAST(RANTEDEB AS VARCHAR(MAX)) AS rantedeb,
		CAST(RANTEDEB_VAL AS VARCHAR(MAX)) AS rantedeb_val,
		CONVERT(varchar(max), RANTEDEBDATUM, 126) AS rantedebdatum,
		CONVERT(varchar(max), REGDATUM, 126) AS regdatum,
		CAST(REGSIGN AS VARCHAR(MAX)) AS regsign,
		CAST(RESKONTRA AS VARCHAR(MAX)) AS reskontra,
		CONVERT(varchar(max), SENASTBETDATUM, 126) AS senastbetdatum,
		CAST(TAB_AVTTYP AS VARCHAR(MAX)) AS tab_avttyp,
		CAST(TAB_BEHÄND AS VARCHAR(MAX)) AS tab_behänd,
		CAST(TAB_BETP AS VARCHAR(MAX)) AS tab_betp,
		CAST(TAB_BETV AS VARCHAR(MAX)) AS tab_betv,
		CAST(TAB_CMALL AS VARCHAR(MAX)) AS tab_cmall,
		CAST(TAB_EFAKT AS VARCHAR(MAX)) AS tab_efakt,
		CAST(TAB_MOMS AS VARCHAR(MAX)) AS tab_moms,
		CAST(TAB_MOTP AS VARCHAR(MAX)) AS tab_motp,
		CAST(TAB_RDEB AS VARCHAR(MAX)) AS tab_rdeb,
		CAST(TAB_RESENH AS VARCHAR(MAX)) AS tab_resenh,
		CAST(UTILITY AS VARCHAR(MAX)) AS utility,
		CONVERT(varchar(max), UTSKRDATUM, 126) AS utskrdatum,
		CONVERT(varchar(max), VERDATUM, 126) AS verdatum,
		CAST(VERNR AS VARCHAR(MAX)) AS vernr,
		CAST(VERRAD AS VARCHAR(MAX)) AS verrad,
		CAST(VREF AS VARCHAR(MAX)) AS vref,
		CAST(ZVFREFERENS AS VARCHAR(MAX)) AS zvfreferens 
	FROM utdata.utdata295.RK_FAKTA_KUNDBOKDET_FAKT
	"""
    return read(query=query, server_url="lsfp3.rd.sll.se")
