
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read


@model(
    columns={'ABONNEMANGSID': 'varchar(40)',
 'ANM': 'varchar(80)',
 'ANSTDATUM': 'datetime',
 'ANSTSIGN': 'varchar(3)',
 'ANTAL_KORR': 'numeric',
 'ATTEST': 'bit',
 'AVTALID': 'varchar(40)',
 'BELOPP_SEK': 'numeric',
 'BELOPP_VAL': 'numeric',
 'BETALNINGSSPARR': 'bit',
 'BETALT_SEK': 'numeric',
 'BETALT_VAL': 'numeric',
 'BETDAGAR': 'numeric',
 'BETPAMDATUM': 'datetime',
 'BETVAG_BANKKONTO': 'varchar(40)',
 'BETVAG_BGNR': 'varchar(40)',
 'BETVAG_CBNR': 'varchar(40)',
 'BETVAG_FACNR': 'varchar(40)',
 'BETVAG_PGNR': 'varchar(40)',
 'BETVAG_UTLNR': 'varchar(40)',
 'BUNTNR': 'numeric',
 'DOKREF': 'varchar(200)',
 'DOK_ANTAL': 'numeric',
 'DRANTESATS': 'numeric',
 'DUMMY3': 'varchar(4)',
 'EREF': 'varchar(40)',
 'FAKTSTATUS': 'varchar(4)',
 'FAKTSTATUS2': 'varchar(4)',
 'FAKTURADATUM': 'datetime',
 'FORFALLODATUM': 'datetime',
 'IRANTEBER_VAL': 'numeric',
 'KLARDATUM': 'datetime',
 'KRABATTDATUM': 'datetime',
 'KRABATT_VAL': 'numeric',
 'KRAVNIVA': 'numeric',
 'KUNDID': 'varchar(16)',
 'KUNDRTYP': 'varchar(2)',
 'KURSDIV': 'numeric',
 'KURSMULT': 'numeric',
 'LEVID': 'varchar(16)',
 'LEVRTYP': 'varchar(2)',
 'MED': 'numeric',
 'MOMS_SEK': 'numeric',
 'MOMS_VAL': 'numeric',
 'MOTTATTDAT': 'datetime',
 'MOTTATTSIGN': 'varchar(3)',
 'NR': 'numeric',
 'OCRNR': 'varchar(40)',
 'ORDERID': 'varchar(40)',
 'OVERDRDAGAR': 'numeric',
 'RANTEDEB': 'bit',
 'RANTEDEBDATUM': 'datetime',
 'RANTEDEB_VAL': 'numeric',
 'REGDATUM': 'datetime',
 'REGSIGN': 'varchar(3)',
 'RESKONTRA': 'varchar(2)',
 'SENASTBETDATUM': 'datetime',
 'TAB_AVTTYP': 'varchar(4)',
 'TAB_BEHÄND': 'varchar(4)',
 'TAB_BETP': 'varchar(2)',
 'TAB_BETV': 'varchar(2)',
 'TAB_CMALL': 'varchar(14)',
 'TAB_EFAKT': 'varchar(1)',
 'TAB_FÖRK': 'varchar(1)',
 'TAB_MOMS': 'varchar(2)',
 'TAB_MOTP': 'varchar(4)',
 'TAB_RDEB': 'varchar(2)',
 'TAB_REF': 'varchar(14)',
 'TAB_RESENH': 'varchar(3)',
 'TAB_RESK': 'varchar(2)',
 'TAB_SCADAT': 'varchar(8)',
 'TAB_SCANNR': 'varchar(10)',
 'TAB_UBF': 'varchar(2)',
 'TAB_UBK': 'varchar(2)',
 'TAB_VALUTA': 'varchar(3)',
 'UTILITY': 'numeric',
 'UTSKRDATUM': 'datetime',
 'VREF': 'varchar(40)',
 'ZVFREFERENS': 'varchar(40)'},
    kind=ModelKindName.FULL,
    cron="@daily"
)
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = """
	SELECT top 1000
 		CAST(ABONNEMANGSID AS VARCHAR(MAX)) AS abonnemangsid,
		CAST(ANM AS VARCHAR(MAX)) AS anm,
		CAST(ANSTDATUM AS VARCHAR(MAX)) AS anstdatum,
		CAST(ANSTSIGN AS VARCHAR(MAX)) AS anstsign,
		CAST(ANTAL_KORR AS VARCHAR(MAX)) AS antal_korr,
		CAST(ATTEST AS VARCHAR(MAX)) AS attest,
		CAST(AVTALID AS VARCHAR(MAX)) AS avtalid,
		CAST(BELOPP_SEK AS VARCHAR(MAX)) AS belopp_sek,
		CAST(BELOPP_VAL AS VARCHAR(MAX)) AS belopp_val,
		CAST(BETALNINGSSPARR AS VARCHAR(MAX)) AS betalningssparr,
		CAST(BETALT_SEK AS VARCHAR(MAX)) AS betalt_sek,
		CAST(BETALT_VAL AS VARCHAR(MAX)) AS betalt_val,
		CAST(BETDAGAR AS VARCHAR(MAX)) AS betdagar,
		CAST(BETPAMDATUM AS VARCHAR(MAX)) AS betpamdatum,
		CAST(BETVAG_BANKKONTO AS VARCHAR(MAX)) AS betvag_bankkonto,
		CAST(BETVAG_BGNR AS VARCHAR(MAX)) AS betvag_bgnr,
		CAST(BETVAG_CBNR AS VARCHAR(MAX)) AS betvag_cbnr,
		CAST(BETVAG_FACNR AS VARCHAR(MAX)) AS betvag_facnr,
		CAST(BETVAG_PGNR AS VARCHAR(MAX)) AS betvag_pgnr,
		CAST(BETVAG_UTLNR AS VARCHAR(MAX)) AS betvag_utlnr,
		CAST(BUNTNR AS VARCHAR(MAX)) AS buntnr,
		CAST(DOK_ANTAL AS VARCHAR(MAX)) AS dok_antal,
		CAST(DOKREF AS VARCHAR(MAX)) AS dokref,
		CAST(DRANTESATS AS VARCHAR(MAX)) AS drantesats,
		CAST(DUMMY3 AS VARCHAR(MAX)) AS dummy3,
		CAST(EREF AS VARCHAR(MAX)) AS eref,
		CAST(FAKTSTATUS AS VARCHAR(MAX)) AS faktstatus,
		CAST(FAKTSTATUS2 AS VARCHAR(MAX)) AS faktstatus2,
		CAST(FAKTURADATUM AS VARCHAR(MAX)) AS fakturadatum,
		CAST(FORFALLODATUM AS VARCHAR(MAX)) AS forfallodatum,
		CAST(IRANTEBER_VAL AS VARCHAR(MAX)) AS iranteber_val,
		CAST(KLARDATUM AS VARCHAR(MAX)) AS klardatum,
		CAST(KRABATT_VAL AS VARCHAR(MAX)) AS krabatt_val,
		CAST(KRABATTDATUM AS VARCHAR(MAX)) AS krabattdatum,
		CAST(KRAVNIVA AS VARCHAR(MAX)) AS kravniva,
		CAST(KUNDID AS VARCHAR(MAX)) AS kundid,
		CAST(KUNDRTYP AS VARCHAR(MAX)) AS kundrtyp,
		CAST(KURSDIV AS VARCHAR(MAX)) AS kursdiv,
		CAST(KURSMULT AS VARCHAR(MAX)) AS kursmult,
		CAST(LEVID AS VARCHAR(MAX)) AS levid,
		CAST(LEVRTYP AS VARCHAR(MAX)) AS levrtyp,
		CAST(MED AS VARCHAR(MAX)) AS med,
		CAST(MOMS_SEK AS VARCHAR(MAX)) AS moms_sek,
		CAST(MOMS_VAL AS VARCHAR(MAX)) AS moms_val,
		CAST(MOTTATTDAT AS VARCHAR(MAX)) AS mottattdat,
		CAST(MOTTATTSIGN AS VARCHAR(MAX)) AS mottattsign,
		CAST(NR AS VARCHAR(MAX)) AS nr,
		CAST(OCRNR AS VARCHAR(MAX)) AS ocrnr,
		CAST(ORDERID AS VARCHAR(MAX)) AS orderid,
		CAST(OVERDRDAGAR AS VARCHAR(MAX)) AS overdrdagar,
		CAST(RANTEDEB AS VARCHAR(MAX)) AS rantedeb,
		CAST(RANTEDEB_VAL AS VARCHAR(MAX)) AS rantedeb_val,
		CAST(RANTEDEBDATUM AS VARCHAR(MAX)) AS rantedebdatum,
		CAST(REGDATUM AS VARCHAR(MAX)) AS regdatum,
		CAST(REGSIGN AS VARCHAR(MAX)) AS regsign,
		CAST(RESKONTRA AS VARCHAR(MAX)) AS reskontra,
		CAST(SENASTBETDATUM AS VARCHAR(MAX)) AS senastbetdatum,
		CAST(TAB_AVTTYP AS VARCHAR(MAX)) AS tab_avttyp,
		CAST(TAB_BEHÄND AS VARCHAR(MAX)) AS tab_behänd,
		CAST(TAB_BETP AS VARCHAR(MAX)) AS tab_betp,
		CAST(TAB_BETV AS VARCHAR(MAX)) AS tab_betv,
		CAST(TAB_CMALL AS VARCHAR(MAX)) AS tab_cmall,
		CAST(TAB_EFAKT AS VARCHAR(MAX)) AS tab_efakt,
		CAST(TAB_FÖRK AS VARCHAR(MAX)) AS tab_förk,
		CAST(TAB_MOMS AS VARCHAR(MAX)) AS tab_moms,
		CAST(TAB_MOTP AS VARCHAR(MAX)) AS tab_motp,
		CAST(TAB_RDEB AS VARCHAR(MAX)) AS tab_rdeb,
		CAST(TAB_REF AS VARCHAR(MAX)) AS tab_ref,
		CAST(TAB_RESENH AS VARCHAR(MAX)) AS tab_resenh,
		CAST(TAB_RESK AS VARCHAR(MAX)) AS tab_resk,
		CAST(TAB_SCADAT AS VARCHAR(MAX)) AS tab_scadat,
		CAST(TAB_SCANNR AS VARCHAR(MAX)) AS tab_scannr,
		CAST(TAB_UBF AS VARCHAR(MAX)) AS tab_ubf,
		CAST(TAB_UBK AS VARCHAR(MAX)) AS tab_ubk,
		CAST(TAB_VALUTA AS VARCHAR(MAX)) AS tab_valuta,
		CAST(UTILITY AS VARCHAR(MAX)) AS utility,
		CAST(UTSKRDATUM AS VARCHAR(MAX)) AS utskrdatum,
		CAST(VREF AS VARCHAR(MAX)) AS vref,
		CAST(ZVFREFERENS AS VARCHAR(MAX)) AS zvfreferens 
	FROM utdata.utdata295.RK_FAKTA_FAKTURA
	"""
    return read(query=query, server_url="lsfp3.rd.sll.se")
