
import typing as t
from datetime import datetime
import pandas as pd
from sqlmesh import ExecutionContext, model
from sqlmesh.core.model.kind import ModelKindName
from models.mssql import read

        
@model(
    columns={'_data_modified_utc': 'date', '_metadata_modified_utc': 'datetime2', '_source': 'varchar(max)', 'FMK_GILTIG_FOM': 'varchar(max)', 'FMK_GILTIG_TOM': 'varchar(max)', 'FMK_ID': 'varchar(max)', 'FMK_ID_TEXT': 'varchar(max)', 'FMK_PASSIV': 'varchar(max)', 'FMK_TEXT': 'varchar(max)', 'FRA01_GILTIG_FOM': 'varchar(max)', 'FRA01_GILTIG_TOM': 'varchar(max)', 'FRA01_ID': 'varchar(max)', 'FRA01_ID_TEXT': 'varchar(max)', 'FRA01_PASSIV': 'varchar(max)', 'FRA01_TEXT': 'varchar(max)', 'FRA03_GILTIG_FOM': 'varchar(max)', 'FRA03_GILTIG_TOM': 'varchar(max)', 'FRA03_ID': 'varchar(max)', 'FRA03_ID_TEXT': 'varchar(max)', 'FRA03_PASSIV': 'varchar(max)', 'FRA03_TEXT': 'varchar(max)', 'FRA05_GILTIG_FOM': 'varchar(max)', 'FRA05_GILTIG_TOM': 'varchar(max)', 'FRA05_ID': 'varchar(max)', 'FRA05_ID_TEXT': 'varchar(max)', 'FRA05_PASSIV': 'varchar(max)', 'FRA05_TEXT': 'varchar(max)', 'KBR_GILTIG_FOM': 'varchar(max)', 'KBR_GILTIG_TOM': 'varchar(max)', 'KBR_ID': 'varchar(max)', 'KBR_ID_TEXT': 'varchar(max)', 'KBR_PASSIV': 'varchar(max)', 'KBR_TEXT': 'varchar(max)', 'KONCRR_GILTIG_FOM': 'varchar(max)', 'KONCRR_GILTIG_TOM': 'varchar(max)', 'KONCRR_ID': 'varchar(max)', 'KONCRR_ID_TEXT': 'varchar(max)', 'KONCRR_PASSIV': 'varchar(max)', 'KONCRR_TEXT': 'varchar(max)', 'KONDEL_GILTIG_FOM': 'varchar(max)', 'KONDEL_GILTIG_TOM': 'varchar(max)', 'KONDEL_ID': 'varchar(max)', 'KONDEL_ID_TEXT': 'varchar(max)', 'KONDEL_PASSIV': 'varchar(max)', 'KONDEL_TEXT': 'varchar(max)', 'KONTO_GILTIG_FOM': 'varchar(max)', 'KONTO_GILTIG_TOM': 'varchar(max)', 'KONTO_ID': 'varchar(max)', 'KONTO_ID_TEXT': 'varchar(max)', 'KONTO_PASSIV': 'varchar(max)', 'KONTO_TEXT': 'varchar(max)', 'KTO1_GILTIG_FOM': 'varchar(max)', 'KTO1_GILTIG_TOM': 'varchar(max)', 'KTO1_ID': 'varchar(max)', 'KTO1_ID_TEXT': 'varchar(max)', 'KTO1_PASSIV': 'varchar(max)', 'KTO1_TEXT': 'varchar(max)', 'KTO2_GILTIG_FOM': 'varchar(max)', 'KTO2_GILTIG_TOM': 'varchar(max)', 'KTO2_ID': 'varchar(max)', 'KTO2_ID_TEXT': 'varchar(max)', 'KTO2_PASSIV': 'varchar(max)', 'KTO2_TEXT': 'varchar(max)', 'KTYP_GILTIG_FOM': 'varchar(max)', 'KTYP_GILTIG_TOM': 'varchar(max)', 'KTYP_ID': 'varchar(max)', 'KTYP_ID_TEXT': 'varchar(max)', 'KTYP_PASSIV': 'varchar(max)', 'KTYP_TEXT': 'varchar(max)', 'MKTO_GILTIG_FOM': 'varchar(max)', 'MKTO_GILTIG_TOM': 'varchar(max)', 'MKTO_ID': 'varchar(max)', 'MKTO_ID_TEXT': 'varchar(max)', 'MKTO_PASSIV': 'varchar(max)', 'MKTO_TEXT': 'varchar(max)', 'MS_GILTIG_FOM': 'varchar(max)', 'MS_GILTIG_TOM': 'varchar(max)', 'MS_ID': 'varchar(max)', 'MS_ID_TEXT': 'varchar(max)', 'MS_PASSIV': 'varchar(max)', 'MS_TEXT': 'varchar(max)', 'SA_GILTIG_FOM': 'varchar(max)', 'SA_GILTIG_TOM': 'varchar(max)', 'SA_ID': 'varchar(max)', 'SA_ID_TEXT': 'varchar(max)', 'SA_PASSIV': 'varchar(max)', 'SA_TEXT': 'varchar(max)', 'SKRD_GILTIG_FOM': 'varchar(max)', 'SKRD_GILTIG_TOM': 'varchar(max)', 'SKRD_ID': 'varchar(max)', 'SKRD_ID_TEXT': 'varchar(max)', 'SKRD_PASSIV': 'varchar(max)', 'SKRD_TEXT': 'varchar(max)', 'SRU_GILTIG_FOM': 'varchar(max)', 'SRU_GILTIG_TOM': 'varchar(max)', 'SRU_ID': 'varchar(max)', 'SRU_ID_TEXT': 'varchar(max)', 'SRU_PASSIV': 'varchar(max)', 'SRU_TEXT': 'varchar(max)', 'ST_GILTIG_FOM': 'varchar(max)', 'ST_GILTIG_TOM': 'varchar(max)', 'ST_ID': 'varchar(max)', 'ST_ID_TEXT': 'varchar(max)', 'ST_PASSIV': 'varchar(max)', 'ST_TEXT': 'varchar(max)', 'SÖSRR_GILTIG_FOM': 'varchar(max)', 'SÖSRR_GILTIG_TOM': 'varchar(max)', 'SÖSRR_ID': 'varchar(max)', 'SÖSRR_ID_TEXT': 'varchar(max)', 'SÖSRR_PASSIV': 'varchar(max)', 'SÖSRR_TEXT': 'varchar(max)', 'UKTO_GILTIG_FOM': 'varchar(max)', 'UKTO_GILTIG_TOM': 'varchar(max)', 'UKTO_ID': 'varchar(max)', 'UKTO_ID_TEXT': 'varchar(max)', 'UKTO_PASSIV': 'varchar(max)', 'UKTO_TEXT': 'varchar(max)'},
    kind=dict(
        name=ModelKindName.FULL
    ),
    cron="@daily"
)

        
def execute(
    context: ExecutionContext,
    start: datetime,
    end: datetime,
    execution_time: datetime,
    **kwargs: t.Any,
) -> pd.DataFrame:
    query = f"""
	SELECT * FROM (SELECT 
 		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _data_modified_utc,
		CAST(CAST(GETDATE() AS datetime2) AT TIME ZONE 'CENTRAL EUROPEAN STANDARD TIME' AT TIME ZONE 'UTC' AS datetime2) as _metadata_modified_utc,
		'sosp_rd_sll_se_raindance_udp_udp_220' as _source,
		CONVERT(varchar(max), FMK_GILTIG_FOM, 126) AS FMK_GILTIG_FOM,
		CONVERT(varchar(max), FMK_GILTIG_TOM, 126) AS FMK_GILTIG_TOM,
		CAST(FMK_ID AS VARCHAR(MAX)) AS FMK_ID,
		CAST(FMK_ID_TEXT AS VARCHAR(MAX)) AS FMK_ID_TEXT,
		CAST(FMK_PASSIV AS VARCHAR(MAX)) AS FMK_PASSIV,
		CAST(FMK_TEXT AS VARCHAR(MAX)) AS FMK_TEXT,
		CONVERT(varchar(max), FRA01_GILTIG_FOM, 126) AS FRA01_GILTIG_FOM,
		CONVERT(varchar(max), FRA01_GILTIG_TOM, 126) AS FRA01_GILTIG_TOM,
		CAST(FRA01_ID AS VARCHAR(MAX)) AS FRA01_ID,
		CAST(FRA01_ID_TEXT AS VARCHAR(MAX)) AS FRA01_ID_TEXT,
		CAST(FRA01_PASSIV AS VARCHAR(MAX)) AS FRA01_PASSIV,
		CAST(FRA01_TEXT AS VARCHAR(MAX)) AS FRA01_TEXT,
		CONVERT(varchar(max), FRA03_GILTIG_FOM, 126) AS FRA03_GILTIG_FOM,
		CONVERT(varchar(max), FRA03_GILTIG_TOM, 126) AS FRA03_GILTIG_TOM,
		CAST(FRA03_ID AS VARCHAR(MAX)) AS FRA03_ID,
		CAST(FRA03_ID_TEXT AS VARCHAR(MAX)) AS FRA03_ID_TEXT,
		CAST(FRA03_PASSIV AS VARCHAR(MAX)) AS FRA03_PASSIV,
		CAST(FRA03_TEXT AS VARCHAR(MAX)) AS FRA03_TEXT,
		CONVERT(varchar(max), FRA05_GILTIG_FOM, 126) AS FRA05_GILTIG_FOM,
		CONVERT(varchar(max), FRA05_GILTIG_TOM, 126) AS FRA05_GILTIG_TOM,
		CAST(FRA05_ID AS VARCHAR(MAX)) AS FRA05_ID,
		CAST(FRA05_ID_TEXT AS VARCHAR(MAX)) AS FRA05_ID_TEXT,
		CAST(FRA05_PASSIV AS VARCHAR(MAX)) AS FRA05_PASSIV,
		CAST(FRA05_TEXT AS VARCHAR(MAX)) AS FRA05_TEXT,
		CONVERT(varchar(max), KBR_GILTIG_FOM, 126) AS KBR_GILTIG_FOM,
		CONVERT(varchar(max), KBR_GILTIG_TOM, 126) AS KBR_GILTIG_TOM,
		CAST(KBR_ID AS VARCHAR(MAX)) AS KBR_ID,
		CAST(KBR_ID_TEXT AS VARCHAR(MAX)) AS KBR_ID_TEXT,
		CAST(KBR_PASSIV AS VARCHAR(MAX)) AS KBR_PASSIV,
		CAST(KBR_TEXT AS VARCHAR(MAX)) AS KBR_TEXT,
		CONVERT(varchar(max), KONCRR_GILTIG_FOM, 126) AS KONCRR_GILTIG_FOM,
		CONVERT(varchar(max), KONCRR_GILTIG_TOM, 126) AS KONCRR_GILTIG_TOM,
		CAST(KONCRR_ID AS VARCHAR(MAX)) AS KONCRR_ID,
		CAST(KONCRR_ID_TEXT AS VARCHAR(MAX)) AS KONCRR_ID_TEXT,
		CAST(KONCRR_PASSIV AS VARCHAR(MAX)) AS KONCRR_PASSIV,
		CAST(KONCRR_TEXT AS VARCHAR(MAX)) AS KONCRR_TEXT,
		CONVERT(varchar(max), KONDEL_GILTIG_FOM, 126) AS KONDEL_GILTIG_FOM,
		CONVERT(varchar(max), KONDEL_GILTIG_TOM, 126) AS KONDEL_GILTIG_TOM,
		CAST(KONDEL_ID AS VARCHAR(MAX)) AS KONDEL_ID,
		CAST(KONDEL_ID_TEXT AS VARCHAR(MAX)) AS KONDEL_ID_TEXT,
		CAST(KONDEL_PASSIV AS VARCHAR(MAX)) AS KONDEL_PASSIV,
		CAST(KONDEL_TEXT AS VARCHAR(MAX)) AS KONDEL_TEXT,
		CONVERT(varchar(max), KONTO_GILTIG_FOM, 126) AS KONTO_GILTIG_FOM,
		CONVERT(varchar(max), KONTO_GILTIG_TOM, 126) AS KONTO_GILTIG_TOM,
		CAST(KONTO_ID AS VARCHAR(MAX)) AS KONTO_ID,
		CAST(KONTO_ID_TEXT AS VARCHAR(MAX)) AS KONTO_ID_TEXT,
		CAST(KONTO_PASSIV AS VARCHAR(MAX)) AS KONTO_PASSIV,
		CAST(KONTO_TEXT AS VARCHAR(MAX)) AS KONTO_TEXT,
		CONVERT(varchar(max), KTO1_GILTIG_FOM, 126) AS KTO1_GILTIG_FOM,
		CONVERT(varchar(max), KTO1_GILTIG_TOM, 126) AS KTO1_GILTIG_TOM,
		CAST(KTO1_ID AS VARCHAR(MAX)) AS KTO1_ID,
		CAST(KTO1_ID_TEXT AS VARCHAR(MAX)) AS KTO1_ID_TEXT,
		CAST(KTO1_PASSIV AS VARCHAR(MAX)) AS KTO1_PASSIV,
		CAST(KTO1_TEXT AS VARCHAR(MAX)) AS KTO1_TEXT,
		CONVERT(varchar(max), KTO2_GILTIG_FOM, 126) AS KTO2_GILTIG_FOM,
		CONVERT(varchar(max), KTO2_GILTIG_TOM, 126) AS KTO2_GILTIG_TOM,
		CAST(KTO2_ID AS VARCHAR(MAX)) AS KTO2_ID,
		CAST(KTO2_ID_TEXT AS VARCHAR(MAX)) AS KTO2_ID_TEXT,
		CAST(KTO2_PASSIV AS VARCHAR(MAX)) AS KTO2_PASSIV,
		CAST(KTO2_TEXT AS VARCHAR(MAX)) AS KTO2_TEXT,
		CONVERT(varchar(max), KTYP_GILTIG_FOM, 126) AS KTYP_GILTIG_FOM,
		CONVERT(varchar(max), KTYP_GILTIG_TOM, 126) AS KTYP_GILTIG_TOM,
		CAST(KTYP_ID AS VARCHAR(MAX)) AS KTYP_ID,
		CAST(KTYP_ID_TEXT AS VARCHAR(MAX)) AS KTYP_ID_TEXT,
		CAST(KTYP_PASSIV AS VARCHAR(MAX)) AS KTYP_PASSIV,
		CAST(KTYP_TEXT AS VARCHAR(MAX)) AS KTYP_TEXT,
		CONVERT(varchar(max), MKTO_GILTIG_FOM, 126) AS MKTO_GILTIG_FOM,
		CONVERT(varchar(max), MKTO_GILTIG_TOM, 126) AS MKTO_GILTIG_TOM,
		CAST(MKTO_ID AS VARCHAR(MAX)) AS MKTO_ID,
		CAST(MKTO_ID_TEXT AS VARCHAR(MAX)) AS MKTO_ID_TEXT,
		CAST(MKTO_PASSIV AS VARCHAR(MAX)) AS MKTO_PASSIV,
		CAST(MKTO_TEXT AS VARCHAR(MAX)) AS MKTO_TEXT,
		CONVERT(varchar(max), MS_GILTIG_FOM, 126) AS MS_GILTIG_FOM,
		CONVERT(varchar(max), MS_GILTIG_TOM, 126) AS MS_GILTIG_TOM,
		CAST(MS_ID AS VARCHAR(MAX)) AS MS_ID,
		CAST(MS_ID_TEXT AS VARCHAR(MAX)) AS MS_ID_TEXT,
		CAST(MS_PASSIV AS VARCHAR(MAX)) AS MS_PASSIV,
		CAST(MS_TEXT AS VARCHAR(MAX)) AS MS_TEXT,
		CONVERT(varchar(max), SA_GILTIG_FOM, 126) AS SA_GILTIG_FOM,
		CONVERT(varchar(max), SA_GILTIG_TOM, 126) AS SA_GILTIG_TOM,
		CAST(SA_ID AS VARCHAR(MAX)) AS SA_ID,
		CAST(SA_ID_TEXT AS VARCHAR(MAX)) AS SA_ID_TEXT,
		CAST(SA_PASSIV AS VARCHAR(MAX)) AS SA_PASSIV,
		CAST(SA_TEXT AS VARCHAR(MAX)) AS SA_TEXT,
		CONVERT(varchar(max), SKRD_GILTIG_FOM, 126) AS SKRD_GILTIG_FOM,
		CONVERT(varchar(max), SKRD_GILTIG_TOM, 126) AS SKRD_GILTIG_TOM,
		CAST(SKRD_ID AS VARCHAR(MAX)) AS SKRD_ID,
		CAST(SKRD_ID_TEXT AS VARCHAR(MAX)) AS SKRD_ID_TEXT,
		CAST(SKRD_PASSIV AS VARCHAR(MAX)) AS SKRD_PASSIV,
		CAST(SKRD_TEXT AS VARCHAR(MAX)) AS SKRD_TEXT,
		CONVERT(varchar(max), SRU_GILTIG_FOM, 126) AS SRU_GILTIG_FOM,
		CONVERT(varchar(max), SRU_GILTIG_TOM, 126) AS SRU_GILTIG_TOM,
		CAST(SRU_ID AS VARCHAR(MAX)) AS SRU_ID,
		CAST(SRU_ID_TEXT AS VARCHAR(MAX)) AS SRU_ID_TEXT,
		CAST(SRU_PASSIV AS VARCHAR(MAX)) AS SRU_PASSIV,
		CAST(SRU_TEXT AS VARCHAR(MAX)) AS SRU_TEXT,
		CONVERT(varchar(max), ST_GILTIG_FOM, 126) AS ST_GILTIG_FOM,
		CONVERT(varchar(max), ST_GILTIG_TOM, 126) AS ST_GILTIG_TOM,
		CAST(ST_ID AS VARCHAR(MAX)) AS ST_ID,
		CAST(ST_ID_TEXT AS VARCHAR(MAX)) AS ST_ID_TEXT,
		CAST(ST_PASSIV AS VARCHAR(MAX)) AS ST_PASSIV,
		CAST(ST_TEXT AS VARCHAR(MAX)) AS ST_TEXT,
		CONVERT(varchar(max), SÖSRR_GILTIG_FOM, 126) AS SÖSRR_GILTIG_FOM,
		CONVERT(varchar(max), SÖSRR_GILTIG_TOM, 126) AS SÖSRR_GILTIG_TOM,
		CAST(SÖSRR_ID AS VARCHAR(MAX)) AS SÖSRR_ID,
		CAST(SÖSRR_ID_TEXT AS VARCHAR(MAX)) AS SÖSRR_ID_TEXT,
		CAST(SÖSRR_PASSIV AS VARCHAR(MAX)) AS SÖSRR_PASSIV,
		CAST(SÖSRR_TEXT AS VARCHAR(MAX)) AS SÖSRR_TEXT,
		CONVERT(varchar(max), UKTO_GILTIG_FOM, 126) AS UKTO_GILTIG_FOM,
		CONVERT(varchar(max), UKTO_GILTIG_TOM, 126) AS UKTO_GILTIG_TOM,
		CAST(UKTO_ID AS VARCHAR(MAX)) AS UKTO_ID,
		CAST(UKTO_ID_TEXT AS VARCHAR(MAX)) AS UKTO_ID_TEXT,
		CAST(UKTO_PASSIV AS VARCHAR(MAX)) AS UKTO_PASSIV,
		CAST(UKTO_TEXT AS VARCHAR(MAX)) AS UKTO_TEXT 
	FROM raindance_udp.udp_220.EK_DIM_OBJ_KONTO ) y

	"""
    return read(query=query, server_url="sosp.rd.sll.se")
    